### ISSUE TITLE
Filter points with bad precision in tracking mode

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#2055] opened 2021-07-22 15:58 UTC
with QFIELD 2.0 (all versions) and on samsung sm-g390f, android 9, activating "precision conditions" does not seem to work.
points, with an error of several kms, are taken. 
![Screenshot_20210720-121833_QField](https://user-images.githubusercontent.com/41300254/126666510-d4e2ebac-82e5-4c3e-bb6a-15850058de19.jpg)
![Screenshot_20210720-121910_QField](https://user-images.githubusercontent.com/41300254/126666513-49b6acd7-0ca3-48f4-bc2b-8f26dd6b46a6.jpg)
![error](https://user-images.githubusercontent.com/41300254/126666566-4c001f59-bcca-4e38-a46c-521964b6c603.jpg)

### Reproduction Steps:
In "settings" activate "activate precision conditions".
select a line vector.
"Start monitoring".
indicate the "tracking parameters".
the plot does not respect the conditions of precision. 

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
* the problem does not seem to occur on an tab active 3 with android 10.

**Comment by m-kuhn** [comment] 2021-07-26 06:35
@nirvn the accuracy requirement is currently only implemented for manual points and not filtering anything for tracking, correct?

**Comment by nirvn** [comment] 2021-07-26 06:36
@m-kuhn , correct.

**Comment by m-kuhn** [comment] 2021-07-26 06:46
@RAFALCO the intended use case for this is to prevent manually taking points with a precision below a threshold, where the user can actively react to this condition.
Including this in tracking would be a nice enhancement, we'll need to make sure the user is informed about why no points are recorded.

**Comment by RAFALCO** [comment] 2021-07-27 05:48
Ok,
I understand.

**Comment by nirvn** [comment] 2022-08-25 05:06
Closing as a duplicate of enhancement #1138 .

**Closed by nirvn** 2022-08-25 05:06 UTC
Labels: ENHANCEMENT
