### ISSUE TITLE
Widget Type Date/Time: typing became complicated

### ISSUE THREAD

**Issue by domhag** [opengisch/QField#842] opened 2020-02-17 08:15 UTC
I use the widget Type _Date/Time_ and the format _HH:mm_. Type in of the first three numbers (HH:m) is ok. Then the cursor jumps back on position and the next time you type, the third number is overwritten. 
This difficulty exists in the newer versions (1.3.4 and also 1.4.2) and was not present in previous versions (e.g. 1.0.3).

[bugreport_time.zip](https://github.com/opengisch/QField/files/4212496/bugreport_time.zip)

**Comment by saemiw** [comment] 2020-02-17 08:28
We noticed this as well. Should be fixed as bugfixing...we paid for the implementation of the widget...;D

**Comment by suricactus** [comment] 2021-01-14 09:17
Unable to reproduce on the latest master. Can you please confirm the issue still exists? If you record your screen with the unfortunate behaviour would be great. Thanks.

**Comment by domhag** [comment] 2021-02-01 19:50
See the attached screen recording. 
Date/time-widget is complicated to type in manualy. The first number after the hyphen is overwritten, so you often have to go back one step and type in again. In most case, you can avoid it by choosing calender popup, which works well. Not a serious issue but irritating. 
Qfield v1.7.8

https://user-images.githubusercontent.com/60700681/106510300-092ec500-64cf-11eb-8411-ddbb76c581c1.mp4

**Comment by nirvn** [comment] 2022-07-31 09:00
Irrelevant in current QField, a time/date panel UI has been implemented.

**Closed by nirvn** 2022-07-31 09:00 UTC
Labels: BUG
