### ISSUE TITLE
Geotag not written to photo taken through QField

### ISSUE THREAD

**Issue by Geol0gue** [opengisch/QField#290] opened 2018-06-07 08:50 UTC
Photos taken through QField do not have geotag information appended in the exif data.

This would be really useful functionality to have - after taking photos in the field we normally run photos through third party software to produce a formatted report where photos are located as points on a map. Without the exif data we can't run this process.

**Comment by Geol0gue** [comment] 2018-06-12 17:59
Using the native camera crashes the app (v0.10.13).

Unchecking this option allows a picture to be taken and stored through the app. The issue is that this picture doesn't have a geotag.

**Comment by m-kuhn** [comment] 2018-06-12 21:32
Sounds like a good feature request to support that for the new camera implementation.
If there is interest to fund this feature, let us know and we'll have a look and estimate the complexity.

**Comment by FilipjFry** [comment] 2019-01-22 16:37
Don't know if it is really the good place for this one but I think my question is more or less related to this thread. When I use the photo functionality in Qfield, it stores the pictures in a DCIM folder, and the filenames are tagged with the time and date. I would like to be able to name the jpg file with the ID of my station.

Also, is there a way to take several pictures on one station, if so how would one do to increment filenames with ID_Station+1 ?

Thanks, 

Fry.

**Comment by magana71** [comment] 2019-03-21 12:19
I have the same problem off FilipjFry.

Someone has the solution?

**Comment by magana71** [comment] 2019-03-21 12:19
> Don't know if it is really the good place for this one but I think my question is more or less related to this thread. When I use the photo functionality in Qfield, it stores the pictures in a DCIM folder, and the filenames are tagged with the time and date. I would like to be able to name the jpg file with the ID of my station.
> 
> Also, is there a way to take several pictures on one station, if so how would one do to increment filenames with ID_Station+1 ?
> 
> Thanks,
> 
> Fry.

Already have the solution?

**Comment by michaelaup76** [comment] 2019-07-29 15:19
Dear all,
I just got the same issue, with a Samsung Galaxy S5e tablet running Android 9. 
I can create the form and include picture field. I can take picture and it are well linked to my feature. But the pictures files have no geotag, witch is actually a problem for me (I must be able to put every picture at the right place on a map).
Can somebody give me an explanation ? It was well working on my Samsung A5 phone running Android 7, but not on the tablet.
Thanks.
Michaël

**Comment by m-kuhn** [comment] 2019-07-29 15:22
Hi all,
it's only working for devices where the native camera setting does not crash (mostly Android 5). We have a solution but will need sponsoring to implement this. We already have parts of the required funding but would be very happy to have this working soon.

Please contact info@opengis.ch, so we can soon reach our goal and fix this!

Thanks in advance.

**Comment by michaelaup76** [comment] 2019-07-29 15:27
I just sent you a mail on info@opengis.ch

**Comment by signedav** [comment] 2019-11-18 11:42
It's very well possible that this is fixed with enabling the native camera which will be implemented. It's coming soon.

**Comment by m-kuhn** [comment] 2020-01-31 13:42
Can you try the current 1.4.1 release with native camera and check if this is fixed?
If your system camera doesn't write exif when used through QField, use opencamera instead.
Thank you.

**Comment by m-kuhn** [comment] 2020-04-21 08:01
Closed since there is no feedback. This is supposed to be working.

**Closed by m-kuhn** 2020-04-21 08:01 UTC
Labels: BUG, feedback, nativecamera

**Comment by michaelaup76** [comment] 2020-04-21 09:49
Hello Matthias,

I’m sorry for my late answer,  I saw you’ve closed the ticket for this support case.
I can confirm you that this function is now perfectly working ! Many thanks for your work and support.
Best regards
Michaël

Take care of you and yours !




De : Matthias Kuhn <notifications@github.com>
Envoyé : mardi 21 avril 2020 10:02
À : opengisch/QField <QField@noreply.github.com>
Cc : Michaël Aupaix <michael.aupaix@kdrix.be>; Comment <comment@noreply.github.com>
Objet : Re: [opengisch/QField] Geotag not written to photo taken through QField (#290)


Closed since there is no feedback. This is supposed to be working.
