### ISSUE TITLE
Selected points are not properly higlighted

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#64] opened 2016-08-22 13:14 UTC
when I click on a point it is selected corecctly but I only see a very small (1px) yellow dot showing tat the point is higlighted

**Comment by geoplanteam** [comment] 2018-08-14 14:00
Is the Issue #64 still pending or should it be solved with Issue #85?
I still have the problem on version 0.10.13 as described by Marco.

**Comment by m-kuhn** [comment] 2018-08-14 14:02
It is still an issue, #85 was a duplicate of this issue, so it was closed to have only this one left open.

**Closed** 2019-01-31 19:33 UTC

**Comment by geoplanteam** [comment] 2019-04-02 15:19
Dear all

I still have problems with this issue. I'm quite sure that with rc3 it was resolved. But now I don't get any highlight anymore (no 1px dot neither).

Does anybody can confirm this?
Regards Christoph

**Comment by geoplanteam** [comment] 2019-04-02 15:24
Sorry,
the issue is allready logged with #533 
Christoph
