### ISSUE TITLE
Qfield crash when entering antenna height correction value

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1027] opened 2020-05-14 16:29 UTC
There is a severe crash when you enter a value in the antenna height correction field. Sometimes Qfield has to be removed from device and reinstalled.

### Reproduction Steps:

1. Enable antenna height correction.
2. Enter a value in antenna height correction field. Sometimes it only crashes when a decimal point is entered (eg. 1.66).

### Expected behavior:

Decimals should be no problem.
### Observed behavior:

Crashes unreliably.

**QField version:** 1.5.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment] 2020-05-19 05:44
Thanks for reporting. I can reproduce.
Even if it would not support decimals it should at least avoid the possibility to enter them.

**Comment by soester** [comment] 2020-05-19 07:39
@signedav 
for this feature it is absolutely necessary to enter decimals. Antenna height correction was introduced to work with high precision GNSS Receivers. High precision surveying without decimals doesn't  work. Would be great if you or @m-kuhn  could have a look at it!

**Comment by soester** [comment] 2020-05-19 08:07
@signedav 
actually it does work sometimes. i managed to collect a reference point twice. once with antenna height correction and once without.
The difference was around 3 cm, which is very good for NTRIP corrected RTK GNSS!

Some details on my setup:
QField 1.5.3
Mock provider: Lefebure NTRIP Client
Samsung Galaxy Tab Active 2 (SM-T395)
Android 9

**Comment by signedav** [comment] 2020-05-20 11:57
Okay, we will care about it.

**Comment by m-kuhn** [comment] 2020-05-23 15:23
@soester do you have the possibility to send an error report when it crashes?
@signedav do you already have a trace?

**Comment by signedav** [comment] 2020-05-23 20:11
Not yet. But since I can reproduce I can debug I guess. I'll check on monday.

**Comment by signedav** [comment] 2020-05-25 14:34
@soester While I have been able to let it crash some days ago, I cannot reproduce anymore. Sadly it just works. So maybe a trace could be helpful or if you find any scenarios to make it crash for sure, would be even better. Thanks a lot.

**Comment by EulenspiegelTill** [comment] 2020-05-26 06:23
@signedav will try to reproduce it stable to give you the trace this afternoon.

**Comment by EulenspiegelTill** [comment] 2020-05-26 16:01
@signedav It did crash again. Was recording a screenvideo and did send a google craslog.. can i provide you more?
Videolink: https://wolke.messtechnik.ch/index.php/s/Y7MLtCa7Fsfe7XS

**Comment by m-kuhn** [comment] 2020-05-26 16:16
Can you give us some details about the device, android and qfield version and time of crash? This will make it easier to locate your specific report.

**Comment by EulenspiegelTill** [comment] 2020-05-26 16:21
@m-kuhn 
Samsung Galaxy Tab active 2, It was today around 17:30 and the qfield version was 1.5.3 (code: 010503991) i suppose, but i had to reinstall it.

**Comment by soester** [comment] 2020-05-26 16:58
there should also be a report on 2020-05-14T09:42:01.000 or a bit before.
same setup.

**Comment by signedav** [comment] 2020-05-27 05:40
Have been able to reproduce again. Sadly not during a debugging session. But could make the attached logcat.
[antenna_1.txt](https://github.com/opengisch/QField/files/4686642/antenna_1.txt)

**Comment by signedav** [comment] 2020-05-27 06:11
When the APK is created here #1038 Would it be possible to test it again @soester or @EulenspiegelTill?
I couldn't reproduce anymore after this fix.

**Comment by EulenspiegelTill** [comment] 2020-05-27 11:53
@signedav  
THX! I will test it this evening or tomorrow and give you the feedback.

**Comment by EulenspiegelTill** [comment] 2020-05-27 20:04
@signedav 
Observed behaivour: I was able to input the Antenna shift and collect point. BUT the blue dot of the GNSS position was not moving anymore when i walked away. The center of the curser/gnss moved away when i clicked center on position. And when i closed the app and restarted it again it crashed on restart again and again..

Screencast:
https://wolke.messtechnik.ch/index.php/s/mAbQgdFDLrjM2a6

**Comment by signedav** [comment] 2020-05-29 14:13
Did this behavior that it stops getting the current position before the issue occurred with the decimal points?

There are two issues. The first is the one that it crashed after entering digits. This should be fixed.
The second one is the one loosing the position you found. But maybe this has been existing since the first implementation. I have it with this APK as well. https://github.com/opengisch/QField/pull/677#issuecomment-568969622

**Comment by m-kuhn** [comment] 2020-05-29 14:31
@signedav do you have any lead on the second issue=

**Comment by EulenspiegelTill** [comment] 2020-06-02 07:01
> Did this behavior that it stops getting the current position before the issue occurred with the decimal points?
> 
> There are two issues. The first is the one that it crashed after entering digits. This should be fixed.
> The second one is the one loosing the position you found. But maybe this has been existing since the first implementation. I have it with this APK as well. [#677 (comment)](https://github.com/opengisch/QField/pull/677#issuecomment-568969622)

no this behaviour was not recognized before. the blue dot was always gently following...

**Comment by signedav** [comment] 2020-06-02 07:19
Okay, thanks.

What is the version you used, where you have been able to enter an antenna height with decimals and still had a moving GPS indicator after?

Because on my device it's not working in the APK created here https://github.com/opengisch/QField/pull/677#issuecomment-568969622
and 1.4.4. Olavtoppen neither, downloaded here: https://github.com/opengisch/QField/releases/download/v1.4.4/qfield-v1.4.4-arm64_v8a.apk

**Comment by signedav** [comment] 2020-06-02 08:30
@EulenspiegelTill Could you make another test with the APK uploaded here: https://github.com/opengisch/QField/pull/1038#issuecomment-637377719

Thanks a lot!

**Comment by EulenspiegelTill** [comment] 2020-06-02 13:58
@signedav 
With this APK it seem's to work fine! Blue dot is following and i can put in decimal height-shifts to correct my gnss antenna. Tested by running around on the balcony with cm-accuracy, will test it again on the long run in the field or the way home this week and give you feedback.

Sorry for the question before. the moving blue dot, i was not able to observe with entering a decimal height, only without a antenna height correction.

**Closed** 2020-06-03 12:45 UTC
Labels: BUG

**Comment by signedav** [comment] 2020-06-04 06:19
Thanks for all the testing @EulenspiegelTill :+1:
