### ISSUE TITLE
Unique values | No suggestions in QField

### ISSUE THREAD

**Issue by TSanderPGG** [opengisch/QField#1931] opened 2021-05-28 07:40 UTC
I have a layer with a polygon geometry. In one of the fields, I chose editable unique values in the attributes form of the field so I get a list of previously entered values by entering the first letter. In QGIS everything works fine: when I enter the first letter of the value it shows me a list of previous values with the same letter (see picture below).
![QGIS_suggestion](https://user-images.githubusercontent.com/80879779/119945631-02ecb900-bf96-11eb-892f-d4bb6427ae09.png)

In QField however that does not work (neither in standard editing mode nore in fast editing mode, see picture below). I'm quite sure it worked before. Can someone relate and is this an issue? Am I doing something wrong or is this not provided anymore?

![GifMaker_20210528093645377](https://user-images.githubusercontent.com/80879779/119947675-49dbae00-bf98-11eb-867e-64b70ac1237e.gif)

Thanks for your help and kind regards!

**Comment by m-kuhn** [comment] 2021-05-28 08:15
The unique values widget has not (yet) been implemented in qfield

**Comment by TSanderPGG** [comment] 2021-05-28 10:02
Hm okay, maybe I confused the suggestion field with relation reference...! Sorry..!

**Comment by m-kuhn** [comment] 2021-05-28 10:04
Duplicate of #98

**Closed by m-kuhn** 2021-05-28 10:04 UTC
