### ISSUE TITLE
 When taking a photo QField crashes

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#83] opened 2016-10-21 14:16 UTC
Crashes when taking a photo with external sours widget. Testet devices: Lenovo tab3 8 (crashes, android 6), Samsung Galaxy core Prime (restart only, Android 5), Sony Xperia tablet z1 (every second photo nor add ir crashes, android 4.3)

**QField version:** [0.8.7]

**Comment by m-kuhn** [comment] 2016-10-21 14:39
Duplicate of #53

**Closed by m-kuhn** 2016-10-21 14:39 UTC
