### ISSUE TITLE
QField crashing on photo taking or app swipe

### ISSUE THREAD

**Issue by veezee2021** [opengisch/QField#2315] opened 2021-11-26 13:42 UTC
QField crashes (often but not always) when adding a photo to record or when leaving the app to go to another app.

### Reproduction Steps (Photo crash):
1. Add photo to record
2. Camera opens, take photo, ask to confirm photo
3. On confirm, comes back to viewer for taking photo
4. On taking photo, it crashes

### Reproduction Steps (leaving the app crash):
1. Leaves the app to go to another app (any, doesn't matter)
2. Try to come back to Qfield project
3. Qfield crashes

### Expected behavior:
Photo attached to record

### Observed behavior:
Qfield crashes

**QField version:**1.10.0
Android version: 11 RP1A.200720.011
MIUI version : 12.5.1.0(RKSEUXM)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: cannot reproduce with Demo files. Other very simple projects with just photo taking are reproducing the same issue. The crash is not reproduced with another phone (android 5.1)

**Comment by nirvn** [comment] 2021-11-28 08:46
@veezee2021 , are you using the native camera or have you turned that setting off:
![image](https://user-images.githubusercontent.com/1728657/143735741-ec1cc933-bc46-4fcb-8413-5a3faf6083a4.png)

Either way, try to toggle the setting to see if your crash is gone. I can't reproduce here on a Samsung device.

If you are able to give us adb logcat of your crashes, that'd be great. I assume you have a Xiaomi device, which is not something we've done loads of test with in the past.

**Comment by m-kuhn** [comment] 2021-11-28 10:07
Possibly related to https://github.com/opengisch/QField/issues/1671

**Comment by veezee2021** [comment] 2021-11-28 14:10
@nirvn , yes it is correct, I am using a Xiaomi Redmi Note 10.
I am suspecting, but of course have no proof, that this is the inbuilt camera software that causes the crash (although I am unsure if this could also cause the app to restart when I am switching between apps).
Regarding the 'Use native camera' setting, this was the first thing I tried when it crashed. The problem is that, for a reason probably related to Xiaomi, I am unable to change the default camera software of the device to another software (I have for example Open Camera installed and working fine). The consequence is that when I toggle off the  'Use native camera' setting, I cannot take any photo anymore from QField: I only can load photos already taken.
Very happy to provide you with an adb logcat but not familiar with this tool. Could you point towards what needs to be done to produce it?

**Comment by veezee2021** [comment] 2021-11-28 14:20
@m-kuhn, yes you are totally correct. I read the whole thread and I am experiencing the same 'random' problem that is described there. Any update if there is some investigation going on with this? QField is simply non-usable in the field with this bug in my case. Will have to find other devices that do not reproduce the issue.

**Comment by nirvn** [comment] 2021-11-28 14:47
@veezee2021 , hopefully the non native camera should stabilize things for you. There's a known regression in 1.10.0 which prevents non native camera from being usable. Stay put for an update in the coming week-ish.

**Comment by m-kuhn** [comment] 2022-02-05 17:19
Can you download this apk (arm64) and confirm if the crash still exists?
https://github.com/opengisch/QField/pull/2486/files?w=1

**Comment by m-kuhn** [comment] 2022-02-05 17:20
Potentially related to #1671

**Comment by veezee2021** [comment] 2022-02-14 09:21
sorry, had missed this. Yes will do.
Now using a samsung phone with no issue

**Comment by m-kuhn** [comment] 2023-05-31 06:19
Duplicate of https://github.com/opengisch/QField/issues/1671

**Closed by m-kuhn** 2023-05-31 06:19 UTC
