### ISSUE TITLE
Support for switching attribute forms when switching themes

### ISSUE THREAD

**Issue by zezzagio** [opengisch/QField#1108] opened 2020-07-04 15:04 UTC
Switching theme doesn't change the edit mask of a layer associated to the theme. Or, actually, it does, but only if the first operation of a session.

### Reproduction Steps:
Refer to https://github.com/zezzagio/qfield_theme_issue for a complete sample of files
that reproduces the behaviour.

The layer "test" has two styles "type" and "name"; each style has a different customized attributes mask. The project has two themes: the theme "type" shows the layer "test" with the style "type"; the theme "name" shows the layer "test" with the sytle "name".

### Expected behavior:

Changing the theme, the state and the symbologies of the layers are changed accordingly, comprised styles and custom attributes masks. This is the behaviour in QGis.

### Observed behavior:

Observed behaviour in QField:

    Open the application; open the project test; "type" theme is selected, points are red, label is "field1";

    -a) select one feature, open the edit mask; the mask of style "type" is open.

    -b) change theme, select theme "name"; points are green, label is "field2";

    -c) select one feature, open the edit mask; the mask of style "type" is open.

Close the application.

    Open the application; open the project test; "type" theme is selected, points are red, label is "field1";

    -a) change theme, select theme "name"; points are green, label is "field2";

    -b) select one feature, open the edit mask; the mask of style "name" is open.

    -c) change theme, select theme "type"; points are red, label is "field1";

    -d) select one feature, open the edit mask; the mask of style "name" is open.

Sample file:
[qfield_problem.zip](https://github.com/opengisch/QField/files/4873043/qfield_problem.zip)

**QField version: 1.5.3 (010503992)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: I don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by zezzagio** [comment] 2020-07-05 16:51
I'd like very much to see this supported; now I have to use two layers on the same table in order to get what I need. What troubled me the most, though, was the incoherent behaviour: in some cases the attribute form is switched, in other ones it isn't.

I'd like to contribute, too, but I'm afraid I can be of little help: I'm not a professional programmer, I never developed anything for Android, and actually I don't even know how to begin to make my system able to compile QField. I'm studying the code anyway, and I'll see if I can come up with something.

**Comment by soester** [comment] 2020-08-06 12:59
I can confirm the behaviour stated above.

As https://github.com/opengisch/qfieldsync/issues/111 was fixed with the use of this functionality (change layerstyle to get  attribute form adapted to theme) in mind, this seems to me more like a bug than an enhancement.

*Qfiled doesn't reliably use the form settings of the current layerstyle.*

I found also this: Fields occouring in both layerstyles but with different default values, use the default values of the respective layerstyle, but the form doesn't change. This is very confusing. 
I have extended the sample provided by @zezzagio to show this behaviour. Works nicely in QGIS, but not in Qfield.
[qfield_problem_extended.zip](https://github.com/opengisch/QField/files/5034847/qfield_problem_extended.zip)

@m-kuhn is this an easy fix? 
We would be glad to contribute! Maybe @zezzagio would also be able to fund something?

**Comment by zezzagio** [comment] 2020-08-06 13:35
>@m-kuhn is this an easy fix?
> We would be glad to contribute! Maybe @zezzagio would also be able to fund something?

As I said, I never developed anything on android, and can't even compile QField on my system.

I suppose it shouldn't be such a difficult fix (or change): form support is already here; it seems a matter of getting the form of the current theme and applying it. I was hoping to at least read the code and find out where to intervene, but so far I have not been able to do it.

Sorry to be of so little help.

**Comment by nirvn** [comment] 2021-01-26 04:29
@zezzagio , @soester , I'm unable to replicate the issue /  implementation gap with QField master, can you guys give it a try and see if it works now? If not, a GIF and/or expanded steps to reproduce would be needed.

**Comment by nirvn** [comment] 2021-01-26 04:31
I.e., here's what I see using @zezzagio 's test project:
![Peek 2021-01-26 11-30](https://user-images.githubusercontent.com/1728657/105800701-f0537a80-5fc9-11eb-8984-0f4e5d6a4f7a.gif)

**Comment by soester** [comment] 2021-01-26 09:52
@nirvn 
here's a screencast with my extended project [qfield_problem_extended.zip](https://github.com/opengisch/QField/files/5034847/qfield_problem_extended.zip).

https://user-images.githubusercontent.com/28543978/105828291-407b0e80-5fc3-11eb-8131-ef9aa431573f.mov

Identify seems to work fine. Also the problem with the default values seems to be fixed.
The problem apparently appears only when digitizing new features. 

In the sample project just  the order of 'field1' and 'field2' in the form should be changed when switching theme. We have a project with rather complex forms (conditions etc.) maybe i can do a test with this project later on...

**Comment by nirvn** [comment] 2021-01-26 09:57
@soester , good to read that the work put in QField has fixed some of the issues you were seeing earlier in 2020. I'll have a look at feature addition. Thanks for the extra details.

**Comment by soester** [comment] 2021-01-26 10:04
> good to read that the work put in QField has fixed some of the issues you were seeing earlier in 2020
QField is getting better and better constantly! Its a joy to see how much nicer all works and looks!
But i think its never ending :)

**Closed** 2021-02-08 15:22 UTC
Labels: ENHANCEMENT
