### ISSUE TITLE
QField overwrites imported project if project is imported again

### ISSUE THREAD

**Issue by soester** [opengisch/QField#2694] opened 2022-04-04 20:42 UTC
If you import a 'project from folder' to QField, collect data on that project and then import the original 'project from folder' again, QField overwrites the first project without any warning. All data is lost?

https://user-images.githubusercontent.com/28543978/161626159-ece88398-7070-42cd-8378-5215d65966e7.mp4

**QField version:** 2.0.14 8f9a8
Android 11 (Tab Active 3, Samsung)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Never tested import on older version
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by soester** [comment] 2022-04-06 09:49
Addition:
Qfield only overwrites files with the same name of the newly imported ones.
Eg. if you dont have a DCIM folder in the original project folder the DCIM folder with the attached fotos stays there. Also exported pdfs wont get overwritten.

**Comment by jfmoyen** [comment] 2022-04-08 08:56
I think it's  feature, not a bug. With the recent changes in Android access policies, the only way to get QField to access a newer version of the project is to re-import it. If QField did not overwrite, it would be impossible to import a modified version of an existing project (or you would have to create a new name, and a version hell !).

**Comment by soester** [comment] 2022-04-08 09:25
yes, i know about the new access policies. if it is a feature, it is a very dangerous feature.
my point is, that one can delete a full day of work with a few taps without even beeing warned.

QField could for example put up a warning dialog:
>> "hey you're importing a new folder with the same name. do you really want to overwrite it?" 
and give the options to
i) overwirte  
ii) rename the folder during import 
iii) cancel

**Comment by jfmoyen** [comment] 2022-04-08 11:22
I agree, a warning would be the right thing to do. You may want to re-import a project, perhaps because after a field day you tweak the data on desktop and put it back to your mobile device; but you do not want this to happen accidentally. So you should have a choice.

**Comment by nirvn** [comment] 2022-04-13 05:37
This PR (https://github.com/opengisch/QField/pull/2733) implements an overwrite warning dialog when trying to import a project or dataset(s) already present in the relevant import directories.

**Comment by nirvn** [comment] 2022-04-14 06:57
@soester , @jfmoyen , let us know if we can close this issue after testing the above-mentioned APKs.

**Comment by nirvn** [comment] 2022-04-14 15:44
@jfmoyen , thanks for testing.

**Closed by nirvn** 2022-04-14 15:44 UTC
Labels: feedback
