### ISSUE TITLE
autogenerate geometry based on tracking

### ISSUE THREAD

**Issue by geostonemarten** [opengisch/QField#607] opened 2019-07-31 08:07 UTC
Objectif is to autogenerate information in relation to a tracking

2 possibilities: 
set point with position : this is ok but I need also auto generate point in relation to speed, bearing and time delay.
set line with form information with geometry based on GPS position. The start declaration generate automaticly a new line and stop the last line.

**Comment by m-kuhn** [comment] 2019-08-20 13:23
Is this a duplicate of of https://github.com/opengisch/QField/issues/111

**Closed** 2019-09-05 13:06 UTC
Labels: duplicate
