### ISSUE TITLE
How to deal with duplicated data

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#142] opened 2017-07-21 10:46 UTC
I have an issue with qfield. Is there any way to prevent creating duplicated data at each synchronisation. I would be very pleased if I get pertinent help. 

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment] 2017-07-28 09:05
Can you fill the information in the issue template so we know how to reproduce this behavior?

Please note that you can push issues up on the priority queue by providing a fix or by making a support contract.

**Comment by signedav** [comment] 2018-03-26 06:14
Hi @zakigates 
Is this still an issue? If yes, can you please provide us the needed information? Thanks!

**Comment by signedav** [comment] 2019-11-18 16:35
I close this since I didn't received any feedback.
Feel free to reopen it @zakigates if the problem persists.

**Closed by signedav** 2019-11-18 16:35 UTC
