### ISSUE TITLE
Wrongly remembered value in numeric fields

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#1470] opened 2020-12-08 09:22 UTC
**Fast Editing Mode displays data from first feature when constraints met, does not retain all of last attribute entered- 1.7.7**

When Fast Editing Mode is enabled, once the form is complete (i.e. all constraints met), the UI immediately shows attributes from the first feature (unless save last value checkbox is ticked, then it shows values from the previously digitised feature). 

No further edits are registered until the form is closed and reopened, also because of this only the first character is recorded for the final attribute required to meet constraints.

This appears to be new to 1.7.7 and later builds, it worked fine in 1.7.6

### Reproduction Steps:

1. Enable Fast Editing Mode
2. Ensure your form has one attribute with a simple enforced constraint (e.g. not null), do not enable saving values from the last feature
3. Digitise the first feature, it will be normal
4. Digitise the next feature. As soon as the constraint is met for that attribute, all attributes on the form will show values from the first feature

### Expected behavior:

The form should keep showing the current feature's values when all constraints are met and the feature is saved.

Further edits should be possible and retained while the form remains open.

### Observed behavior:

When Fast Editing Mode is enabled and all constraints are met, the feature is saved to disk, but on the screen it changes all the other values to those of the first feature. Upon exiting the attribute editor and inspecting the newly created feature, the correct attributes are displayed.

Additionally, because of the above, in Fast Editing Mode, as soon as you enter one character in the last field required to meet all constraints, the form is saved - but does not retain any additional characters. So if your last attribute is "61", you type "6", the form immediately saves and then shows the attributes from the first feature, and even if you delete what's there and type more, when you exit the form and inspect the feature it (a) doesn't show any of the data you've since entered and (b) only shows "6"

### Screenshots and GIFs

See mp4 in zip below - note values of first feature and subsequent ones

[QField Fast Edit Mode digitising issue.zip](https://github.com/opengisch/QField/files/5658155/QField.Fast.Edit.Mode.digitising.issue.zip)

See also gif in [this comment](https://github.com/opengisch/QField/issues/977#issuecomment-740386759) on #977 

**QField version:** 1.7.7 (from Google Play), also reproduced in Beta 1374
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, also happens on different Android devices.

**Comment by signedav** [comment] 2020-12-11 08:30
Thanks for reporting. I think this is not concerning constraints and not concerning fast mode but numeric fields in every case.

I made this with the current master and simple bee farming demo project:
![value on save](https://user-images.githubusercontent.com/28384354/101880651-8efb5780-3b93-11eb-93f6-a00962c712a6.gif)

**Comment by signedav** [comment] 2020-12-11 08:51
On the mobile phone I cannot reproduce consistently. Maybe @suricactus has already an idea, what could be the cause, since you worked with default values (no idea if this is related)?

**Comment by suricactus** [comment] 2020-12-11 11:32
Just a wild guess from https://github.com/opengisch/QField/commit/ebd45563bb74dae1cbc0c0bef92b7f59d8ce69e9 is that `createdFeature` and `mFeature` need to be the same. Not sure though.

**Comment by nirvn** [comment] 2021-02-10 10:25
@she-weeds , thanks for reporting, it'll be fixed in upcoming 1.8.4.

**Closed by nirvn** 2021-02-10 10:25 UTC
Labels: BUG
