### ISSUE TITLE
Unfortunately QField has stopped

### ISSUE THREAD

**Issue by gyttza** [opengisch/QField#55] opened 2016-07-19 10:06 UTC
When I run QField, the program crashes, prompted by the "QField has stopped Unfortunately".Qt in the application output error prompt as follows:
```
W/System.err( 2460): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2460): 	at android.os.Looper.loop(Looper.java:137)
W/System.err( 2460): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
W/System.err( 2460): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2460): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err( 2460): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
W/System.err( 2460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
W/System.err( 2460): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 2460): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/VectorDrawable
W/System.err( 2460): 	... 25 more
W/System.err( 2460): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.VectorDrawable" on path: DexPathList[[zip file "/data/app/ch.opengis.qfield-1.apk"],nativeLibraryDirectories=[/data/app-lib/ch.opengis.qfield-1, /system/lib]]
W/System.err( 2460): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
W/System.err( 2460): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err( 2460): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err( 2460): 	... 25 more
W/ResourceType( 2460): Skipping entry 0x10804d8 in package table 0 because it is not complex!
D/dalvikvm( 2460): GC_FOR_ALLOC freed 345K, 12% free 4538K/5152K, paused 19ms, total 19ms
D/dalvikvm( 2460): GC_FOR_ALLOC freed 424K, 13% free 4584K/5268K, paused 17ms, total 18ms
D/dalvikvm( 2460): GC_FOR_ALLOC freed 5K, 13% free 4665K/5356K, paused 16ms, total 18ms
D/dalvikvm( 2460): GC_FOR_ALLOC freed <1K, 13% free 4750K/5444K, paused 18ms, total 18ms
D/dalvikvm( 2460): GC_FOR_ALLOC freed <1K, 13% free 4922K/5620K, paused 17ms, total 18ms
D/dalvikvm( 2460): GC_FOR_ALLOC freed <1K, 13% free 5093K/5796K, paused 16ms, total 16ms
D/dalvikvm( 2460): GC_CONCURRENT freed 412K, 10% free 5441K/6044K, paused 3ms+9ms, total 35ms
D/dalvikvm( 2460): GC_CONCURRENT freed 616K, 12% free 5706K/6460K, paused 4ms+3ms, total 36ms
D/dalvikvm( 2460): GC_CONCURRENT freed 714K, 13% free 5947K/6800K, paused 4ms+3ms, total 40ms
D/dalvikvm( 2460): GC_CONCURRENT freed 898K, 15% free 6076K/7112K, paused 3ms+11ms, total 36ms
D/dalvikvm( 2460): GC_CONCURRENT freed 1007K, 16% free 6149K/7292K, paused 4ms+2ms, total 44ms
D/dalvikvm( 2460): GC_CONCURRENT freed 959K, 16% free 6329K/7472K, paused 4ms+22ms, total 45ms
D/dalvikvm( 2460): Trying to load lib /data/app-lib/ch.opengis.qfield-1/libqfield.so 0x416f69b0
D/        ( 2460): (null):0 ((null)): QML debugging is enabled. Only use this in a safe environment.
D/dalvikvm( 2460): Added shared lib /data/app-lib/ch.opengis.qfield-1/libqfield.so 0x416f69b0
D/dalvikvm( 2460): No JNI_OnLoad found in /data/app-lib/ch.opengis.qfield-1/libqfield.so 0x416f69b0, skipping init
W/EGL_emulation( 2460): eglSurfaceAttrib not implemented
D/QField  ( 2460): ../../QField/src/qgismobileapp.cpp:64 (QgisMobileapp::QgisMobileapp(QgsApplication*, QWindow*)): STORED DOTQGIS2_DIR: QVariant(QString, "/storage/sdcard/Android/data/ch.opengis.qfield/files/.qgis2")
D/QField  ( 2460): ../../QField/src/qgismobileapp.cpp:69 (QgisMobileapp::QgisMobileapp(QgsApplication*, QWindow*)): STORED SHARE_DIR: QVariant(QString, "/storage/sdcard/Android/data/ch.opengis.qfield/files/share")
W/QField  ( 2460): qrc:/qml/qgismobileapp.qml:188 ((null)): qrc:/qml/qgismobileapp.qml:188:5: Type LayerSelector unavailable
W/QField  ( 2460): qrc:/qml/LayerSelector.qml:5 ((null)): qrc:/qml/LayerSelector.qml:5:1: VectorLayer is not a type
F/libc    ( 2460): Fatal signal 11 (SIGSEGV) at 0x00000010 (code=1), thread 2588 (.opengis.qfield)
I/DEBUG   (   35): pid: 2460, tid: 2588, name: UNKNOWN  >>> ch.opengis.qfield <<<
D/Zygote  (   38): Process 2460 terminated by signal (11)
I/ActivityManager(  275): Process ch.opengis.qfield (pid 2460) has died.
```

**Comment by m-kuhn** [comment] 2016-07-19 10:10
Which version of Android are you using?

Possibly a duplicate of #42

**Comment by gyttza** [comment] 2016-07-20 03:31
It's the same when I use Android 4.3/4.4/5.0
and This is the warning I compile.

jdk1.8.0_91 --ant /home/tq/apache-ant-1.8.0/bin/ant
Warning: QML import could not be resolved in any of the import paths: org.qgis
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils

**Comment by m-kuhn** [comment] 2016-07-20 05:16
Ah, so you compile yourself?

**Comment by gyttza** [comment] 2016-07-20 05:52
All of the source code is cloned from here, but a lot of member functions are not defined at compile time. Let me feel the OSGeo4A generated library and QField does not match.

**Comment by m-kuhn** [comment] 2016-07-20 05:55
Better try with the QGIS master_2 branch (you can work with a local QGIS source if you set this option https://github.com/opengisch/OSGeo4A/blob/master/config.conf.default#L17).

But there may even some patches which I haven't integrated upstream. Let me know what exactly is missing in master_2.

**Comment by gyttza** [comment] 2016-07-20 06:46
Thanks. I will try

**Closed** 2016-09-09 09:39 UTC
