### ISSUE TITLE
Performance Issue since 2.5.x

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#4102] opened 2023-03-30 15:18 UTC
### Describe the issue
We have noticed a strong loss of speed since version 2.6.0 our last used QField Version was about 2.2.x we used.
When capturing new object points, the opening of the attribute fields takes up to 10s.

There are many @first_snapped_point used in the attribute form, maybe they are an issue.

Samsung Galaxy Tab Active 2: https://www.gsmarena.com/samsung_galaxy_tab_active_2-8897.php
Creating Point >6s

Samsung Galaxy Tab Active 3: https://www.gsmarena.com/samsung_galaxy_tab_active3-10476.php
Creating Point ~2s

Maybe we just need a little hint where to search on or where the trouble is originated.

### Reproduction steps
1. Creating Point

### Expected behavior
to be faster

### Observed behavior
slow

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active 2; Samsung Galaxy Tab Active 3
 - OS: Android 9 / Android 12
 - QField version: 2.6.3 - Geeky Gecko (aa9ed)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment] 2023-03-31 06:57
@EulenspiegelTill , have you tried with latest 2.7.2?

**Comment by EulenspiegelTill** [comment] 2023-04-05 06:23
Yes, also tested with the actual version. The thing is, it was quite handy to use before and came much, much slower by the actual verisons.

In the attribute form expr. like the one below are used ~26x:

```
with_variable(
  'first_snapped_point',
  array_first( @snapping_results ),
  attribute(
    get_feature_by_id(
      map_get( @first_snapped_point, 'layer' ),
      map_get( @first_snapped_point, 'feature_id' )
    ),
    'id_messtelle_art'
  )
)
```

**Comment by nirvn** [comment] 2023-04-05 06:47
@EulenspiegelTill , ok. Two things would help moving this forward:
1/ provide a test case to replicate slowness
2/ go to the GitHub releases page and identify which extract version regressed

**Comment by nirvn** [comment] 2023-04-05 07:35
@EulenspiegelTill , just to double check I understand you well: 1.9.5 was fine and 1.9.6 became slow to you?

**Comment by EulenspiegelTill** [comment] 2023-04-05 07:40
@nirvn good double check. No, we were rolling on 1.9.6 and postponed the updating on an actual version, because everything was fine 😉 . Have done the update two weeks ago and was facing the speed issue on 2.6.0.

**Comment by nirvn** [comment] 2023-04-05 07:55
@EulenspiegelTill , was 2.5.7 fine?

**Comment by nirvn** [comment] 2023-04-05 13:13
@EulenspiegelTill , ok, I'll look into profiling this in the coming days. In the meantime, since slowness is partially subjective ( 😃 ), what would help a lot is for you to work your way back to 1.9.6 one release at a time and identify which point release caused the perceived slowdown.

Ive tested your project over here on my pixel 6a and while I do see a 2-3 seconds is required to open the attribute form, it doesn't appear to be slower than when I tried the project on QGIS itself with my beefy workstation. 

Btw, your project looks fantastic, great to see QField unlocking that kind of really advanced data entry.

**Comment by EulenspiegelTill** [comment] 2023-04-05 14:16
@nirvn did a little rollback, sadly startet at the bottom than at the top.. 
2.4.0 was running smooth. 2.5.7 was the first running version of the 2.5.x and there the editing becames slow. see the vids attached. When i use a newer tablet for sure it is a bit faster, but still not responsive enough for working productive.

https://kdrive.messtechnik.ch/app/share/121947/f272f616-0b89-4019-99cd-f0eaf1215438

**Comment by EulenspiegelTill** [comment] 2023-04-05 14:20
@nirvn there it was always crashing when editing new points.. 2.5.7 was the first working on my tablet.

**Comment by nirvn** [comment] 2023-04-05 14:24
@EulenspiegelTill , alright. You've been super helpful in gathering information. I'll keep you posted on findings.

**Comment by nirvn** [comment] 2023-04-06 03:09
@EulenspiegelTill , can you give these APKs a try: https://github.com/opengisch/QField/pull/4123#issuecomment-1498417757 -- thanks.

**Comment by EulenspiegelTill** [comment] 2023-04-06 05:57
@nirvn, no changes in case of sloowww..

**Comment by nirvn** [comment] 2023-04-06 07:54
@EulenspiegelTill , can you try new APKs here: https://github.com/opengisch/QField/pull/4123#issuecomment-1498417757 (it's not a solution per say but I would like to see whether we can rule out one specific change in 2.5).

**Comment by EulenspiegelTill** [comment] 2023-04-06 08:09
@nirvn bit less slow but still not comparable with 2.4 see the vids link on top, put the vids of 2 apk version in there.

**Comment by EulenspiegelTill** [comment] 2023-04-06 09:37
@nirvn nope.. vid attached in the link on top, still slow. i will be off till Tuesday from now, can test the next apke then..  happy 🐰 🥚

**Comment by nirvn** [comment] 2023-04-06 10:15
@EulenspiegelTill , if by any luck you are still around, one last pre-easter set of APKs to test: https://github.com/opengisch/QField/pull/4123#issuecomment-1498417757

**Comment by nirvn** [comment] 2023-04-06 12:37
@EulenspiegelTill , also, thinking outloud here, in QField 2.4, is it possible that you do see a freeze, but it only occur once (e.g. when you toggle digitzing mode on and/or switch active layer)?

**Comment by soester** [comment] 2023-04-09 11:45
@nirvn @EulenspiegelTill 
due to covid i had time to test over :egg: :rabbit: 

in https://github.com/opengisch/QField/pull/4126 and https://github.com/opengisch/QField/pull/4131 i noticed a freeze/lag when i tried to enter a value in a field after the form has been opened. ->> After this freeze all values populated by @snapping_results defauts are wiped out of the form :boom: 

in https://github.com/opengisch/QField/pull/4131 opening the attribute form after snapping is muuuuch faster on my fairphone3 than on the current release.

i can also confirm the freeze while toggling the digitzing mode.

**Comment by nirvn** [comment] 2023-04-09 12:12
@soester , thanks for testing, let's try to focus on perceived speed issue (ie there might be something else going on with the snapping result variable).

When you say that you can confirm the freezer when toggling the digitizing mode, you meant with 2.4 or with the test builds?

Is 4131 overall an improvement?

**Comment by soester** [comment] 2023-04-09 12:40
@nirvn didn't test with 2.4 
just tried to reproduce the freeze with the test builds (4131 and 4126) and was not able to. anyway this is not a big probelm.

4131 is defenitly an improvement speed-wise!
wiping the whole form is a bit scary, but im sure you'll be able to fix that :-)

**Comment by nirvn** [comment] 2023-04-09 12:51
@soester , the wiping of the whole form is replicable with the test project attached above? Is it an issue with 2.7.2?

**Comment by nirvn** [comment] 2023-04-09 13:19
@soester , alright, as suspected, this was a separate problem, which also affects released QField versions. Let's move the discussion on this within the PR which I hope fixes the issue here: https://github.com/opengisch/QField/pull/4138 -- you'll have some APKs to test within 10 minutes or so.

**Comment by soester** [comment] 2023-04-09 14:43
Yeah @nirvn you were right, that seems to bee another big issue in current releases. i first had to check the project versions. i was not using the exact same project @EulenspiegelTill shared with you. 
unfortunately the wiping attribute form issue persists in https://github.com/opengisch/QField/pull/4138. also the performance gain is not as obvious as i saw it yesterday.
i will try to find out which version it was that was faster.

**Comment by soester** [comment] 2023-04-09 14:56
https://github.com/opengisch/QField/pull/4123 is a bit faster. 
https://github.com/opengisch/QField/pull/4131 is much faster.

**Comment by nirvn** [comment] 2023-04-09 15:13
@soester , #4138 has no performance gains, just working on this wiping situation. Can you provide a test project in that PR for me to test? I was seeing it fixed on the project @EulenspiegelTill had shared

**Comment by soester** [comment] 2023-04-09 15:22
@nirvn sorry for the confusion. i think i messed up the (many) qfield versions.
i can confirm the fix. 
from now on i will test with the project from @EulenspiegelTill !

**Comment by nirvn** [comment] 2023-04-09 15:26
@soester , thanks for all the testing.

**Comment by nirvn** [comment] 2023-04-12 11:29
@EulenspiegelTill , it would be great if you could test the APKs in #4123 and #4131 and report back your experience with both builds. I think #4131 might be bring back QField performance close to what 2.4 was.

**Comment by EulenspiegelTill** [comment] 2023-04-12 12:34
@nirvn #4131 is fast as.. it is at the performance of 2.4 with the "old" tablet, would be nice to work like this again! 👍 

![image](https://user-images.githubusercontent.com/23494522/231458503-098b0a9d-083b-49b0-88e0-45195c0d2ef3.png)

**Comment by soester** [comment] 2023-04-12 15:15
@nirvn we further tested https://github.com/opengisch/QField/pull/4131 and there is some strange behaviour in our forms:
- most dropdowns (value relation) in the form do not work
- also some numeric values cannot be enterd
- fields referenced twice in multiple tabs work in one tab but not the other
- it highly depends on the map theme in use wich fields work and wich don't

@EulenspiegelTill just tested one field (messtechniker in tab kampagne), this works so we didn't discover the rest.

**Comment by nirvn** [comment] 2023-04-12 15:17
@soester , let's deal with these as separate issues. Feel free to open PRs on specific issues you spot with replicable steps.

**Comment by nirvn** [comment] 2023-04-14 09:31
Fixed

**Closed by nirvn** 2023-04-14 09:31 UTC
