### ISSUE TITLE
Possible bug - Changes lost after a specific manipulation

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#5215] opened 2024-04-26 21:02 UTC
Hi,

The information written in the fields is lost when we tap on the name of the feature. 

On the video right after, you can see changes on the feature are not saved when I tap on the name "Monitoring (03-Flora)...".

https://github.com/opengisch/QField/assets/72577399/7e395d42-902e-42c7-9c3f-3deb19550f23

Do you think it is a bug ? 
In any case, this can bring to data loss. 

Desktop
OS: [Windows 10]
QGIS Version [3.36.1]
QFieldSync Version [4.9.1]

Mobile
Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (14a0be)]

Additional information

Problem started happening recently, didn't happen in an older version of QField: [Yes] (Qfield 3.2.2 - Congo)
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment] 2024-04-27 15:50
Can you provide a minimal example with as little layers and attributes as possible to reproduce this behavior?

**Comment by Ipickedausername** [comment] 2024-04-29 14:55
Hi, 
Sorry, I was on the field when I prepared this post and I didn't give much information. 
I've made some tests on a project. 
Here is the test project:
[Test_project_QFIELD.zip](https://github.com/opengisch/QField/files/15150866/Test_project_QFIELD.zip)

To reproduce the error: 
> Disable "Maximized attribute form"
> Open the only existing feature in the layer "test_layer"
> Update one of the available fields (except "id"). 
> Tap on the name of the feature, or slide down (with the finger on the name of the feature, in order to save changes). 

>> You'll see the error message, saying "Unable to save changes"

**Comment by SeqLaz** [comment] 2024-04-30 08:17
Hi @Ipickedausername ,

I did some test and I was not able to reproduce the issue,

[Test Possible bug - Changes lost after a specific manipulation 002.pdf](https://github.com/opengisch/QField/files/15160381/Test.Possible.bug.-.Changes.lost.after.a.specific.manipulation.002.pdf)

**Comment by Ipickedausername** [comment] 2024-04-30 09:11
Hi, 

Here another video with the complete process. 

You can see that:
1] with maximized attribute form, change is saved
2] with disabled maximized attribute form, the same change is not saved. 

https://github.com/opengisch/QField/assets/72577399/4bc1fa92-7484-4f78-ba4e-ffecf0d08894

**Comment by SeqLaz** [comment] 2024-04-30 10:47
Hi @Ipickedausername ,

Apologize but still can't reproduce it

https://github.com/opengisch/QField/assets/77129293/56a06c42-a9ea-478e-a06c-eb2002bc0363

**Comment by Ipickedausername** [comment] 2024-04-30 16:18
This issue happens on the master-dev version and on the official Qfield version. 
Are you trying on a phone ? Dunno if it can make a difference. 

I tried to change several options, the app kept behaving the same. 
I'll try on another phone when I have time.

**Comment by SeqLaz** [comment] 2024-04-30 21:27
> This issue happens on the master-dev version and on the official Qfield version. Are you trying on a phone ? Dunno if it can make a difference.
> 
> I tried to change several options, the app kept behaving the same. I'll try on another phone when I have time.

@Ipickedausername Both tests were conducted using the QField v3.2.2 official release, with the first one on Linux and the last one on Android 11.

**Comment by Meykaefer** [comment] 2024-05-06 16:59
I was able to reproduce the issue with the test-project provided - see video below:

https://github.com/opengisch/QField/assets/117784621/2236bccd-c898-4984-99a3-c639cfabb772


I think what is happening is that when I use a slide down motion to save the changes it displays the the error message "Unable to save changes", but it still saved the changes for me. If I only tapped the name and closed the form I wouldn't see the error message. So based on my observations it displays the error message when saving/closing the feature form with a slide down, but it still saved the changes to the feature.

Not sure if that helps.


    Device: [IPad 9th gen]
    OS: [OS 17.2]
    QField version: 3.2.2 (72be17 v3.2.2)]

**Comment by Ipickedausername** [comment] 2024-05-06 17:39
Thank you for testing. 
In my case, it doesn't save. This is curious 🤔

**Comment by SeqLaz** [comment] 2024-06-15 20:45
@Ipickedausername could you test again using the latest release https://github.com/opengisch/QField/releases/tag/v3.3.1 ?

**Comment by Ipickedausername** [comment] 2024-06-16 04:54
Hi !
Just tried with the latest release of Qfield as requested. 
It seems that I cannot reproduce this error anymore. 

I guess I can close this discussion.
Thanks !

**Closed** 2024-06-16 04:55 UTC
