### ISSUE TITLE
Cannot digitize point with GPS location into a spatialite database

### ISSUE THREAD

**Issue by tveinot** [opengisch/QField#146] opened 2017-08-03 13:07 UTC
When the snap to GPS location is active QField will not digitize a point.

### Reproduction Steps:

1. Enable Digitization Mode
2. Tap the Snap Crosshiars to GPS Point 
3. Tap the Edit/New Feature Pencil Icon
4. Input data into fields
5. Tap Save Disk Icon
6. No point is created at location.

Work Around
1. Enable Digitization
2. Tap the GPS Active Icon to centre screen on GPS Location
3. Repeat Steps 3-5 from above
4. A new point will be created at your location.
NOTE: This only works if your location is outside the snapping tolerance of other features on map. Only an issue if you are using snapping.

### Expected behavior:

A point to be created at my GPS Coordinate

### Observed behavior:

No Point is created at my location

**QField version:** 2.09, 2.10, and 2.11

## Additional information:
Samsung Galaxy Tab E 9 inch Android 6.0.1
Kernel 3.10.49-11590139
Build Number MMB29M.T560NUUEU1BQF1

**Comment by tveinot** [comment] 2017-08-29 12:02
To add to this issue it is only an issue when using a spatialite database; snapping to location and digitizing to a shapefile works great. I am currently exporting all my editing layers to shape and holding my base data in spatialite.

**Comment by m-kuhn** [comment] 2017-08-29 12:38
could this be a crs issue

**Comment by tveinot** [comment] 2017-08-29 13:14
It could be; its not like it hasn't happened but I will say I am confident it isn't but I will check when I get the chance.

**Comment by tveinot** [comment] 2017-08-29 18:35
Matthias;
I just tried it again on a spatiallite database and I can only place points I drop with the cross hairs and not with the snap to my location feature. I will also note that I tried this in my office where I had an accuracy of 29m and a very jumpy GPS dot; however, it was the same conditions when I tried it on a shapefile and it worked with the snapping to my location on. Both porojects are 2954 NAD83 CSRS PEI Stereographic Projection and all the layers are in this CRS as well.
Tyler

**Comment by tveinot** [comment] 2017-08-29 18:42
Matthias;
I posted on the git forum about this issue but I have a question about
another behavior.
When I build forms in QGIS for data entry in QField they work rather well,
lately I tried something a little more complex with using taps that have an
expression to control their viability. I have several forms all built into
tabs, each tab is for a specific feature type, the first question is "What
Feature is this?" when you answer, lets say garbage can, the garbage can
tab appears and you fill out information specific to garbage cans. One of
these tabs drops some of the fields some times and I was wondering if this
is a known behavior or if I am trying to do something unsupported in qfield
at this time? I didn't want to start an issue report if it was something
known or unsupported.
Let me know if you think I should post this up on the git forum.
Tyler

**Comment by m-kuhn** [comment] 2017-08-30 06:58
It doesn't ring a bell just like that.
Better open a new issue report so we have things well separated and discussions focused.
If it turns out it wasn't worth it, we can close it quick enough ;)

**Comment by m-kuhn** [comment] 2017-08-30 07:00
> I just tried it again on a spatiallite database and I can only place points I drop with the cross hairs and not with the snap to my location feature. I will also note that I tried this in my office where I had an accuracy of 29m and a very jumpy GPS dot; however, it was the same conditions when I tried it on a shapefile and it worked with the snapping to my location on. Both porojects are 2954 NAD83 CSRS PEI Stereographic Projection and all the layers are in this CRS as well.

Something else that might have an effect here: when the crosshair is snapped to the GPS location it works in 3D. Possibly a 2D SpatiaLite layer drops 3D coordinates altogether...

**Comment by tveinot** [comment] 2017-08-30 10:40
Matthias;
Will do.
Thanks;
Tyler

**Comment by etiennethomassen** [comment] 2017-09-14 12:06
I can confirm the behaviour that I cannot digitize a point when using 'centre on GPS location' in a spatiallite db (made by the QField Plugin), but can do it in a shapefile (ESPG 28992). I also tried making a 3D SpatialLite layer, but that did not work either (perhaps wrong CRS?).

**Comment by soester** [comment] 2017-10-06 14:28
I can also confirm this behaviour. My setup:
Postgres Table with POINTZ geometry -> QField Sync -> Spatialite

The sqlite file generated by the plugin has no z-geometry. 
When digitizing on Qfield with GPS, the row and values are inserted to the table, but geometry is dropped because of Z. Elements digitized by hand (no gps location) have no z and are stored with geometry.

Would be great if there is a solution to either generate a sqlite-file with z (preferable) or to accept geometry with z even it is only 2D in Qfield.

**Comment by zakigates** [comment] 2017-10-16 17:26
I have the same issue when digitizing with the gps tool, no point is added in spite of the information about the Z in being inserted on the field but when you use it without gps center there is no Z.

**Closed** 2018-03-17 08:45 UTC
