### ISSUE TITLE
Text entry only in capital letters

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#289] opened 2018-06-06 13:14 UTC
Since at least QField 0.10.12 (also 0.10.13) but not 0.10.9 QField has a problem when entering text. It always turns on the capital function and all text is entered in capital letters. The button to write in small letters can be pushed and one letter be entered correctly. But he following letter will be entered as capital again. This behaviour seems device or android version specific. We can only reproduce it on Samsung Galaxy Tab Active 2 (model number SM-T395, android version 7.1.1) but not on with model number Galaxy Tab Active (SM-T365, android version 5.1.1)

Can anyone reproduce this with other devices/Android versions? Do the developers see a possiblity to solve this?

**Comment by VxTedxV** [comment] 2018-06-06 20:37
+1
on Samsung Galaxy XCover4 - Android 7.0

**Comment by ferenc-attila** [comment] 2018-06-08 22:14
±1
on Galaxy Tab S2, Android 7.0
Only with factory keyboard. Works well with Google keyboard (gboard).

**Comment by saemiw** [comment] 2018-06-11 11:56
There is a workaround for the problem (in German): In the settings under "Samsung Tastatur" -> "Intelligentes Tippen" -> desactivate "Automatische Grossschreibung"

**Comment by fahrwegdienste** [comment] 2018-06-13 09:57
This issue can be reproduced with 
- Samsung Galaxy Tab Active 
- Samsung Galaxy Tab Active 2, 
using QField 0.10.13, Android 7.

**Comment by gnerred** [comment] 2018-08-29 08:18
Is it planned to fix this bug ? Thanks

**Comment by Emic37** [comment] 2018-09-19 09:30
+ 1 
I encount same issue with default samsung keyboard on Samsung Galaxy S7. But no issue if I use Gboard keyboard.
However, when I use Gboard keyboard (my default keyboard), automatic correction seems not work.

**Comment by m-kuhn** [comment] 2018-10-05 08:28
Looks like there's a fixed version of Qt available. Fingers crossed.

https://bugreports.qt.io/browse/QTBUG-69398

**Comment by m-kuhn** [comment] 2018-10-05 08:35
This will only be shipped with Qt 5.11.3. If the rhythm between 5.11.2 and 5.11.3 is also 3 months like between 5.11.1 and 5.11.2, this should be available before January.
This can be tested before, but building Qt ourselves will need some extra effort.

**Comment by 3nids** [comment] 2018-10-05 11:42
5.12 is out on 29.11.2018 anyway.

**Comment by m-kuhn** [comment] 2018-12-11 14:22
#405 should solve this. Unfortunately I am not able to reproduce the issue, can someone download the apk [here](https://github.com/opengisch/QField/pull/405#issuecomment-446215764) and check? Thank you

**Comment by saemiw** [comment] 2018-12-11 15:18
Yes I can confirm that the problem disappears with the apk of #405 

But (spoiler) instead I have problems saving a second feature. I can enter and save my first feature (a polygon in a geopackage) perfectly. When trying to enter a second feature I miss the buttons to finish the entering process. See printscreen below. If I close and re-open QField I am able to again enter 1 feature.
![screenshot_20181211-161253_qfield](https://user-images.githubusercontent.com/20398621/49809805-1ffa8680-fd60-11e8-8209-a52888080116.jpg)

**Comment by m-kuhn** [comment] 2018-12-11 15:37
Thanks for the feedback and ouch for the issue.

Can you verify with the apk in #404 too, to see if the issue was introduced by this pull request or another one?

**Comment by saemiw** [comment] 2018-12-11 16:19
The issue described with the printscreen above also appears with the apk in #404

**Comment by m-kuhn** [comment] 2018-12-11 16:52
Thanks a lot for the feedback and testing @saemiw 
The capitalization problem is in master and will be fixed with the next release.

I have opened a new separate issue https://github.com/opengisch/QField/issues/407
If you have more information regarding that please post there.

**Closed by m-kuhn** 2018-12-11 16:52 UTC
Labels: bug

**Comment by 3nids** [comment] 2018-12-13 13:37
@saemiw this is fixed by https://github.com/opengisch/QField/pull/412
