### ISSUE TITLE
QGIS / QFIELD : Value by default doesn't work

### ISSUE THREAD

**Issue by LeelooSIG** [opengisch/QField#1068] opened 2020-06-18 18:22 UTC
Hello, 

I did an QField application for forest inventory. Each point is a tree. In my form, I would like the new circumference (Variable2) has (by default) the old circumference (variable1).
I do it, but when i try with the form the new circumference = NULL (and not the value of the old circumference).

Any chance to help me ?
Thanks

**Comment by m-kuhn** [comment] 2020-06-19 14:51
This looks like a duplicate of what has been reported here: https://github.com/opengisch/QField/issues/977

Please get in touch with @ARBkey who is actively looking for crowdfunding partners

**Comment by m-kuhn** [comment] 2020-07-03 16:37
Closing as duplicate of #977

**Closed by m-kuhn** 2020-07-03 16:37 UTC
