### ISSUE TITLE
Can't copy QField folders from android device to PC via Cable Connection

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/QField#3799] opened 2023-01-09 15:29 UTC
### Describe the issue
Can't copy QField folders from android device to PC via Cable Connection

### Reproduction steps
1. Create a QField Project that includes capturew of 1:n photos
2. Load the project onto the Android Device via cable connection (..\Internal storage\Android\data\ch.opengis.qfield\files\Imported Projects)
3. Add some features with photographs. Close QField.
4. Attempt to copy QField folder from ..\Internal storage\Android\data\ch.opengis.qfield\files\Imported Projects to your PC via Cable Connection. Error occurs.

### Expected behavior
No error. Folder and DCIM folder copy across.

### Observed behavior
After surveying, in cases where there are photos in the DCIM subfolder, I am unable to copy the QField folder from the Android Device to PC (Win10) over a cable connection. The Main QF folder copies across, the DCIM folder and its contents do not. I receive an error message in Windows: "Unspecified error". 

As a workaround, I can export the folder from the QField app to a desired location.

### Desktop (please complete the following information)
 - OS: WIn 10
 - QGIS Version 3.22.11
 

### Mobile (please complete the following information)
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - QField version: - QField 2.5.7 (CFan't give build no., as it auto-updated to 2.6)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes - as far as I can tell on my device]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment] 2023-01-10 18:11
Did you try to restart the device?
And could you possibly try to create all folders beforehand manually?
It's a pity Android has become so restrictive ...

**Comment by Oisin-JK** [comment] 2023-01-10 19:54
Yes, I've tried restarting, and manually creating folders. It seems to be photos causing the issue, and I saw a reference to it being file size. I assume this is an Android issue? If intended it seems an odd restriction.

**Comment by nirvn** [comment] 2023-01-21 08:20
Closing as duplicate of  #3736.

**Closed by nirvn** 2023-01-21 08:20 UTC
