### ISSUE TITLE
QField 1.0.0-rc1 not working with Samsung galaxy S4

### ISSUE THREAD

**Issue by anotheruserhere** [opengisch/QField#461] opened 2019-01-30 14:14 UTC
QField 1.0.0-rc1 on Samsung Galaxy S4 (running Android 4.4.2) doesn't work for me.

When I open QField the app crash straight away.

I have uninstalled QField 1.0.0-rc1, installed Lucendro (0.11.11) instead and everything works fine.

**Comment by giedrioks26** [comment] 2019-01-30 14:22
same with QField 1.0.0-rc2 on Blackview BW9000 pro (android 8.0). Crash when opening.

**Comment by m-kuhn** [comment] 2019-01-30 15:16
@giedrioks26 does https://download.opengis.ch/qfield/ci-builds/qfield-dev--234e69e3f76473de32c03507338419be878df3d6-armv7.apk work for you?

**Comment by m-kuhn** [comment] 2019-01-30 15:23
@anotheruserhere that's probably a duplicate of https://github.com/opengisch/QField/issues/434

**Closed by m-kuhn** 2019-01-30 15:23 UTC

**Comment by anotheruserhere** [comment] 2019-01-30 15:27
@m-kuhn yes more than likely.

**Comment by mbernasocchi** [comment] 2019-01-30 16:19
@giedrioks26 we just pushed RC3 to the playstore beta channel, can you try? cheers

**Comment by giedrioks26** [comment] 2019-01-30 18:32
@m-kuhn yes, it work :)
@mbernasocchi in playstore I see only rc1 (although recently it was rc2). From here https://github.com/opengisch/QField/releases/download/v1.0.0-rc3/qfield-v1.0.0-rc3-armv7.apk work fine

**Comment by giedrioks26** [comment] 2019-02-04 13:37
@mbernasocchi I get rc3 version from playstore. Works fine. No crashed at startup.  I don't know how to work with andrioid 4.4. We are no longer using it. No chance to try.

**Comment by mbernasocchi** [comment] 2019-02-04 14:09
Ok thanks. Maybe somebody else stumbles to this issue and will report :)
