### ISSUE TITLE
Editing failed after deleting a feature

### ISSUE THREAD

**Issue by JuliusNagel** [opengisch/QField#1228] opened 2020-08-18 15:27 UTC
Hello everybody,
since i updated QField to 1.6.2 on my RugGear RG910 with Android 8.0 the editing of the layers in my Project failed after i delete a feature. If i only add features without deleting a feature everything work well. When i use the DemoProject simle Bee Farming and the Layer Field i have the same Problems
I worked with QGis 3.10.7 and QFieldSync 3.2.1.
On my Smartphone with QField 1.5.3 and the same Project and Files everything work fine

### Reproduction Steps:

1. Chose digitizing mode an the Layer 
2. Add Geometrys and Features - Message: "Changes saved"
3. Delete a Polygon - Message: "Succesfully delete feature"
4. Message in the Log -> Screeenshot
5. Try to add some new geometrys. Message: "Unable to save changes"
6. Try to delete features. Message: "Unable to delete feature"

Screenshots and GIFs
![grafik](https://user-images.githubusercontent.com/69513244/90532024-076a8280-e177-11ea-953d-21f5c372add7.png)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment] 2020-08-18 17:57
This looks like a duplicate of https://github.com/opengisch/QField/issues/1189

Could you have a look and check the requested test in there?

**Comment by chakasasacha** [comment] 2020-08-19 06:10
Hi ! I have exactly the same problem since yesterday morning ! Had an update and after it happened the thing you told. Really annoying... Did you find a solution ? :)

**Comment by JuliusNagel** [comment] 2020-08-19 06:49
I try the new build from the issue #1189 and it works well. With this Version its possible to delete Features and add new in one session without any bugs
I think i will downgrade to 1.5.3 and wait for the release of 1.7

**Comment by nirvn** [comment] 2020-08-19 06:51
@chakasasacha , give this PR a try when APKs pop up (in a few minutes): https://github.com/opengisch/QField/pull/1235

**Comment by chakasasacha** [comment] 2020-08-19 07:24
@nirvn 
It's running well !!! THANKS A LOT ! have a nice day :)

**Comment by JuliusNagel** [comment] 2020-08-19 13:10
Thanks for the Support !!

**Closed** 2020-08-19 13:10 UTC
