### ISSUE TITLE
Expand photos within QField

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#2096] opened 2021-08-20 05:49 UTC
When a photo is recorded in QField, we see a thumbnail. To expand it fullview, it goes to another app.
 
### Reproduction Steps:

1. Configure a project to be able to insert photo in attribute
2. Take a photo in QField and validate
3. The photo is recorded and the thumbnail is shown
4. Tap on the thumbnail to enlarge the photo

### Expected behavior:

At step 4, no external app should be asked to open the photo and it should be enlarged fullscreen within QField

### Observed behavior:

At step 4, a list of available apps is proposed like the default app to view photos taken by the device. If choosen it goes out of QField (not ergonomic). If QField is selected from the list, it opens a blank screen with a QField top grey bar (with logo & app name) and no go back allowed.

**QField version:**  1.9.6 (d5dd01)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by suricactus** [comment] 2021-08-20 17:20
Duplicate of https://github.com/opengisch/QField/issues/386 , this one is better described.

**Closed** 2021-08-20 17:24 UTC
Labels: ENHANCEMENT
