### ISSUE TITLE
[Qfield 2.4+] Photos with expression no longer appear in the PDF generated by the atlas

### ISSUE THREAD

**Issue by zzzef** [opengisch/QField#3660] opened 2022-11-18 16:10 UTC
Hello, 

There were atlas changes in Qfield 2.4. Since 2.4, I've got photos with expression for the path in the layout, and they no longer appear in the PDF generated by the atlas. PDF generated with atlas in QGIS 3.22 are OK and they were OK with Qfield 2.3. 

I have to explain that my expression has warnings at the project's openning in QGIS and QField (Picture expression eval error). Perhaps this expression could be enhanced, but there is a regress since 2.4. PDF were OK with Qfield 2.3. 

```python
try(array_get(string_to_array(   array_to_string( array_filter( string_to_array(relation_aggregate(relation:='fk_graepa_vs_anc__v_otdcman_tc_th_last_open_visaancterrain', aggregate := 'concatenate', expression := "th_type" || ';:;:;' || "th_photo1", 
concatenator := ',:,:,' ),',:,:,'), @element LIKE 'VisaAncTerrain%')),';:;:;'),1))
```
### Desktop
 - OS: Windows
 - QGIS Version 3.22

### Mobile
 - Device: muttiple devices
 - OS: Android 10, 11, 12
 - QField version: 2.4 / 2.5

**Comment by nirvn** [comment] 2022-11-19 02:53
@zzzef , try exporting your atlas in QGIS 3.28 to see if it works first. If it doesn't work, it's likely an issue with your project. If it does work, feel free to attach a sample project here.

**Comment by aliasatp** [comment] 2022-11-22 11:09
Hi, for me the same issue. QGIS 3.28, Qfield 2.5. In Qfield atlas I haven't expression even if in QGIS atlas print I have

**Comment by nirvn** [comment] 2022-11-22 11:23
@aliasatp , feel free to attach a sample project here.

**Comment by zzzef** [comment] 2022-11-23 13:09
Oops 

[3660.zip](https://github.com/opengisch/QField/files/10075749/3660.zip)

**Comment by aliasatp** [comment] 2022-11-23 18:06
Ok, my problem was due a text box formatted as "html", in that case expressions weren't displayed in pdf print. In a simple text box they appear

**Comment by nirvn** [comment] 2022-11-26 07:42
@aliasatp , HTML label items are not supported on Android and iOS. It's a limitation of Qt itself. Glad  you find a work around.

**Comment by nirvn** [comment] 2022-11-26 07:45
@zzzef , your expression needs to result in an absolute path to your photos. To make it portable, simply use the @project_home variable. E.g.:

`@project_home ||'/'||relation_aggregate( 'fk_saisie__ctrl', 'concatenate', "photo1", ',:,:,' )`

(Closing as not a bug with QField, the project also fails with QGIS 3.28; solution above :) )

**Closed by nirvn** 2022-11-26 07:45 UTC
