### ISSUE TITLE
Plus/minus buttons for numeric fields

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#1687] opened 2021-02-13 03:14 UTC
UI suggestion: plus/minus buttons for increasing/decreasing values in numeric widgets by the step specified in the widget settings.

Currently in QField it's just a simple text edit widget. It would be great to have the option of being able to bump numbers up or down especially in conjunction with the "remember last value" checkbox. For example, when assessing a row of trees of similar height, it would be more convenient and less error-prone to be able to go 11, 12, 10, 11, 10 with a simple press of the button, rather than having to click the field, and manually edit the value with a popup keyboard.

As an example Input has this feature with numeric fields (see below). 

![Screenshot_20210213-141134](https://user-images.githubusercontent.com/41975056/107840290-a100ad00-6e05-11eb-8db7-ff61e3996000.png)

**Comment by signedav** [comment] 2021-02-15 07:39
Thanks for the input. 

Do you know about the slider widget btw.?
![WhatsApp Image 2021-02-15 at 08 37 48](https://user-images.githubusercontent.com/28384354/107918100-5730d780-6f69-11eb-9ff1-a89eca849181.jpeg)

**Comment by she-weeds** [comment] 2021-02-21 21:52
> Thanks for the input.
> 
> Do you know about the slider widget btw.?
> ![WhatsApp Image 2021-02-15 at 08 37 48](https://user-images.githubusercontent.com/28384354/107918100-5730d780-6f69-11eb-9ff1-a89eca849181.jpeg)
> 
> Edit: But I agree that for your use case a +/- seems to be better than a slider...

Thanks for adding it as an enhancement. Yeah I am aware of the slider but on smaller screens we find it really hard to use as the default range of values for that field can be anywhere from 3 to 200 in just one project. It's best to have the combined ability to type and use +/- in one widget.

Looking forward to the buttons - thanks again for all the awesome progression with the app.

**Comment by nirvn** [comment] 2021-03-08 08:14
Closing as it is a duplicate of #1399 .

**Closed by nirvn** 2021-03-08 08:14 UTC
Labels: ENHANCEMENT
