### ISSUE TITLE
Feature request: make option to disable double tap to exit app

### ISSUE THREAD

**Issue by blacktesta** [opengisch/QField#4784] opened 2023-11-19 07:05 UTC
Hi, developers of the best mobile app!
I observed some problems using back button.

The bug: Select feature on the map. Feature list will open. Try to come back to the map with back button tap. You'l get a message: "tap again to close app".

For me exiting app with double tap is useless even unwanted, but coming back to previous menu/map is very usefull. Instead I'd prefer menu item "Close app" in the "gear" menu.

I'm interested if nobody experiencing difficulties with the back button like me?

My device: Samsung m21, Android 12, Qfield 3.0.6 d36352

**Comment by Ipickedausername** [comment] 2023-11-19 14:01
I do, almost every time I use the app 🥺

**Comment by blacktesta** [comment] 2023-11-19 14:55
@Ipickedausername just saw your issue, I think my can be closed

**Comment by suricactus** [comment] 2023-11-19 23:32
Duplicate of https://github.com/opengisch/QField/issues/3451 .

I think we have provided even better solution in #4772 by using the lock screen functionality.

**Closed by suricactus** 2023-11-19 23:32 UTC
Labels: ENHANCEMENT

**Comment by blacktesta** [comment] 2023-11-19 23:53
@suricactus Just to clarify. Proposed solution doesn't help in my situation. I want to use the app (i cant do it with locked screen) and don't want to leave the app with back button. For me its hard to understand who actually wants to quit the app from feature form or feature list.

**Comment by Ipickedausername** [comment] 2023-11-20 01:29
Same for me. It makes sense to use the double back button to leave the app, as every other app is doing the same. 
But, in this specific situation, I think the double tap could be optional. 

Maybe this is related to how we use the app. I'm right-handed, and I use my right hand to navigate in the app. 
So the application back button is always located at the opposite of my hand (top left corner). It is, then, easier to use the back button, which is always nearer (and always visible / the same ; not replaced by navigation arrows). 

Also, there are situations where you can go back with the "back button" (for example: when you add a feature, before validating, you can go back by pressing the back button (which will weirdly add the feature)), but there are other situations where this button will only be used to leave the app.

**Comment by nirvn** [comment] 2023-11-20 03:05
@blacktesta , @Ipickedausername , this PR should improve things for you (hopefully): https://github.com/opengisch/QField/pull/4787 -- the back button will now close the feature form (or cancel editing) instead of asking to close the app. It doesn't deal with the enhancement request of disabling it altogether but it fixes the expected UX of having back close things before reaching a point where it asks to exit.

**Comment by blacktesta** [comment] 2023-11-20 05:39
Thank you, @nirvn, for your work ! That's awesome! Works fine.
Another little typo spotted when i was working on transifex. File filter string for images contains wrong extension for PNG and some of translators fix it for their languages. The string: 
All images (*.jpg *.jpeg *.png *.bmp);;JPEG images (*.jpg *.jpeg);;PNG images (*.jpg *.jpeg);;BMP images (*.bmp)
Telling you here, because i think it is too small for opening issue.
