### ISSUE TITLE
Your application encountered a fatal error and cannot continue

### ISSUE THREAD

**Issue by taff224** [opengisch/QField#194] opened 2017-11-18 19:11 UTC
Hi,

I installed the app from google play, installed fine, did the unpackaging of post installation files fine but then gives me this error when I try and run it.

I have atatched an adb log - it's long and not sure which bits are important.

Thanks

Chris
[adb log - qfield Nov 2017.docx](https://github.com/opengisch/QField/files/1484937/adb.log.-.qfield.Nov.2017.docx)

**Comment by taff224** [comment] 2017-11-26 14:37
Anyone any ideas?

**Comment by ypro0** [comment] 2018-01-15 14:17
Hi,

I installed the app from google play, installed fine, did the unpackaging of post installation files fine but then gives me this error when I try and run it.

I have atatched an adb log - it's long and not sure which bits are important.

Thanks

Chris

**Comment by ypro0** [comment] 2018-01-15 14:18
Hello, I'm installing qfield. Android 6 Marshmallow. The files are decompressing up to 92% then "Your application has encountered a fatal error and can not continue".
This is the same thing since version 0.10.1.
do you have an idea?

**Comment by 3nids** [comment] 2018-01-15 14:23
pastebin for the crash https://pastebin.com/6u80XrR7

**Comment by ypro0** [comment] 2018-01-15 14:29
thank you for your reply. I am a basic user. I can not understand your
answer ...

2018-01-15 15:23 GMT+01:00 Denis Rouzaud <notifications@github.com>:

**Comment by 3nids** [comment] 2018-01-15 14:32
@ypro0 no worries, it's just an easier access to your crash report. We did not do any advance here yet.

**Comment by 3nids** [comment] 2018-01-15 14:33
@ypro0 what device are you using? do you know which version of Android?

@taff224 is the issue still present?

**Comment by ypro0** [comment] 2018-01-15 14:35
I'm using a Panasonic FZ-A2 with Android 6.0.1.
Thanks

2018-01-15 15:33 GMT+01:00 Denis Rouzaud <notifications@github.com>:

**Comment by taff224** [comment] 2018-01-15 15:05
I haven't tried it recently - I did manage to get it to install on my kids tablet - slightly updated version of mine and it worked fine.

**Comment by ypro0** [comment] 2018-01-22 08:32
Hello, do you have any news for me?
Thanks

**Comment by BeaSavoie** [comment] 2018-02-14 14:51
Hello,
Have you find a solution ? 
I have exactly the same configuration (FZ-A2 with Android 6.0.1) and I have an error fatal on installation.
What can I do ?
Thanks a lot.

**Comment by m-kuhn** [comment] 2018-02-24 13:27
Thanks for the log Chris and for all the information everyone.

There is a suspicious line in the log

```
E/art     (13970): dlopen("/data/data/ch.opengis.qfield/lib/libgnustl_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/ch.opengis.qfield/lib/libgnustl_shared.so" has unexpected e_machine: 40
```

And looking at the specs of FZ-A2, it looks like this tablet is shipped with an Intel processor (x86).

The app is currently only compatible with arm tablets, that would explain the error. I thought the app would simply not show up on these tablets in play store, I'm sorry for the inconvenience!

If there is interest, we can setup a build infrastructure for Intel processors (x86 architecture) as well. This would be around one day of work.

**Comment by taff224** [comment] 2018-02-24 22:22
Thanks, at least it is a simple explanation. Interesting that the next model on which my kids have must have an ARM processor as it loads fine on that.

Thanks

Chris

**Comment by m-kuhn** [comment] 2018-02-25 17:18
Let's keep this open until it's actually fixed!

**Comment by ypro0** [comment] 2018-02-26 15:01
Hello,
I have nearly all understood... I think...
Thank you for your help.
Does it still a chance for ne next versions? What about 1 day of work, only for one version or one time for all future versions?
Have a good day

**Comment by m-kuhn** [comment] 2018-02-26 16:59
So far we didn't do it because it would have to be done for each version. We recently implemented a new build system that automates everything, so this 1 day would be an initial effort and then every new version would be compatible.

**Comment by ypro0** [comment] 2018-02-26 18:01
Ok. Done.

**Comment by ypro0** [comment] 2018-02-27 16:55
Bonjour BéaSavoie, pourrions nous communiquer pour faire avancer les choses.
yperso0@gmail.com
Merci.

**Comment by m-kuhn** [comment] 2018-03-11 14:08
We don't have a x86 tablet to test, so it would be nice if someone could [verify our first test apk for x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-87ce5f753d8d896bec12ec5be56fcd90f97bf434-x86.apk).

**Comment by BeaSavoie** [comment] 2018-03-12 10:17
Hello,
I can test on our tablet your first apk but I can't access to the server... Connection timed out...
![opengis](https://user-images.githubusercontent.com/36480350/37278107-ed19d816-25e6-11e8-91a8-fb6fd78c028e.png)
Thanks...

**Comment by m-kuhn** [comment] 2018-03-12 12:22
Sorry, we are currently experiencing technical problems. We are working on it and will tell you when it's back up.

**Comment by BeaSavoie** [comment] 2018-03-12 14:17
No problem, I can test when you're ready..
Thanks a lot...

**Comment by m-kuhn** [comment] 2018-03-12 14:44
We are backup and running.
It was a faulty mainboard, luckily our service provider replaced it in almost no time.

**Comment by BeaSavoie** [comment] 2018-03-12 15:55
I can install your apk on our tablet without problem. I installed and Qfield open. Thanks a lot ! 
I'll test this week with differents Qgis projects and I'll report you any encountered problems...
If you have some specials tests to do, tell me... I'll test it...

**Comment by m-kuhn** [comment] 2018-03-12 16:34
:tada: does that mean we have it running on X86 tablets where it was crashing on startup before?

**Comment by BeaSavoie** [comment] 2018-03-12 16:38
I have a Panasonic Toughpad pro FZ-A2 tablet with an ATOM x5 intel processor. 
Before, it was crashing on startup and today with your new apk, it's OK.... I haven't a crash ! 
![image](https://user-images.githubusercontent.com/36480350/37296733-1b5119d0-261c-11e8-8e40-648afcad6e22.png)

**Comment by ypro0** [comment] 2018-03-12 16:41
Hi,
It works on my tablet to! It is the same Panasonic.
Thanks a lot!
Yann

**Comment by taff224** [comment] 2018-03-12 16:53
Hi - just downloaded and installed the apk and it seems to work on the tablet I failed on originally. I will need to get the wife to provide me with a QGIS file to test it fully but definitely a lot further on than it got when i raised the problem.

Thanks for your efforts.

Chris

**Comment by ypro0** [comment] 2018-03-13 15:20
Hi,
I have quickly tested this version (in my office...).
On my device, on my device, the first launch page ("The app is now up and
running.....")  reappears each time the application is launched.
Thanks.
YAnn

2018-03-12 17:53 GMT+01:00 taff224 <notifications@github.com>:

**Comment by m-kuhn** [comment] 2018-03-25 12:18
This has been released in 0.10.10.
Can anyone confirm that it installs the correct version from the PlayStore.

**Comment by m-kuhn** [comment] 2018-03-26 06:50
@VxTedxV currently on arm devices 0.10.11 should be installed, on intel devices 0.10.10. Can you confirm?

**Comment by ypro0** [comment] 2018-03-26 08:42
Hi,
The installation on Google Play doesn't work. It is like before : it failes
when arrived at 92% of installation.
There is an annoucement "This application is certainly not optimized for
your device"


2018-03-26 8:50 GMT+02:00 Matthias Kuhn <notifications@github.com>:

**Comment by m-kuhn** [comment] 2018-03-26 13:00
> There is an annoucement "This application is certainly not optimized for your device"

Is this a translation? If yes, can you give us the original (untranslated) message.

**Comment by VxTedxV** [comment] 2018-03-26 21:02
I can only confirm for ARM -> 0.10.11

**Comment by ypro0** [comment] 2018-04-25 07:52
Hi,

The problem is the same: no possible installation of the new version of
Qfield from Google Play.

Have a nice day!


2018-03-26 23:02 GMT+02:00 VxTedxV <notifications@github.com>:

**Comment by m-kuhn** [comment] 2018-04-25 08:38
We are still trying to figure out how exactly google play works, both releases (arm and x86) are published and detected to be platform specific apparently. We'll try to upload them to a single release next time, please keep posting your test results!

**Comment by ypro0** [comment] 2018-04-25 08:47
Ok, thanks a lot for all your efforts.
Is the new version disponible for x86 somewhere ?

2018-04-25 10:38 GMT+02:00 Matthias Kuhn <notifications@github.com>:

**Comment by m-kuhn** [comment] 2018-04-25 08:56
Yes, all releases are available for download here https://github.com/opengisch/QField/releases

**Comment by 3nids** [comment] 2019-01-31 19:58
can we close this?

**Closed** 2019-02-01 08:31 UTC
Labels: bug
