### ISSUE TITLE
Option to disable closing QField by double backarrow tap

### ISSUE THREAD

**Issue by GuyGeneau** [opengisch/QField#4770] opened 2023-11-15 19:17 UTC
On android device, if you touch twice de backarrow, Qfield is shutting. We are using the lockscreen while navigating with the phone in our jacket's pocket (inventory jacket in forestry) but when the weather isn't on our side (rain, humidity, etc.), the android buttons are doing things on their own! 

Would it be possible to add a function in the menu to close the app instead of the double backarrow of the android? It would be much safer to not any unsaved data.

Thanks.

**Comment by Ipickedausername** [comment] 2023-11-16 11:24
Proposed here : [https://github.com/opengisch/QField/issues/3451](url)

**Comment by suricactus** [comment] 2023-11-16 12:21
Thanks for spotting the duplicate.

**Comment by suricactus** [comment] 2023-11-16 12:22
Duplicate of #3451

**Closed by suricactus** 2023-11-16 12:22 UTC
Labels: ENHANCEMENT
