### ISSUE TITLE
Layer visibility individually with categorized symbols

### ISSUE THREAD

**Issue by vowasemp** [opengisch/QField#234] opened 2018-03-05 07:58 UTC
Controlling layer visibility individually with categorized symbols

### Reproduction Steps:

1. long press on layer name (categorized symbols) -> uncheck checkbox 'show on map canvas' -> symbols disappear
2. long press on layer name (categorized symbols) -> check checkbox 'show on map canvas' -> symbols are not shown
3. long press on layer category -> check checkbox 'show on map canvas' -> symbols of that category are shown

### Expected behavior:

When setting the whole layer to visible, all the categories should be visible. If there are a lot of categories, its not very comfortable to turn on the visibility for each category separatly

### Screenshots and GIFs

Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 0.10.9

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by vowasemp** [comment] 2018-03-05 14:00
I did some additional tests, this behaviour happens only with presets. Without presets it's working fine

**Comment by signedav** [comment] 2019-11-18 15:15
Can be reproduced by using the demo project "offline_bees" on map theme "diseases".

**Comment by signedav** [comment] 2019-11-18 15:16
I close this because of duplicate. Keeping #175 open.

**Closed by signedav** 2019-11-18 15:16 UTC
Labels: BUG-, checked, duplicate
