### ISSUE TITLE
Feature count causes hidden symbol in legend

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#181] opened 2017-10-25 07:45 UTC
If you check the "Count Feature" Option in QGIS and then transfer this project to qfield, qfield will not show the symbology in the table of content. The following images illustrate the problem:

**Situation without Feature count:**
on QGIS:
![qgis without feature count](https://user-images.githubusercontent.com/20398621/31986435-c4ffc86c-b968-11e7-85dc-509ada6cebc7.PNG)

on QField
![qfield without feature count](https://user-images.githubusercontent.com/20398621/31986438-c8ee354e-b968-11e7-86ac-9c1441d1ad28.png)

**Situation with Feature count for layer radiotagging:**
on QGIS
![qgis with feature count](https://user-images.githubusercontent.com/20398621/31986449-d72219c8-b968-11e7-9794-ba0865e98bd9.PNG)

on QField
![qfield with feature count](https://user-images.githubusercontent.com/20398621/31986453-db36cd06-b968-11e7-9b93-7ae70e52362c.png)

And here the project if you want to check yourself:
[qgis-project.zip](https://github.com/opengisch/QField/files/1413682/qgis-project.zip)

**QField version:** [0.10.1]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Not sure but I think it depends on the file, with geopacke it is certainly an issue]

**Comment by saemiw** [comment] 2017-10-25 07:46
Additional info. According to my coworker this problem disappears when using qfieldsync. So maybe the issue is really specific to the geopackage format.

**Comment by signedav** [comment] 2018-01-18 10:11
I tried to reproduce. I didn't use qfieldsync but copied the project from your zip to my tablet directly instead. There is still the symbology. I've got version 0.10.4 - probably it's solved already there.
Did you tested it with 0.10.4 as well or only 0.10.1 @saemiw ? 
@m-kuhn where there changes effecting a solution on that?

**Comment by m-kuhn** [comment] 2018-01-18 14:20
Nothing I am aware of.
@saemiw, can you attach (or send us) a sample project that demonstrates the issue?

**Comment by saemiw** [comment] 2018-01-18 16:44
I'll check tomorrow (under 0.9.10 I can still reproduce the error with).

**Comment by saemiw** [comment] 2018-01-18 16:51
It seems fixed. On the same device I was able to reproduce the issue with 0.9.10. After updating to 0.10.4. I could not reproduce the error anymore. I'll ask my coworkers to check (as they had most problems with that issue) but it seems like you already fixed it. ;D

**Comment by gaby-h** [comment] 2018-01-22 12:48
When "single symbol" is used, the problem seems to be fixed with version 0.10.4
But a new problem occurs with version 0.10.4 when using "categorized" rendering, impossible to display the categorized symbols, QField crasches (see issue 199).
This problem did not exist with version 0.9.6:
![categorized](https://user-images.githubusercontent.com/33145785/35217454-ad7dd8a2-ff6b-11e7-81ac-d52cf53aa040.jpg)
Test-project to check
[categorized.zip](https://github.com/opengisch/QField/files/1651948/categorized.zip)

**Comment by signedav** [comment] 2018-01-22 13:02
Thanks for reporting. I'll have a look.

**Comment by saemiw** [comment] 2018-01-22 14:47
@signedav @gaby-h is also working at vogelwarte. She'll check some issues (and their fixes) we are paying for currently.

**Comment by signedav** [comment] 2018-01-29 14:51
Fixed in Version 0.10.5 (in Playstore for Beta-Testers or [here](https://github.com/opengisch/QField/releases/tag/release-0.10.8_5))

**Closed by signedav** 2018-01-29 14:51 UTC

**Comment by saemiw** [comment] 2018-02-20 14:44
Seems to work fine even though you need sometimes many tries to actually open the extended symbolgy view (are very fine fingers). Nothing very urgent unless you see a very easy way to improve this...I always need 3-5 tries until I manage to show the extended symbology.

**Comment by signedav** [comment] 2018-02-20 15:05
It should be a double click on the layer or a single click on the triangle on the left.
Is it like this?
If yes, we know at least that it's working how it should. But we still could discuss improvement of usability of course.

**Comment by saemiw** [comment] 2018-02-20 15:36
Ahh double click (I didn't know) works really well!

**Comment by signedav** [comment] 2018-02-20 15:52
So you like the handling with double click? 

I confess that it's not that clear when you don't know it. But I think it's quite handy like this.

**Comment by saemiw** [comment] 2018-02-20 16:10
Yea, double click is perfectly fine for me. You just need to know. ;D
