### ISSUE TITLE
Value Relation Widget - Filter expression

### ISSUE THREAD

**Issue by nicpitsch** [opengisch/QField#950] opened 2020-04-11 18:21 UTC
The question originally posted by @jhonalex06 refers to an issue, which is still open: *Filter expression*:

> Hi, I have a question 

> i try to use the filter expression, but it didn't work, is possible implement the filter expression?

> ![image](https://user-images.githubusercontent.com/27906888/61477019-f50a8d80-a953-11e9-9a90-762f0cd82578.png)

_Originally posted by @jhonalex06 in https://github.com/opengisch/QField/pull/600#issuecomment-512903064_

**Comment by nicpitsch** [comment] 2020-04-11 19:45
The idea behind is related dropdown content as expliced [here](https://www.northrivergeographic.com/archives/qgis-3-2-drive-down-lists-aka-value-relation-widget).

**Comment by m-kuhn** [comment] 2020-04-13 20:03
Is this a duplicate of https://github.com/opengisch/QField/issues/436 and/or https://github.com/opengisch/QField/issues/724 ?

**Comment by nicpitsch** [comment] 2020-04-14 03:10
Yes, it's a duplicate of #436 as far at it concerns **Filter expression** property for *Value Relation* Widget Type.
In #724 it's described as *Filter functions* - I suppose it's the same. 
Sorry, I should have investigated better befor opening a new issue.

**Comment by m-kuhn** [comment] 2020-04-14 05:24
It would be a great functionality to add. Please feel free to pitch the other issues !

**Closed by m-kuhn** 2020-04-14 05:24 UTC
