### ISSUE TITLE
selection highlight geometry not overlay the selected feature

### ISSUE THREAD

**Issue by donkey12345** [opengisch/QField#119] opened 2017-03-29 06:29 UTC
the selection highlight geometry not overlay the selected feature.

Screenshots:
![11](https://cloud.githubusercontent.com/assets/26738889/24446126/f9926db0-149e-11e7-8c8d-81c77802c38b.png)

when select features ,the  highlight geometry always offset the original feature! when zommin the map  or pan the map,the offset is larger! what's wrong with it?

Thank you for your answer

**Comment by m-kuhn** [comment] 2017-03-30 07:15
Does this only happen when zoomed in very much or on every zoomlevel?

**Comment by donkey12345** [comment] 2017-03-30 10:52
yes, when zoomed larger ,the offset larger.but when i pan the map,the offset is also changed.
when map is smaller scale,the offset is exist,Just not so obvious . 
Thank you for your reply!

**Comment by m-kuhn** [comment] 2017-03-30 11:23
And when you are zoomed in and pan, the offset does "jumps"?

**Comment by donkey12345** [comment] 2017-03-30 11:57
it seems dose not jumps obvious ！olny  the offset change!

**Comment by m-kuhn** [comment] 2017-03-30 12:02
I am still not completely true, how the offset change happens if not in jumps.

My assumption is that this corresponds to the following development proposal:
http://www.qfield.org/docs/development/index.html#improved-coordinate-precision .

**Comment by donkey12345** [comment] 2017-03-30 12:29
I guess：

1.is it relate to Coordinate transformationl(maybe is map to screen)?

2. QtQuick draw GGeometry item is not exactly  overlay the qgis draw the map?

**Comment by m-kuhn** [comment] 2017-03-30 12:48
Pretty much.

(Most) OpenGL implementations don't support double, so they use float. Add to that that `qreal` is also defined to `float` on arm qt builds.

So to fix this issue, the code responsible to create the opengl representation of the geometries should reproject them into an intermediate coordinate system that offers enough precision in the area of interest to convert a pixel-precise representation in screen coordinates. The tricky bit is finding the appropriate intermediate coordinate system automatically.

**Comment by donkey12345** [comment] 2017-03-31 01:34
ok ,thanks for your help.
i will take a look at the code in detail

**Comment by m-kuhn** [comment] 2017-04-07 05:56
> there is no map coordinates to the screen coordinates transform. Directly using map coordinates. Is this correct?

> Is there any other place to set or transform the coordinate ?

Translation from map units to screen units is done on the GPU

https://github.com/opengisch/QField/blob/master/src/qgsquickmapcanvasmap.cpp#L210-L220

**Comment by donkey12345** [comment] 2017-04-07 07:48
thank you, i saw it. 
So is the Transform operation(GPU) caused by the loss of precision? 
And in my environment I see the QREAL definition is the DOUBLE type not real.

#if defined (QT_COORD_TYPE)
Typedef QT_COORD_TYPE qreal;
#else
Typedef double qreal;
#endif

**Comment by m-kuhn** [comment] 2017-04-07 07:53
> And in my environment I see the QREAL definition is the DOUBLE type not real.

On ARM (almost all android devices) it's float

> So is the Transform operation(GPU) caused by the loss of precision?

Pretty sure that it's this (or at least that this is a part of it).
One will need to determine a suitable intermediate coordinate system, send the coordinates to the GPU in this intermediate space and then instruct the GPU to transform from the intermediate space to screen coordinates.

**Comment by donkey12345** [comment] 2017-04-07 08:04
Why not use the original Transform method  in QGIS?

**Comment by m-kuhn** [comment] 2017-04-07 08:05
Because the GPU can do this faster and with less battery consumption

**Comment by donkey12345** [comment] 2017-04-07 08:18
ok ,thank for your reply
But I feel that if this is done, the problem is tricky.

**Comment by m-kuhn** [comment] 2017-04-07 08:22
Yes, it is tricky ;)

**Comment by donkey12345** [comment] 2017-04-10 03:47
I used QTCREATER to debug(press run debug button ) the QFIELD program and found that the program hangs when running in debug mode . The device screen is displayed in black, and no interface elements are displayed. Whether the program can not break the point debugging?

It seems that the line of code starts to hang:  load (QUrl ("qrc: /qml/qgismobileapp.qml")) in qgismobileapp.cpp;

**Comment by signedav** [comment] 2019-11-19 08:10
Reproduceable with the demo project offline-bees 
![WhatsApp Image 2019-11-19 at 09 09 44](https://user-images.githubusercontent.com/28384354/69128366-6d24c380-0aac-11ea-8015-8ece0b918f72.jpeg)

**Comment by jlgranda** [comment] 2020-12-11 18:42
The bug persist in the current time. 
![qfield_zoom_issue](https://user-images.githubusercontent.com/1143320/101941860-95e79180-3bb6-11eb-87a5-e93b7828afe2.gif)

**Comment by nirvn** [comment] 2021-01-30 02:06
Fixed in upcoming QField 1.9.

**Closed by nirvn** 2021-01-30 02:06 UTC
Labels: BUG
