### ISSUE TITLE
@gnss_fix_status_description wrong when using lefebure and direct connexion

### ISSUE THREAD

**Issue by ewaca** [opengisch/QField#2623] opened 2022-03-20 14:00 UTC
i'm using Ntrip lefebure with F9p external gnss receiver (bluetooth) on android 11.
the value returned by @gnss_fix_status_description is always "FIX3D" even if i am in "floatRTK" or "DGPS" with lefebure client.

### Reproduction Steps:

every time i'm using the app

### Expected behavior:

get "float rtk" value for the variable @gnss_fix_status_description when correction is float rtk

### Screenshots and GIFs
![Screenshot_20220320-145413_Lefebure_NTRIP_Client](https://user-images.githubusercontent.com/29289462/159166029-84ab4b26-6230-4148-bd38-bb9638c23c7c.png)

**Comment by m-kuhn** [comment] 2022-03-25 05:30
Are you able to connect directly (i.e. not via lefebure)?

**Comment by ewaca** [comment] 2022-03-25 19:36
here are the screenshots with direct BT connexion with my antenna.
With direct connexion, it seems my antenna is recognized as GNSS antenna. I have more details  in position information (bottom of 2nd screenshot) whereas i have not theses details through lefebure connexion.
![Screenshot_20220325-201823_QField_Dev](https://user-images.githubusercontent.com/29289462/160188672-a5a1bd16-7e2a-4d76-918f-efd3e1942259.png)
![Screenshot_20220325-202339_QField_Dev](https://user-images.githubusercontent.com/29289462/160188774-095a2cad-ddb3-40e8-a23d-c622aeb834be.png)
![Screenshot_20220325-202409_QField_Dev](https://user-images.githubusercontent.com/29289462/160188782-9fc4e281-6737-4c93-b739-848fdffc2631.png)

**Comment by m-kuhn** [comment] 2022-03-26 15:44
It's preferable to use direct connection over lefebure.
Do you have the possibility to connect your receiver to QGIS and check the reported rtk status there?

**Comment by ewaca** [comment] 2022-03-26 16:19
sorry, i don't understand want you meen. In my first post, my antenna was connected over lefebure client with Bluetooth. 
direct connection = usb cable connection ?
i will try to conect my receiver to Qgis on my pc with BT and usb cable. I'll post the results as soon as it's done.

**Comment by ewaca** [comment] 2022-03-26 16:58
here, screenshot with USB : 
![usb](https://user-images.githubusercontent.com/29289462/160249640-1e97c936-a1c7-439d-a443-ee9d75ecc7ae.PNG)


and here, screenshot with BT : 
![bluetooth](https://user-images.githubusercontent.com/29289462/160249663-26483c92-ea2b-475b-877e-5d9f47174f0e.PNG)

**Comment by m-kuhn** [comment] 2022-03-26 16:58
Direct connection = bluetooth to qfield (no lefebure)

**Comment by ewaca** [comment] 2022-03-26 17:11
ok, so it was i understood, only first post was with lefebure, all others are with direct connexion.

**Comment by nirvn** [comment] 2022-03-26 17:25
@ewaca , have you tried the @gnss_fix_mode variable?

**Comment by nirvn** [comment] 2022-03-26 17:40
Having looked into the QGIS side of things (which QField relies on), its implementation/understanding of the fix mode is incomplete at this moment. It only returns automated/manual.

**Comment by ewaca** [comment] 2022-03-26 17:57
i have tried @gnss_fix_mode first, but it returned blank field ... so i have tried fix_status_description.
ok, it already prety cool to be able to record horizontal and vertical accuracy .

**Comment by nirvn** [comment] 2022-03-27 05:05
@ewaca , there's a QGIS fix incoming (https://github.com/qgis/QGIS/pull/47979). Once that's merged, I'd advise you to try a qgis-dev nightly (on OSGeo4W installer) and check whether the QGIS GPS panel returns the proper value (in the qualite field). 

If it does return the value you've been expecting, then you will need to use the @gnss_quality_description variable in your attribute form.

I'm closing this as the issue is upstream.

**Closed by nirvn** 2022-03-27 05:05 UTC
