### ISSUE TITLE
Crash after layer switching

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#477] opened 2019-02-15 08:12 UTC
I do have a QGIS 3.4.4 Project, use QField Sync 3.1.1 and QField 1.0.0-rc3 to set it offline. With some layers that were used the QFieldSync action "copy" I have problems. Upon selecting that layer, then selecting an offline layer and trying to add a new feature in this offline layer QField crashes. 

First I thought I was able to very consistently (like 10 times in a row) reproduce the crash. But now suddenly it crashes and sometimes not. I first thought it was tied to the layer options "searchable" or "editable" but I get the crashes with and without this options.  I also noticed that it happens with geopackage and shapefile.  The only thing clear seems that it doesn't happen with layers that were set offline (by QFieldSync). I am happy to provide my project through wetransfer if you like testing your self. I keep you updated if I find out more.

**Comment by saemiw** [comment] 2019-02-15 10:50
Update 1: The crash does not only happen upon data entry. It happens on any next action. So this will lead to a crash at steh 3: 1) click on non-offline layer, 2) click on offline-layer, 3) click on another non-offline layer

**Comment by 3nids** [comment] 2019-02-19 03:35
yes, please share the project if you can.

**Comment by saemiw** [comment] 2019-02-19 07:38
I sent a donwload link via email. Try to do this to reproduce the crash:

1. Open the project with QGIS 3.4.4
2. Set it offline with qfieldsync 3.1.1
3. Copy the project to your tablet running QField 1.0.0-rc3
4. Add a few points for the layer "deadwood"
5. click in the layers panel on the layer "birds
6. Click again on the lyer "deadwood" and try to digitize another point

After point 6 it crashes (most of the time). The same is true for layer "mcp100" and probably more layers.

**Comment by gioman** [comment] 2019-02-19 10:36
> yes, please share the project if you can.

@3nids this is most likely duplicate of https://github.com/opengisch/QField/issues/474

**Comment by 3nids** [comment] 2019-02-20 02:40
@saemiw sorry, I am not able to reproduce the crash, I tried the steps about 10 times without any crash. Do you have any mean to provide a crash log?

**Comment by saemiw** [comment] 2019-02-20 07:27
> @saemiw sorry, I am not able to reproduce the crash, I tried the steps about 10 times without any crash. Do you have any mean to provide a crash log?

ehh...how do I get access to it? Is it generated automatically?

**Comment by geostonemarten** [comment] 2019-02-21 09:33
T

> > @saemiw sorry, I am not able to reproduce the crash, I tried the steps about 10 times without any crash. Do you have any mean to provide a crash log?
> 
> ehh...how do I get access to it? Is it generated automatically? Did you uese exactly the same QGIS, QField and QFieldSync versions. I notice with other problems that developers tend to test (for understandable reasons) on their test environment/versions which sometimes explains the differenc ;D

There is no crash log for this https://github.com/opengisch/QField/issues/485#issuecomment-465924422

**Closed** 2019-03-04 16:44 UTC
