### ISSUE TITLE
qfield crashes using non-native camera

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#4760] opened 2023-11-13 16:17 UTC
### Describe the issue
New qfield release crashes when I use non-native camera. In prevoius versions for me the issue was the same but using native camera, now it is the opposite.

### Reproduction steps
1. Set non native camera
2. Take a picture
3. Qfield crashes

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device:OPPO and Redmi 10
 - OS: Android
 - QField version: 3.0.6

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment] 2023-11-14 02:35
Duplicate of https://github.com/opengisch/QField/issues/4704.

**Closed by nirvn** 2023-11-14 02:35 UTC
