### ISSUE TITLE
Last working version for Samsung Tab E 1.4.4

### ISSUE THREAD

**Issue by tveinot** [opengisch/QField#1203] opened 2020-08-12 16:24 UTC
The last working reslease for the Samsung Tab E is 1.4.4, I know it is an old tablet but I thought I would mention it.

### Reproduction Steps:

1. Install Any version greater then 1.4.4 on Samsung Tab E
2. Run QField
3. QField will either close earely in it's start up or when you try and open a project depending on the version installed

### Expected behavior:

This might be an issue with Google Play but when you install through Play it will use the most recent release and not the last working release.

### Observed behavior:

You have to download 1.4.4 rom GitHub and Install in order to keep QField working.

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment] 2020-08-13 16:26
What's the Android version of your tablet?
See http://lists.qfield.org/pipermail/users-qfield.org/2020-May/000090.html
And https://github.com/opengisch/QField/issues/1125

**Comment by tveinot** [comment] 2020-08-13 16:38
Android 7.1.1

**Comment by m-kuhn** [comment] 2020-08-13 16:39
Can I safely assume it's a 32 bit device (arm-v7a)?

**Comment by tveinot** [comment] 2020-08-13 17:07
Thats an affirmative

**Comment by m-kuhn** [comment] 2020-08-13 17:17
Honest response:

I would *love* to continue supporting *any* device out there. However it seems that (for unknown reasons, I guess it's mostly neglection and not "planned obsoletion") this becomes harder and harder and things that used to work suddenly start acting strange. At the same time the number of active users of such devices becomes fewer. And often when asked, it's cheaper for people to buy new devices rather than investing into fixing software.
I was promised a 32 bit device which should arrive every day here. I hope to find some time -- and prevent users out there from being forced to dump hardware for no good reason.

**Comment by tveinot** [comment] 2020-08-13 17:24
Matthias;
I completely understand where you are coming from and honestly I was on the
fence to even mention the issue due to the age of the device in question. I
wouldn't worry too much about fixing it, as long as I can get the 1.4.4
version it should last us until we get new hardware.
Tyler

**Comment by m-kuhn** [comment] 2020-08-14 08:13
Shall we close this as duplicate of #1125 ?
If possible you can still provide a locat, to check what the reasons for the crash are.

**Comment by tveinot** [comment] 2020-08-14 10:45
Matthias;
Yeah close it, it was more of an FYI than anything. If I can find a
resolution I will let you know in issue 1125.
Cheers;
Tyler

**Closed** 2020-08-14 11:17 UTC
