### ISSUE TITLE
The measurement tool does not indicate the distance since latest update

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#4633] opened 2023-10-11 16:49 UTC
### Describe the issue
When activating the measurement tool in QField, it doesn't indicate the distance but it says "Segment: nam m" and "Length: nan m"
See the printscreen.

### Screenshots and GIFs

![Screenshot_20231011_184355](https://github.com/opengisch/QField/assets/57868975/f1b5a494-ecbb-45ba-ab0c-d17c52b9d8a4)

### Mobile (please complete the following information)
 - Device: Samsung A50, A52 and others
 - OS: Android 13
 - QField version: Latest one
 - 
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: No

**Comment by nirvn** [comment] 2023-10-11 16:51
@BoswachterMarc , can you provide a test project? With the sample bees project I can't replicate this issue

**Comment by BoswachterMarc** [comment] 2023-10-11 18:39
@nirvn I need to check more thoroughly; I see I can't replicate it either in another project... I will keep you informed

**Comment by BoswachterMarc** [comment] 2023-10-12 07:31
@nirvn I just tried re-installing the previous version qfield-v2.8.7-arm64-android.apk Insightful Indri on the device of a collegue and the measurement tool works as expected in the previous version (no 'nan m'). In other words, I think the bug is not in our project...

**Comment by nirvn** [comment] 2023-10-12 07:40
@BoswachterMarc , right, something must have regressed, but unless I can reproduce locally, it'll be hard to fix, and that's where your project comes in :) can you share a sample project that shows the issue?

**Comment by BoswachterMarc** [comment] 2023-10-12 07:50
@nirvn Can you use/download our cloud project Walden_v6a? It is a rather big project to share here...

**Comment by nirvn** [comment] 2023-10-12 08:05
@BoswachterMarc , if you take your project and remove all the layers (except openstreetmap), and save that as a small sample project, that should work. I suspect the problem has to do with the project CRS and/or some of the project unit display settings. That reduced project should be small enough to attach to this issue. Thanks.

**Comment by nirvn** [comment] 2023-10-12 11:47
Tried to replicate this issue some more just now, to no success. We'll definitively need a test project showcasing this issue to progress.

**Comment by BoswachterMarc** [comment] 2023-10-12 11:53
@nirvn I tried to quickly package the project as you said with QPackage but that didn't work out. I will come back to you later on.

**Comment by BoswachterMarc** [comment] 2023-10-12 16:37
@nirvn I removed all layers from the project and *.gpkg. OSM is still there. I hope this helps ;-)

[Walden_sample_gpkg.zip](https://github.com/opengisch/QField/files/12884995/Walden_sample_gpkg.zip)
[Walden_sample_qgs.zip](https://github.com/opengisch/QField/files/12884996/Walden_sample_qgs.zip)

**Comment by nirvn** [comment] 2023-10-13 04:53
@BoswachterMarc , excellent, I'm able to reproduce the issue now.

I've not been able to identify _why_ it's happening, but the good news is a/ it appears fixed in upcoming QGIS 3.34, which QField will adopt sooner than later, and b/ you can work around this issue by setting your project properties' measurement ellipsoid to none (away from International 1924):

![image](https://github.com/opengisch/QField/assets/1728657/87f17306-2f3a-4646-9e27-1b6e684e3924)

**Comment by nirvn** [comment] 2023-10-13 10:12
@BoswachterMarc , actually, it seems like the issue is (in part) with your project file; you can remove this section in your .qgs file and the measurements will work:

```
    <srcDest coordinateOp="+proj=pipeline +step +inv +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +step +proj=push +v_3 +step +proj=cart +ellps=intl +step +proj=helmert +x=-106.8686 +y=52.2978 +z=-103.7239 +rx=0.3366 +ry=0.457 +rz=-1.8422 +s=-1.27469999999796 +convention=position_vector +step +inv +proj=helmert +x=-99.059 +y=53.322 +z=-112.486 +rx=-0.419 +ry=0.83 +rz=-1.885 +s=-1 +convention=coordinate_frame +step +inv +proj=cart +ellps=intl +step +proj=pop +v_3 +step +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl" allowFallback="1">
      <src>
        <spatialrefsys nativeFormat="Wkt">
          <wkt>BOUNDCRS[SOURCECRS[PROJCRS["Belge 1972 / Belgian Lambert 72",BASEGEOGCRS["Belge 1972",DATUM["Reseau National Belge 1972",ELLIPSOID["International 1924",6378388,297,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4313]],CONVERSION["unnamed",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Longitude of false origin",4.36748666666667,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of false origin",90,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Latitude of 1st standard parallel",51.1666672333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Easting at false origin",150000.013,LENGTHUNIT["m",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",5400088.438,LENGTHUNIT["m",1],ID["EPSG",8827]],PARAMETER["scale_factor",1,SCALEUNIT["unity",1]],PARAMETER["Latitude of 2nd standard parallel",49.8333339,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]]],CS[Cartesian,2],AXIS["easting",east,ORDER[1],LENGTHUNIT["m",1]],AXIS["northing",north,ORDER[2],LENGTHUNIT["m",1]],ID["EPSG",31370]]],TARGETCRS[GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]]],ABRIDGEDTRANSFORMATION["Transformation from Belge 1972 to WGS84",METHOD["Position Vector transformation (geog2D domain)",ID["EPSG",9606]],PARAMETER["X-axis translation",-106.8686,ID["EPSG",8605]],PARAMETER["Y-axis translation",52.2978,ID["EPSG",8606]],PARAMETER["Z-axis translation",-103.7239,ID["EPSG",8607]],PARAMETER["X-axis rotation",0.3366,ID["EPSG",8608]],PARAMETER["Y-axis rotation",0.457,ID["EPSG",8609]],PARAMETER["Z-axis rotation",-1.8422,ID["EPSG",8610]],PARAMETER["Scale difference",0.9999987253,ID["EPSG",8611]]]]</wkt>
          <proj4>+proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.8686,52.2978,-103.7239,0.3366,0.457,-1.8422,-1.27469999999796 +units=m +no_defs +type=crs</proj4>
          <srsid>0</srsid>
          <srid>0</srid>
          <authid></authid>
          <description>Belge 1972 / Belgian Lambert 72</description>
          <projectionacronym></projectionacronym>
          <ellipsoidacronym>PARAMETER:6378388:6356911.94612794648855925</ellipsoidacronym>
          <geographicflag>false</geographicflag>
        </spatialrefsys>
      </src>
      <dest>
        <spatialrefsys nativeFormat="Wkt">
          <wkt>PROJCRS["BD72 / Belgian Lambert 72",BASEGEOGCRS["BD72",DATUM["Reseau National Belge 1972",ELLIPSOID["International 1924",6378388,297,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4313]],CONVERSION["Belgian Lambert 72",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",90,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",4.36748666666667,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",51.1666672333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",49.8333339,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",150000.013,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",5400088.438,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["Engineering survey, topographic mapping."],AREA["Belgium - onshore."],BBOX[49.5,2.5,51.51,6.4]],ID["EPSG",31370]]</wkt>
          <proj4>+proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +units=m +no_defs</proj4>
          <srsid>2640</srsid>
          <srid>31370</srid>
          <authid>EPSG:31370</authid>
          <description>BD72 / Belgian Lambert 72</description>
          <projectionacronym>lcc</projectionacronym>
          <ellipsoidacronym>EPSG:7022</ellipsoidacronym>
          <geographicflag>false</geographicflag>
        </spatialrefsys>
      </dest>
    </srcDest>
```

**Comment by BoswachterMarc** [comment] 2023-10-13 10:53
@nirvn I just gave your first solution (using the other ellipsoid) a try and that workaround works fine! Another project works well even though the ellipsoid is set to international. I imagine that then your second solution comes into view. Thank you

**Comment by nirvn** [comment] 2023-10-13 10:57
@BoswachterMarc , good to hear. I'm inclined to close this issue if that's ok with you. I think the problem comes from an old version of QGIS which created a perfect file be with a slightly broken  transformation. It'd be an upstream issue in any case.

**Comment by BoswachterMarc** [comment] 2023-10-13 11:07
@nirvn Closing the issue is fine for me ;-)

**Closed** 2023-10-13 11:07 UTC
