### ISSUE TITLE
Changes are not written to data.gpkg by QField

### ISSUE THREAD

**Issue by samillar94** [opengisch/QField#609] opened 2019-08-01 21:06 UTC
I have been wasting hours trying to get changes in QField to sync to QGIS, and have narrowed it down to a failure by QField to add new features to the `log_added_features` layer in `data.gpkg`.

### Reproduction Steps:

1. Layers set to offline editing and project exported
2. Files copied to mobile and features added in QField
3. In QGIS master project, hit "Synchronise from QField" 

### Expected behavior:

Entries in `log_added_features` and addition of new features to master project layers.

### Observed behavior:

No entries in `log_added_features`, no features transferred, no error messages.

**QField version:** 1.1.0

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

I'm running QField on a Huawei P Smart.

**Comment by saemiw** [comment] 2019-10-09 14:18
I was not able to reproduce the issue with QGIS 3.4.12, QField 1.2.0 using qfieldSync for setting the project offline.

**Comment by rwjdennis** [comment] 2019-10-26 16:43
I'm also having this problem. Looking at the geopackage log files, it appears for my project that the layer_id references may be wrong.
For example, when I export my project with QFieldSync, the point layer name "Trees_Field" gets a long string appended to it (e.g., "Trees_Field_bde016a9_22e3_4e6e_aaf5_e7945f43aaf5"), and the layer now has "(offline)" beside it. When I want to update the layer, QFieldSync apparently synchronizes the data, but no changes are made and no errors are logged (similar to @samillar94 ). 

When I look at the log files in the geopackage, the log_feature_updates and log_added_features reference layer_id in their attribute table, the value for which is at least 0. Looking at the log_layer_id, the qgis_id value for id=0 is "Trees_Field__offline__9f01cb53_1029_463f_9076_6ace43c0e3eb". If I understand the relations correctly, shouldn't the log_layer_id reference the table being updated, in this case "Trees_Field_bde016a9_22e3_4e6e_aaf5_e7945f43aaf5"? And so the reference to "Trees_Field__offline ..." could be why the updates aren't showing up.

**Comment by georgecorea** [comment] 2019-10-29 12:43
When I try the Synchronise from QField project, it just re-adds all the tables to the project without the updated data in the edited GPKG. I have set the editable files as offline and they are in a single gpkg with the same projection.

**Comment by meyerlor** [comment] 2019-11-04 09:00
I can confirm this behaviour. layer (in gpkg) set by the Syncplugin to offline editable. Added and changed features with Qfield. Syncing  back the data with Sync plugin wrote the changed features correctly to the database, but did not add newly created features

**Comment by rwjdennis** [comment] 2019-11-05 23:19
@meyerlor That is interesting, because I just updated my project using QFieldSync on the weekend, and only the new features were added, but no existing points were updated. Basically the inverse of what you just described. This was the first time it had happened like that for me, though.

**Comment by signedav** [comment] 2019-11-06 12:36
Can you test it with the current master builds [here](https://github.com/opengisch/QField/commit/3249a9ac1ee1e4fe38f549b6f58663cd538391d3#commitcomment-35774953) since there has been implementations flushing changes to the geopackage here #694

**Comment by nirvn** [comment] 2021-02-08 14:59
Fixed, closing.

**Closed by nirvn** 2021-02-08 14:59 UTC
Labels: BUG
