### ISSUE TITLE
Close doesn't close QField

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#184] opened 2017-10-25 13:06 UTC
Main Menu -> Close is supposed to close QField. When I use the show open apps button on my tablet QField is still open. This might be relevant when working with geopackages that stay in wal-mode (temporary state) as long as QField is open. Is it possible to really close the app as expected when pushing the buton "Close"?

**Comment by m-kuhn** [comment] 2017-11-22 15:05
Works as expected here (I did not check the WAL state of the layers though).

**Comment by saemiw** [comment] 2017-11-22 18:01
Honestly? You don't see QField when you click on this button? On my tablets qfield only disappears if I click this button and then "close all"
![prasentation1](https://user-images.githubusercontent.com/20398621/33142609-65ecca5e-cfb7-11e7-8800-c34e18dfe359.png)

**Comment by saemiw** [comment] 2017-11-27 15:38
Some more precision on this issue: 

I noticed that WAL-Files disappear when I close QField, but windows file explorer doesn't seem to update its presentation of the available files (even when I click the update symbol). When I disconnet and re-connect my tablet. Windows explorer correctly shows that wal-files have disappeared. This can be a problem when you connect your tablet, edit a layer without closing qfield then copy'n'paste the geopacke back from the tablet to your desktop computer directory (without noticing that there were still wal-files open). 

Under real field-work conditions this case is almost impossible because you always unplug your tablet... One should just not forget to close qfield BEFORE you connect the tablet with the desktop computer to make file transfer.

QField-Version used: 0.10.3

**Comment by m-kuhn** [comment] 2017-12-07 15:26
Strange, for me the wal and shm files disappear ~5 secs after closing qfield via quit in menu.

**Comment by saemiw** [comment] 2017-12-08 11:29
o.k. I think its not worth to invest more time on this issue. It is to specific and doesn't seem to be related to your code...

**Comment by m-kuhn** [comment] 2017-12-11 07:08
I'd still be interested to have a corrupted .gpkg file (with companion .shm/.wal if possible) if you have one somewhere.

**Comment by esigra** [comment] 2018-01-16 21:00
This issue is reproducible with QField 0.10.4 - Kesch on a SAMSUNG smartphone.

**Comment by signedav** [comment] 2018-01-22 08:10
Hi all. 
I could reproduce with Galaxy Tab 4 (Lollipop) and Galaxy S6 (Nougat) with the same behavior:
 
1. The app never closes completely. Same behavior when I close over the menu "Quit" as when I press the "Back" button (arrow back) on the device. QField exits all the submenus and goes to the "background" apps, reachable by the "Recent" button (two squares) to remove by swipe.
When the app is in the "background", the WAL-Files are still displayed in the filebrowser on Linux System (but disappears after a while or after unplug and plug USB - so they are not anymore on the device)

2. When pressing the home button the app goes to the "background" as well, but does not close the submenus. It's in real background-mode and the WAL-Files are not deleted.

So the question is, what should be done on:
- "Home" key button
- "Back" key button
- Menu "Quit"

And the possibilities are:
- App is in the **background but in the current state** (no close of open forms and submenues etc.) (WAL-files are not deleted)
- App is **"closed" but still in the background** (close of open forms etc.) (WAL-files are deleted)
- App is **"really closed" and not in the background anymore** (WAL-files are deleted)

### "Home" key button
I think this is clear. The app should be in the **background but in the current state**. 

### "Back" key button
As I understand this issue, I guess the expected behavior is, that the app should be in the **background but in the current state** as well. But this is IMHO not what a user expects. Because on most other apps they will be **"closed" but still in the background** then. I suppose that a QField user will expect that as well.

### Menu "Quit"
As I understand this issue, I guess the expected behavior is, that the app should **"really closed" and not in the background anymore**. But why? This is a behavior I cannot see on other apps. I think, a user NEVER expects a complete close (instead with swiping on "Resent" mode). I think a user expects always that any app will be **"closed" but still in the background** - because I don't know another app that complete closes. But here it's possible that I have a lack of information. But why do we have this menu option with "Close" anyway? What other app has such an option? Or is there a problem in the synchronization when the app is closed but still in the background? 

Probably you could have an input on that too @mbernasocchi @3nids

**Comment by saemiw** [comment] 2018-01-22 15:54
Excellent, thanks for following up on this issue!

To me it would be logical to close QField completely (no background running) when clicking "menue" -> "close" (inside qfield). With all the other buttons ("home", "back"), I don't expect Qfield to close. 

A proper closing could be helpful to avaid problems with WAL-files no? If I can tell our users to always close the app before copy'n'pasting files this is an easy message. For offline-synchronisation the problem is irrelevant because wal-files don't appear with sqlite (qfieldsync creates an sqlite-file).

**Comment by saemiw** [comment] 2018-01-23 07:20
> Even more, I would remove the "Quit" in the menu. 

I agree. Either remove it or close QField properly. I think it makes sense when you developpers make the final decision (as you have a broader overview).

**Comment by signedav** [comment] 2018-01-23 07:27
The user's opinion is very important too. Especially on questions regarding the handling of a product. But I'm happy you agree @saemiw  
@mbernasocchi probably you where involved in first design including the "Quit" - what is your opinion?

**Comment by signedav** [comment] 2018-01-23 08:23
Just had a call with mbernasocchi and he agreed that the "Quit" option does not make much sense. 
So I will remove this option and you close the app with the ordinary Android way of work: "Back" key and swipe it off in the "Recent" modus.

But we talked about other improvements we could think about in a next step (near future). For example to have a message, when pressing the "Back" button ( expl. "Press again to close the QGIS Project"). So the user is really sure it's closed and he can copy it back to the PC etc.

**Comment by signedav** [comment] 2018-01-24 19:51
For the two step close I opened a new issue #217 

Regarding this, is the "Quit" selection removed in future versions.

**Closed by signedav** 2018-01-24 19:51 UTC

**Comment by signedav** [comment] 2018-01-29 14:52
Issue #217 is implemented as well in Version 0.10.5 (in Playstore for Beta-Testers or [here](https://github.com/opengisch/QField/releases/tag/release-0.10.8_5))
