### ISSUE TITLE
Accessing internal GNSS on Windows devices

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#2221] opened 2021-10-11 00:12 UTC
I'm testing out the latest windows build from the installer (2.0.8) on a Panasonic Toughpad (FZ-G1W3102VA) and QField can't detect the internal GNSS chip. 

The log in cmd that shows up when I run QField.exe shows: 

    serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.

Where am I able to specify this - do I need to edit the source code and compile or is there a text file where I can change this value?
Or is QField unable to support this sort of GNSS chip just yet?

(I realise this is very much a beta version - there's a lot of things that aren't working quite right just yet, but I thought I'd flag this first)

**Comment by m-kuhn** [comment] 2021-10-12 14:51
Duplicate of https://github.com/opengisch/QField/issues/2038

**Closed by m-kuhn** 2021-10-12 14:51 UTC
