### ISSUE TITLE
qgis plugin crashes on 3.34.10

### ISSUE THREAD

**Issue by gdt** [opengisch/QField#5601] opened 2024-08-30 12:16 UTC
### Describe the issue
I have the QField plugin installed, and opening Project Properties shows information about QField and nothing else, and there's a crash warning.

### Reproduction steps
1. Build qgis 3.34.10 from pkgsrc.
2. Install and activate QField plugin
3. Open project properties.

### Expected behavior
One sees the full properties dialog.

### Observed behavior
python error, and only the qfield sub-screen

```
ProjectProperties.GeofencingBehavior.ALERT_INSIDE_AREAS,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: type object 'ProjectProperties' has no attribute 'GeofencingBehavior'
```

### QGIS (please complete the following information)
 - NetBSD/pkgsrc
 - 3.34.10
 - QFieldSync  4.10.1

### QField (please complete the following information)
This happens on the qgis computer, without even having a QField device.

### Additional information
This seems related to the new geofencing stuff, which I haven't seen before.

I think the root cause is that the qfield code for the properties dialog needs to catch exceptions  and do something reasonable.

Arguably there is also a qgis bug which is that a plugin's properties sub-module throwing an exception should result in the plugin's pane being marked or going missing, not breaking the whole properties dialog, but this bug report is about QField crashing.

**Comment by gdt** [comment] 2024-08-30 12:36
Error is resolved by deleting UI lines about Geofencing; see #5603 for experiment report.

**Comment by nirvn** [comment] 2024-08-30 13:38
Seems like root cause would be the same as the other issue filed, let's close this one.

**Closed by nirvn** 2024-08-30 13:38 UTC
