### ISSUE TITLE
Labels crash QField

### ISSUE THREAD

**Issue by grdaveygrd** [opengisch/QField#988] opened 2020-05-05 20:45 UTC
Using 1.5.0, and earlier versions, labels worked fine on my Samsung Tab S2 and Samsung A3 2016 - both with Android 7. Versions since then crash QField when a project is loaded with an enabled layer that has labels, or when a layer with labels is enabled after loading. Two layers with labels tried, QField works when the labels are not enabled, crashes when they are.

### Reproduction Steps:

Described above

### Expected behavior:

No crashing when using labels.

### Observed behavior:

Crashes when labels used in a layer

### Screenshots and GIFs

**QField version:**1.5.3 010503991 definitely didn't happen with 1.5.0. Did crash with 1.5.2

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes - 2 devices tried
* Problem happens with all files and projects, not only some files or projects: Yes - 2 projects with layers with labels tried, 2 different layers with labels.

**Comment by nirvn** [comment] 2020-05-06 00:56
Can you share a project that crashes for you?

**Comment by grdaveygrd** [comment] 2020-05-06 02:24
Thanks - here's a tiny project. When I load it into QField with labels on it immediately crashes. Without labels all is fine. I tried with another layer with labels on and off - same thing. I've been using QField for a couple of years and have found it incredibly useful, and getting better all the time. The only other problems I've had were early teething problems - getting it to actually behave on my devices. Sorry, just found I can't attach the files in this - how to do?

**Comment by grdaveygrd** [comment] 2020-05-06 02:26
Just realized you had emailed, attached are the files. With comment on the forum.
Regards,
Grant
    On Wednesday, 6 May 2020, 12:57:00 pm NZST, Mathieu Pellerin <notifications@github.com> wrote:  
 
 


Can you share a project that crashes for you?

**Comment by nirvn** [comment] 2020-05-06 04:27
@grdaveygrd , nothing attached here. You'll have to use github on your web browser, and drag 'n drop a zip file.

**Comment by grdaveygrd** [comment] 2020-05-06 05:03
Hopefully here it is. Thanks

[QField test.zip](https://github.com/opengisch/QField/files/4584864/QField.test.zip)

**Comment by nirvn** [comment] 2020-05-06 05:05
![Screenshot from 2020-05-06 12-04-54](https://user-images.githubusercontent.com/1728657/81139950-d54f5f00-8f91-11ea-8425-be6c61085077.png)

Not getting a crash over here (on master).

**Comment by grdaveygrd** [comment] 2020-05-06 05:08
I might try the uninstall everything and start again route. This definitely started happening with a new version of QField, on an old project already loaded into the device. Thanks.

**Comment by grdaveygrd** [comment] 2020-05-06 05:32
I uninstalled QField, reinstalled it and it still crashes with a layer that has labels.

**Comment by m-kuhn** [comment] 2020-05-06 07:19
See also https://github.com/opengisch/QField/issues/777

Current state of knowledge: It's related to 32 bit builds (and the stack trace shows to somewhere in PAL code). Desktop 32 bit (i686) QGIS builds do not crash.

**Comment by bartabbas** [comment] 2020-05-13 15:33
I've the same problem, if I'm right.

**Comment by frgis** [comment] 2020-05-16 17:10
I've the same problem.
Using Qgis 3.10.5 / Qfield 1.5.3 on Android 7.1

**Comment by frgis** [comment] 2020-05-17 05:42
notes : the problem does not exist in 1.5.1

**Comment by bartabbas** [comment] 2020-05-21 07:30
I solved my problem : label rendering has been changed from 'position around the point, 5 pixels' to 'offset from point'.

**Comment by nirvn** [comment] 2020-05-21 08:06
@bartabbas , what geometry type?

**Comment by grdaveygrd** [comment] 2020-05-24 22:51
Works with me too - if label placement is set to Offset from Point rather than Around Point - QField no longer crashes.

**Comment by florida63** [comment] 2020-05-28 10:44
Same problem.
Using Qgis 3.12.3 / Qfield 1.5.3 on Android 7.1

**Comment by bartabbas** [comment] 2020-05-30 10:47
@nirvn the geometry is point geometry.

**Comment by m-kuhn** [comment] 2020-06-08 08:03
I cannot reproduce this with newer builds (Qt, QGIS, GEOS updated).
Can someone give it a try with the builds from the following link?

https://github.com/opengisch/QField/pull/1053#issuecomment-640434997

**Comment by frgis** [comment] 2020-06-08 09:20
I just tested. I always reproduce the bug (armv7) - Android 7 - QGIS project 3.10
![Screenshot_20200608-111621](https://user-images.githubusercontent.com/56657014/84013975-ef59d400-a979-11ea-9d85-981088b7e86e.png)

**Comment by m-kuhn** [comment] 2020-06-08 09:24
Can you upload the data you are testing?
I used the one from the message https://github.com/opengisch/QField/issues/988#issuecomment-624443124

**Comment by nirvn** [comment] 2020-06-08 09:27
@m-kuhn , was libspatialindex updated too or not yet?

**Comment by m-kuhn** [comment] 2020-06-08 09:31
Not yet, but we've got a new infrastructure in place that makes this a piece of cake.

**Comment by frgis** [comment] 2020-06-08 09:44
I will test again by removing the aerial image. The project is too heavy to send.
I verify that I reproduce without the aerial image and I send the project.

**Comment by frgis** [comment] 2020-06-08 10:10
Attached the project.

1. Open the project
2. Change the theme (Photo + Route) -> I removed the aerial image.
3. Zoom in to see the streets (1/2000 or more).
4. When I move the map (about 5 or 6 pan) the application stop.

[TEST.zip](https://github.com/opengisch/QField/files/4745281/TEST.zip)

**Comment by m-kuhn** [comment] 2020-06-08 10:44
@frgis Your project runs here like a charm, but I don't seem to reproduce the problem any more with *any* project or *any* QField version, which makes it super hard to track.

If you could run `adb logcat` while reproducing the crash and then uploading this file somewhere, that could provide a lead.

**Comment by frgis** [comment] 2020-06-08 12:25
In attachment the requested log, thank you




[log_motog4.txt](https://github.com/opengisch/QField/files/4745894/log_motog4.txt)

**Comment by m-kuhn** [comment] 2020-06-08 12:28
Thanks, this is a confirmed duplicate of #777 in this case.

**Comment by m-kuhn** [comment] 2020-06-09 12:04
@frgis can I ask you to do another test with the build below?
It was built with debug information included in the hope to get more leads on the cause.

https://download.opengis.ch/qfield/ci-builds/qfield-dev-1053-c57c7465b92626b9f5609d73f8b8706781353a2c-armv7.apk

**Comment by frgis** [comment] 2020-06-09 21:02
Hi, with this version QField always stop. The associated log

Thanks
[log_moto.txt](https://github.com/opengisch/QField/files/4754839/log_moto.txt)

**Comment by m-kuhn** [comment] 2020-06-09 21:06
Thanks.

It's hard to tell anything from this log. It's not your fault. It appears the crash here happens much earlier for an unrelated reason. It would be good to have this validated on another device.

**Comment by koenigherford** [comment] 2021-04-19 11:38
I can confirm that the issue still exists with 32-bit devices (Samsung SM-T365 Galaxy Tab Active LTE-A with Android 5.1.1.) with QFIELD 1.9.3. 
Exported via QFIELD-sync (version from today) from QGIS 3.16.5.. 

64-bit devices are  working without problems.

Some infomations in map should/can only be displayed as labels (i.e. house-numbers). Therefore it will be great to have the labeling-function on 32-bit devices too so that the user will not be forced to buy new 64 bit-devices because auf enviromental and financial reasons.

Sample-projects can be shared (but no attachment-function available in this comment) :
My test-project contains:

just one point-layer with 69 points 

- default-style as suggested by QGIS

- with/without` labeling of one text-field. (Default-labeling-style. Just changed from "no labels" to "single labels" and selected a attribute-field for labeling.)

**Comment by grdaveygrd** [comment] 2021-04-19 20:39
Because of this issue I have had to stop using an otherwise ideal Samsung Tab S2 with 8 inch screen and go to a more modern 64 bit smart phone. This size of tablet is ideal for mapping with and I can't find a suitably specified new tablet of this size. But I've also found that the 3GB of RAM on the S2 seems also to be insufficient.

**Comment by lomptorne** [comment] 2021-06-28 13:53
I Allow myself to up this issue since I have the same problem on a Samsung SM-T555.
Is there any workaround for this problem ? Cause I need my labels for some projects. 

Thank you.

**Comment by m-kuhn** [comment] 2021-07-08 16:09
> I Allow myself to up this issue since I have the same problem on a Samsung SM-T555.
> Is there any workaround for this problem ? Cause I need my labels for some projects.
> 
> Thank you.

1. Contact us for a fix of the crash, we should be able to fix it within a couple of days of work
2. Possibly using fixed label positions (the source is a crash in the automated label placing mechanism) -- no guarantee that this works ...

**Comment by lomptorne** [comment] 2021-07-12 06:34
> 
> 
> > I Allow myself to up this issue since I have the same problem on a Samsung SM-T555.
> > Is there any workaround for this problem ? Cause I need my labels for some projects.
> > Thank you.
> 
>     1. Contact us for a fix of the crash, we should be able to fix it within a couple of days of work
> 
>     2. Possibly using fixed label positions (the source is a crash in the automated label placing mechanism) -- no guarantee that this works ...

Thank you for your anwser, yes I tried every position options, but it still crash. 
An also, yes it would be nice if your team will be able to fix it in a couple of days. 
I could also join a sample project if it could help you.

Thank you, regards,.

**Comment by m-kuhn** [comment] 2021-07-12 06:46
Thank you for the offer, we have sample projects and devices to reproduce the issue.
What is currently needed is some sponsoring to get this fixed.

**Comment by nirvn** [comment] 2024-03-23 11:09
@grdaveygrd , is this still an issue with latest QField 3.2.0? The workflow to build QField has considerably improved here, I would expect it to be working now.

**Comment by grdaveygrd** [comment] 2024-03-23 20:52
Thanks. This was a very long time ago and i barely recall it. I no longer have problems, possibly from using a different device.

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 24 Mar 2024 at 12:09 am, Mathieu ***@***.***> wrote:   


@grdaveygrd , is this still an issue with latest QField 3.2.0? The workflow to build QField has considerably improved here, I would expect it to be working now.

**Closed** 2024-03-23 22:20 UTC
Labels: BUG, feedback
