### ISSUE TITLE
Projects fail to open after download from locally hosted QFieldCloud

### ISSUE THREAD

**Issue by BizTechnology** [opengisch/QField#5716] opened 2024-10-07 12:39 UTC
### Discussed in https://github.com/opengisch/QField/discussions/5715

<div type='discussions-op-text'>

<sup>Originally posted by **BizTechnology** October  7, 2024</sup>

![qfield1](https://github.com/user-attachments/assets/fd6378d0-4ac1-414d-aefb-4fe7e2342337)

I'm currently facing some issues with our locally deployed QFieldCloud instance and could really use some help troubleshooting.

I've deployed QFieldCloud on a local server and am able to upload projects from QGIS to the locally deployed QFieldCloud instance successfully. However, QGIS has successfully uploaded the project to the QFieldCloud but when downloading it using QField, the following errors are displayed in the QField.

The errors I'm seeing in the QField are:

Project file read error in file c:/users/bizit/appdata/roaming/opengis.ch/qfield/cloud_projects/admin/5a536cbb-a423-4835-845f-85594bcdbe34/gis4_cloud_qfield.qgs: premature end of document at line 1, column 0
Error opening zip archive: 'c:/users/bizit/appdata/roaming/opengis.ch/qfield/cloud_projects/admin/5a536cbb-a423-4835-845f-85594bcdbe34/gis4_cloud_qfield_attachments.zip' (error code: 19) 
Failed to remove temporary file gis4_cloud_qfield_attachments.zip
Failed to remove temporary file gis4_cloud_qfield.qgs
Failed to remove temporary file data.gpkg

And when I try to download individual file from the QFieldCloud projects overview in QGIS, the downloaded file will become 0.00KB (zero kilo bites) and no xml code in the file. Kindly checkout the snapshot.
Has anyone else seen these errors when downloading projects from a locally hosted QFieldCloud instance? Any suggestions on how to troubleshoot or resolve the errors would be appreciated.

Any help pls. Or can anyone send us a proven working procedure to follow to install QFieldCloud locally that smoothly works with the QField. I've follow the GitHub steps but QField is facing problem to download and display the upload projects from locally deployed QFieldCloud.

Thanks.</div>

**Comment by suricactus** [comment] 2024-10-17 01:40
Duplicate of https://github.com/opengisch/QFieldCloud/issues/1044

**Closed by suricactus** 2024-10-17 01:40 UTC
Labels: self-hosted
