### ISSUE TITLE
Error in the relation between an alphanumeric form and geometric form

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#1686] opened 2021-02-12 21:51 UTC
When I try to associate a **Terreno (Polygon)** to the **Predio (1002) (Alphanumeric)**, the application doesn’t allow it and instead associates it with another **Predio** feature.

### Reproduction Steps:

1. Select **Terreno historico** in the interface.
2. Identify the **Predio** to find.
3. Find the **Predio(1002)**.
4. Open the form related to **Predio(1002)**.
5. Go to section **3- Terreno**.
6. Create a new **Terreno**.
7. Save the modifications in **Predio(1002)**.

### Expected behavior:

When I create a new **Terreno** from a **Predio**, I expect the new **Terreno** created to be associated with the **Predio** from which the edition began.

### Observed behavior:

When I create a new **Terreno** from a **Predio**, the new **Terreno** created is not associated with the **Predio** from which the edition began, the **Terreno** is associated with another **Predio**.

### Screenshots and GIFs

![Error_relación](https://user-images.githubusercontent.com/27906888/107826233-8e796b80-6d52-11eb-8af2-0f9e5aca39c2.gif)

**QGIS Project:**  [Project.zip](https://github.com/opengisch/QField/files/5974360/Project.zip)

**QField version:** "PR1680" (653e9c)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment] 2021-03-02 08:47
The problem isn't QField but a setting in your project.

The polygon layer, Terreno, has the following default value set for the predio field that's used in the relation:
![image](https://user-images.githubusercontent.com/1728657/109622013-3625d480-7b6e-11eb-8c00-125164077b95.png)

The `[x] apply default value on update` option being active means that when the feature is created, the value set by the relation (i.e. the T_id from the Predio layer) is overwritten by the default value expression (i.e. `aggregate('Predio', 'max', "T_id")`).

You can either uncheck the apply default value on update, which will leave the value set by the relation manager, or remove that default value expression altogether.

**Comment by nirvn** [comment] 2021-03-02 08:48
@jhonalex06 , sorry, I forgot to ping you on the reply. Are we good to close this issue?

**Comment by jhonalex06** [comment] 2021-03-02 14:47
Yes, you are right, in this case, it was the configuration, thanks @nirvn, and yes, we are good to close this issue.

**Comment by nirvn** [comment] 2021-03-02 14:51
Great. Thanks for testing you this upcoming feature.

**Closed by nirvn** 2021-03-02 14:51 UTC
