### ISSUE TITLE
CRS and database problems

### ISSUE THREAD

**Issue by pticv** [opengisch/QField#192] opened 2017-11-10 10:39 UTC
After last update, projects in CRS other than WGS84 (EPSG:4326) do not work. I have several projects on my SD card that did work just fine, until last update 0.10.3. After this update project can be opened, but layers do not show up. I used EPSG:3912. Error icon appears on top right corner. And many: 'Can't open database: unable to open database file' errors appear. I reprojected project and layers to ESPG:4326. Now layers do show up. But Error is persistent, despite having project and all layers in same CRS (WGS84).
I reinstalled application hoping to restore CRS database. That did not help. Putting any layer in CRS different from project CRS, makes it invisible.

### Observed behavior:

CRS conversion does not work

### Screenshots and GIFs

**QField version:** 0.10.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by walking-the-talk** [comment] 2017-11-14 13:49
Hi,
Have you tried opening the Qfield project on your desktop version of QGIS?

I have an old project using ESPG:27700 works on Qfield with a raster basemap
New project using ESPG:29903 doesn't display any layers whose underlying projection is ESPG:29903, but does show those that are WGS (ESPG:4326).

I had a look at the portable file .qgis on my desktop copy of QGIS and discovered that these layers are not reprojected. I noticed the following:

Desktop project .qgis:
      <layer_coordinate_transform_info>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="OR20171114111215569"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="**EPSG:29903**" srcDatumTransform="-1" destDatumTransform="-1" layerid="OS1840_D20171114104451369"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="gf20171114113722714"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="**EPSG:29903**" srcDatumTransform="-1" destDatumTransform="-1" layerid="OS1842_D20171114104451474"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="ss20171114113922169"/>
    </layer_coordinate_transform_info>
  
Portable project .qgis
   <layer_coordinate_transform_info>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="OR20171114111215569"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="**EPSG:4326**" srcDatumTransform="-1" destDatumTransform="-1" layerid="OS1840_D20171114104451369"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="gf20171114113722714"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="**EPSG:4326**" srcDatumTransform="-1" destDatumTransform="-1" layerid="OS1842_D20171114104451474"/>
      <layer_coordinate_transform destAuthId="EPSG:29903" srcAuthId="EPSG:4326" srcDatumTransform="-1" destDatumTransform="-1" layerid="ss20171114113922169"/>
    </layer_coordinate_transform_info>

So it looks like the sync plugin is using EPSG:4326 as the srcAuthId for all layers...

I manually changed those layers, but they are still not visible (on desktop or Qfield) - maybe there is another setting because 'zoom to layer'  on QGIS goes to the expected range, but the layer isn't visible.

Not sure if this helps, or is a different issue (maybe there's a problem with the plugin that I'm describing here?)

QGIS: 2.18.3 ; Qfield 0.10.3

**Comment by pticv** [comment] 2017-11-15 05:49
Project files open correctly in QGIS desktop. There are like 6 users that we used these same projects on QFiledd without problem. After last update none of the projects that we all used, does not work any more. I translated project and all layers to WGS84. After translation, project opens and one can see layers. But scale bar does not work. It is visible only in extreme zoom-out, and shows scale in pica.
Database error is present on all this devices constantly.
Then I used phone that never had QField or Qfield project on it. Installed latest version of Qfield and WGS84 project. There is no database error. Yet scale-bar still shows only in extreme zoom-out.
So obviously there is something wrong with CRS  OTF translation in last version of QField. Yet this error also damages database somehow.

**Comment by m-kuhn** [comment] 2017-11-15 07:01
@pticv Can you try to uninstall / reinstall qfield on one of the affected devices and see if that helps?
Make backups of the projects on the device first.

**Comment by pticv** [comment] 2017-11-15 07:35
I did that allready. I deinstalled QField. Restarted phone. Installed QField. No change. I can provide link to projects in question. But would not like to post it here in public.

**Comment by saemiw** [comment] 2017-11-16 09:13
I did check if 0.10.3 creates problems with our projects. Everything works fine, we use epsg:2056. We do not use SD cards though.

**Comment by pticv** [comment] 2017-11-17 07:49
Maybe there is something wrong with my projects. I followed instructions on creating those projects. And all projects worked under previous version, Yet none works under last version. It could be that new version is more restrictive on projects. 
But I tested with one very simple project. Project is in WGS84 with one vector layer that is also in WGS84. Project loads ok,. Layer is shown. But there is constant database error present. It is not my device. I personally tested on 6 devices. Same result, except on device that did not have any previous installation of Qfield. And all other users (6 of them) of projects report same errors. Different devices and Android versions.

**Comment by rwjdennis** [comment] 2017-11-22 23:30
I am having this problem as well. Just started on our new tablets (running Android 7.0) but not our old one (running Android 7.1.1).

In the log, I can see the 'Can't open database ...' as well as:
'CRS
Could not open CRS database /data/user/0/ch.opengis.qfield/files/share/resources/srs.db'

Sure enough, the folder is empty (I don't know how it got that way). I copied all the files in "/data/user/0/ch.opengis.qfield/files/share/resources/" from one of the working tablets onto the defective one, but it didn't fix the problem.

Both tablets are running 0.10.3, but there was an update recently and the version didn't change, so I don't know how much help that is.

Our project hasn't changed, except we've been having to modify it regularly due to file sizes and storage limitations on our devices (Matthias knows about this ...).

**Comment by mrtwister3142** [comment] 2017-11-23 18:02
I have the same issue with 0.10.3 (epsg:2056) and Android 7.0 but _only_ when storing my data on SD card.

**Comment by rwjdennis** [comment] 2017-11-23 22:09
To follow up @mrtwister3142 , we don't store the data on an SD card, but the directory we load the projects onto is 'sdcard'. This is emulated storage, since our devices aren't rooted.

In the directory where I can store my projects, I have no "srs.db" file where it *should* be. However, if in QField I try to open a project, I can navigate to '/data/user/0/ch.opengis.qfield/files/share/resources/'. In here, I have all the folders that should be there, but I still do not have "srs.db". I have the .xml files, but none of the .db files. I can't do a screenshot of this, but I think this might be part of the problem. That's really where it should be, and I still don't have it.

**Comment by pticv** [comment] 2017-11-25 15:46
I can confirm that if I move offending projects on /Android/data/ch.opengis.qfield/files in pohone's storage they work.

**Comment by pticv** [comment] 2017-11-25 15:46
I can confirm that if I move offending projects on /Android/data/ch.opengis.qfield/files in pohone's storage they work.

**Comment by saemiw** [comment] 2018-02-16 14:42
I have now the same issue: project with layers saved in epsg: 4326 and epsg:2056 don't show up but not in the right place. If I transform the layers both to epsg:2056 and disable on-the-fly everything works fine. So I think the issue ist that the latest qfield version (0.10.8_5) doesn't support OTF-Projection properly. It that possible? Is it possible to fix this as it worked neatly in earlier versions. 

By the way. My data area always saved on sd-cards.

**Comment by saemiw** [comment] 2018-02-20 10:08
Update on this issue. It really is software and no hardware problem. I have a project with layers in epsg:4326 and epsg:2056. I copied this project to the same device, once with qfield 0.10.8 and once with Qfield 0.10.4. On 0.10.4 the on the fly (OTF) projection works, on 0.10.8_5 it doesn't work. Could you please check that. I remember that there existed some problems with OTF projection in earlier versions of qfield.

**Comment by saemiw** [comment] 2018-02-20 14:13
I have all data in epsg:2056 and this is also the epsg of the qgis project. When I center to my current GPS position, QFIeld correctly shows my coordinates (but in epsg:4326 coordinates). At the same time it does not seem to project the data at the right place (I have a basemap in the data at my position). And I also get curious warning messages (by clicking on the alarm bell symbol in the top right corner).

This shows the situation before moving to my current position (by gps). If I move to current position I am out of my basemap (which should not be the case).
![screenshot_2018-02-20-14-53-34](https://user-images.githubusercontent.com/20398621/36428390-10aad024-1650-11e8-8260-627a69cc6ba2.png)

This shows the warning messages:
![screenshot_2018-02-20-14-53-38](https://user-images.githubusercontent.com/20398621/36428493-54e04b84-1650-11e8-9db9-e7ef1a04ee39.png)

**Comment by saemiw** [comment] 2018-02-22 17:05
@m-kuhn & @signedav I'd be glad for a short evaluation on this problem. Is it fixable quickly or something major? Because without this fix we won't be able to use 0.10.8, which would be a pitty. ;D

**Comment by m-kuhn** [comment] 2018-02-22 17:30
Not completely sure what's going on yet.

I notice that the "first run dialog" (progress bar unpacking the crs database, images etc.) is not being shown. This might be caused by the new build infrastructure, in particular this line might be a hint:
https://travis-ci.org/opengisch/QField/jobs/334696721#L669-L671
On the other hand, I think this issue also surfaced before the new build infrastructure.

I'll quickly try a simple fix for now.

**Comment by m-kuhn** [comment] 2018-02-22 18:26
@saemiw I'm sorry I'm unable to test myself right now. If you have any chance to install the apk here and report back, that would  be much appreciated. https://github.com/opengisch/QField/releases/tag/release-0.10.9

Thanks

**Comment by VxTedxV** [comment] 2018-02-22 19:48
Didn't work in 0.10.8_5... works in 0.10.9 ! Thanks !

**Comment by saemiw** [comment] 2018-02-23 07:24
Thanks @m-kuhn the projection seems to work now.

**Closed** 2018-03-15 14:58 UTC

**Comment by RatInTheField** [comment] 2020-11-11 15:42
Looks like this old ghost is back to haunt us!

I have a project running in "3.16 Hanover". I can create features and save them no issues. In the recent past, I have been able to export to QField and add/update records in the field. After updating (I think this started after 3.14) I am now getting errors in Qfield. A notification shows immediately on opening the project with the message "Using non-preferred coordinate operation between EPSG:4326 and EPSG:27700.......etc) (See screen shot). I normally work in EPSG:27700 and only use other CRS when I am forced to so am not sure why there is a reference to EPSG:4326.
When I try to create a new feature, Qfield takes so long to create the feature that the operator thinks the system has crashed and gives up. In reality, if the user is patient, the feature is created after about 2-5 mins!
I have sometimes been able to avoid this issue by creating a new project from scratch, but sine upgrading to 3.16, even this no longer works. Qfield shows the same errors however the project is created.

QGIS version 3.16
Qfield version1.7.6
![Screenshot_20201111-153645](https://user-images.githubusercontent.com/54633479/98832130-5a7d6a00-2434-11eb-817b-4a72c291c407.png)

**Comment by signedav** [comment] 2020-11-11 15:50
With what QField version it used to work @RatInTheField ?

**Comment by m-kuhn** [comment] 2020-11-11 15:54
Adding grids will be possible starting from https://github.com/opengisch/QField/pull/1385

Currently grids need to be placed manually on the device. A possible improvement would be to have them downloaded automatically when required.

**Comment by RatInTheField** [comment] 2020-11-11 17:07
@signedav , will check and get back to you

**Comment by RatInTheField** [comment] 2020-11-11 18:03
@signedav ,checked latest versions, results are
1.7.6 fails
1.7.5 fails
1.7.4 fails
1.7.3 fails
1.7.2 fails
1.7.0 OK

**Comment by nirvn** [comment] 2020-11-12 02:31
@RatInTheField , can you share your project here? You don't have to add datasets, the project file itself will do for now.

On why there's a mention of WGS84, you'd see it if you activate the GPS for eg

**Comment by RatInTheField** [comment] 2020-11-12 08:29
@nirvn,

[QField.zip](https://github.com/opengisch/QField/files/5529151/QField.zip)
This is the project file prepared for QField by QFieldSync 'Package for QField'

[QGIS.zip](https://github.com/opengisch/QField/files/5529163/QGIS.zip)
This is the project file as created in QGIS before prepping for QField

And finally, was your last comment complete? It seemed to stop abruptly??

**Comment by nirvn** [comment] 2020-11-12 08:44
@RatInTheField , can you check if these APKs improve the situation for you: https://github.com/opengisch/QField/pull/1385#issuecomment-725930472 -- note: you should still see a projection error message, but I suspect the freeze might be gone.

**Comment by RatInTheField** [comment] 2020-11-12 11:52
@nirvn, I have tested the new apk. Mixed results. Notification does not appear. Features are being saved in about 15 seconds.

I am not too familiar with grids. Can you help me with what grids I should have loaded and where they should be stored in QField? Perhaps you could direct me to where I can read up on them?
Thanks.

**Comment by nirvn** [comment] 2020-11-12 11:58
From 2-3 minutes to 15 seconds, I call that a great improvement ;) 

You should get one message now, with an hyperlink to the missing grid in your message log panel (that you open by clicking the dark gray bubble below the search button).

Download that grid file and put it in your device's root /QField/proj/ directory.

**Comment by nirvn** [comment] 2020-11-12 12:00
![Screenshot_20201112-190025_QField Beta 1385](https://user-images.githubusercontent.com/1728657/98937681-59723880-2519-11eb-85fd-ccbaa73c4726.jpg)

**Comment by RatInTheField** [comment] 2020-11-12 12:36
![Screenshot_20201112-123127](https://user-images.githubusercontent.com/54633479/98940637-3036b580-24e3-11eb-9af3-56e10d3c5189.png)
I think the grids are now setup. 
I have to accept that 15-20 seconds is a big improvement, but it is still not almost instant as it used to be. Is there scope for further improvement or have we achieved as much as is practical at the moment?

**Comment by nirvn** [comment] 2020-11-12 13:10
@RatInTheField , you have copied the grids in the right place, however you should not assign any vertical grid, keep it to no grid.

15sec remains an abnormal time. Can you share the dataset(s) you are using to insert features that take that long to save?

**Comment by RatInTheField** [comment] 2020-11-12 14:27
@nirvn , these are the data collection layers. Both are affected by the issue.
[HolcombeMoor_Line.zip](https://github.com/opengisch/QField/files/5531193/HolcombeMoor_Line.zip)
[HolcombeMoor.zip](https://github.com/opengisch/QField/files/5531163/HolcombeMoor.zip)

**Comment by nirvn** [comment] 2020-11-15 10:09
@RatInTheField , can you confirm that the APKs in PR #1418 have fixed the 15 second freeze when adding features to your project?

**Comment by RatInTheField** [comment] 2020-11-15 19:49
EPIC radical improvement!!!

Many thanks for your impressive and speedy response!

Early tests show indicate an almost instant response when saving a new
feature.

I will continue to test more fully and update you with the results.

Thanks again,

Roland

**Comment by RatInTheField** [comment] 2020-11-16 08:15
I have now tested point and line create, delete and vortex tool. All seems OK and works within reasonable time frame.

One question, labels seem to lag behind features with the spinning cursor showing for some seconds after the feature is drawn before the label is drawn, but this is a small issue for me!!

**Comment by RatInTheField** [comment] 2020-11-16 08:16
Latest test used https://download.opengis.ch/qfield/ci-builds/qfield-dev-1418-302214ce0efcbf5c96a5eaca2e8e5cffa5d929d0-arm64_v8a.apk.
Results still good.
