### ISSUE TITLE
Child features cannot be created when mandatory field is not fulfilled

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#3775] opened 2022-12-28 13:09 UTC
### Describe the issue
I want to record many species and have enabled project relations. Standing in the field the user can observe and record many species (and images) at the same spot. Some fields in the form are mandatory.

In QGIS this works fine: I can record species whenever I want (mandatory fields can be entered AFTER species have been recorded).
In QField I must enter all mandatory fields BEFORE species can be entered?

Example: attribute feltarbeider is mandatory and not entered yet and species may not be entered (the pluss-icon is gray and unavailable) in QField, but available in QGIS.
<img src="https://user-images.githubusercontent.com/10632163/209816270-15f93e70-45dc-4132-ba9e-d06087713d29.png" width=35%/>

<img src="https://user-images.githubusercontent.com/10632163/209816309-702aa0be-333f-4bfc-a70f-e32d3cf98bb3.png" width=35%/>

<img src="https://user-images.githubusercontent.com/10632163/209812827-95b3dbb3-105b-4557-9191-6409bb0cfe95.jpg" width=70%/>
feltarbeider is entered and I may add species.
<img src="https://user-images.githubusercontent.com/10632163/209812955-0e850f82-ae10-427c-beea-7b48ee53d7b0.jpg" width=70%/>

In the latter case, I may save the recordings even though no species is entered. The idea with ferdig (eng. finished) checkbox (that I want to be mandatory) is that this may work as a "reminder" (remember to add species before saving).

### Reproduction steps
Unzip [karplante.zip](https://github.com/opengisch/QField/files/10314042/karplante.zip) and open project in QGIS and prepare with QField (offline editing on arter, oversikt, artsdekning and artsbilder) and transfer with cable to tablet. Open project on tablet and show the layers and set arter in digitize mode

###Expected behavior
Expected same behavior in QField as in QGIS: I may enter species "whenever" I want regardless mandatory fields are empty/not set or not.

### Observed behavior
See description and images above.

### Desktop (please complete the following information)

- OS: Windows 10
- QGIS Version 3.28.1
- QFieldSync Version 4.2.0

### Mobile (please complete the following information)

- Device: Samsung Tab Active3
- OS: Android 13
- QField version: 2.5.7

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment] 2023-01-03 22:05
This is intentional behavior IIRC. qfield wants to be sure children are only created for existing parents and therefore to save the parent before creating the children.
@signedav do you remember what would be needed to change that?

**Comment by signedav** [comment] 2023-01-04 05:51
I think you are right. The children can only be added and saved when the parent exists. So the parent is saved on pressing the + (what is only possible when the parent's contstraints are fulfilled). When we cancel adding the parent after adding the children, the children will be deleted. An unsolved part is AFAIK the case where the FK value (on the parent) changes after adding the children: here we will get orphans (but same in QGIS I guess).
I think the main reason we did it like this (disabling on having no parent) was because we would have a mess when the FK value (on the parent) does not exist yet. FID is often used even when it's not suggested but as well we have this problem on every primary key. 
So i guess the sollution would be to have a workflow to change the childrens FK when it changes on the parent (or do you see other parts @m-kuhn )

**Comment by m-kuhn** [comment] 2023-01-04 06:09
Adding support for changing pk's sounds like an approach.
Or otherwise we could check if the pk is not null and in this case allow adding children without saving? It's slightly less predictable when a save will happen in this case though.

**Comment by 9ls1** [comment] 2023-01-04 08:05
Thanks for your comments. Realize that it is not quite straight forward, but quite a complex affair. (One idea I had was to make the species mandatory: Not possible to save unless at least one species ((one child)) is selected. I didn't succeed.) I want to log the time spend on observations. When the form appears start time is recorded (`now()`) and when finished the idea is to tick the finish checkbox. When checked, end time will be recorded. Thereby, the time spend will be calculated (end time - start time). When the user has to check finish before adding the species the time spend gets incorrect.

**Comment by m-kuhn** [comment] 2023-01-04 08:32
"At least one child" indeed is not possible at the moment.
"Time spent on form" is a tricky topic in itself, that needs a deeper look into possibilities and options.

**Comment by 9ls1** [comment] 2023-01-04 09:18
Thanks for your comments/replies. For now I will remind the users to stay sober when collecting data in the field to increase the chances of remembering to record species before saving. 😁

**Comment by m-kuhn** [comment] 2023-01-04 09:39
> "At least one child" indeed is not possible at the moment.

Actually, it might be possible with aggregates, but the problem is that constraint validity is not rechecked after adding a child, so partially possible but as far as I can tell not reliably.

**Comment by nirvn** [comment] 2024-03-22 05:04
@9ls1 , good news, this has been fixed in latest QField 3.2.0, hope you enjoy the functionality!

**Closed by nirvn** 2024-03-22 05:04 UTC

**Comment by 9ls1** [comment] 2024-03-22 07:57
Great, great news! Thank you!
