### ISSUE TITLE
Value relation: Possible to combine multiple selections and the completer?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#3046] opened 2022-07-04 08:57 UTC
### Describe the issue
The **value relation widget** works quite nicely. This widget gives me the opportunity to "Allow multiple selections" which works fine on shorter lists, but not very convenient with 400 list-items. Also "Use completer" works fine, but only allowing _one_ selection.

Is it possible to combine multiple selections _and_ the completer?
E.g. start typing the specie, choose from the drop down list, start typing a new specie and choose from the list and continue until all species in that particular location are recorded.

### Desktop (please complete the following information)
 - OS:  Windows 10
 - QGIS Version 3.26
 - QFieldSync Version 4.1.1.

### Mobile (please complete the following information)
 - Device: Samsung
 - OS: Android 10
 - QField version: 2.1.4

**Comment by suricactus** [comment] 2022-07-04 10:29
Duplicate of https://github.com/opengisch/QField/issues/1436 .

If you want to speed-up the implementation of this feature, drop us an email at info [at] opengis.ch for an offer.

**Closed** 2022-07-04 10:30 UTC

**Comment by 9ls1** [comment] 2022-07-04 10:52
Ah, sorry for the duplicate. Hm, I tried to search to refind the issue before posting my own (I was quite sure I had been seeing it, but my mistake was searching for value relation widget and not just relation widget...)
Anyway, I'll look for some funding.

**Comment by 9ls1** [comment] 2022-08-25 10:29
Something like this would be nice: [https://merginmaps.com/docs/layer/settingup_forms/#value-map](https://merginmaps.com/docs/layer/settingup_forms/#value-map).

In addition: Sometimes the list (csv-file) is incomplete (e.g. you observe a species not listed in the original csv-file. In those cases it would be nice to write in the species and then click Add to add the new species to the list. Next time this species is spotted, you can choose it from the now extended list. (I know I can add new item to the list by editing the list layer, but if I could do it "on-the-fly" while choosing species for my new feature, it would save me some clicking during field work.)
