### ISSUE TITLE
Qfield 1.6 crashes on Android 7

### ISSUE THREAD

**Issue by giocoro** [opengisch/QField#1121] opened 2020-07-07 09:38 UTC
The new realese keeps crashing.

Qfield 1.6
Samsung Galaxy J2.

**Comment by m-kuhn** [comment] 2020-07-07 11:02
Thanks for reporting.
This is a duplicate of https://github.com/opengisch/QField/issues/1114 which has been fixed already for upcoming 1.6.1

**Closed by m-kuhn** 2020-07-07 11:02 UTC
