### ISSUE TITLE
Accessing location info while background

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#958] opened 2020-04-18 08:01 UTC
I need more investigations but I wonder if we can improve that. QField needs only location info while in use. Still it requests the user for access during running in background...
![Screenshot_20200418-095713_Permission controller](https://user-images.githubusercontent.com/28384354/79631801-739e9080-815b-11ea-8c00-e6eec38f6bbb.jpg)

QField Master and Android 10

**Comment by m-kuhn** [comment] 2020-04-20 14:48
If possible at all, only asking for foreground should be the way to go.

I assum complete background tracking will be hard to implement.

Something to improve UX by "pseudo background" (i.e. to use other apps while tracking, but cannot be used to save battery) https://developer.android.com/guide/topics/ui/picture-in-picture

**Comment by signedav** [comment] 2020-04-20 19:30
The problem is that it appears like QField would do something in the background what it doesn't...

**Comment by alsper78** [comment] 2020-06-26 16:48
QField can work in background, for example to track a path, but many Android devices stop the GPS/GNSS receiver when the app using geolocation is in background or the display is off. So even if the app is working in background it doesn’t receive geolocation data because the GPS/GNSS receiver is off. To solve this problem there are many apps to hold the GPS/GNSS active.
For example I use the app “GPS Connected” with QField set to work in background and battery save option disabled. I tested for only 10 minutes but in this way QField seems to be able to register track even when it is in background or display is off.

**Comment by monticola2** [comment] 2021-04-13 10:52
> 
> 
> QField can work in background, for example to track a path, but many Android devices stop the GPS/GNSS receiver when the app using geolocation is in background or the display is off. So even if the app is working in background it doesn’t receive geolocation data because the GPS/GNSS receiver is off. To solve this problem there are many apps to hold the GPS/GNSS active.
> For example I use the app “GPS Connected” with QField set to work in background and battery save option disabled. I tested for only 10 minutes but in this way QField seems to be able to register track even when it is in background or display is off.

I cannot reproduce this. I use "GPS Connected", too, to keep GPS running in the background as it helps keeping the fix in difficult terrain. I would like to use tracking lines to see the area I have covered in my surveys. Tracking with QField works just fine until I turn off the display. QField then no longer creates new vertices at the given time intervals until I turn the display back on. Then it simply connects the last point with the current position.
I have tested this with two phones and different projects. I have also turned off all energy saving options for QField in my current phone. Is there anything I am missing?

**Comment by nirvn** [comment] 2021-10-02 08:45
Closing this in favor of an enhancement filed in another issue.

**Closed by nirvn** 2021-10-02 08:45 UTC
Labels: INPUT
