### ISSUE TITLE
Tracking stops any time QField isn't active app

### ISSUE THREAD

**Issue by AK-survey** [opengisch/QField#4133] opened 2023-04-07 23:55 UTC
### Describe the issue
I manage a few field devices for my company and really want to like QField. However, we have had an issue where the tracking to a layer stops as soon as the app is no longer the active app and won't restart when QField becomes the active app again. This is happening across a wide variety of devices, older and newer, Android (Samsung), iPad, iPhone, it doesn't seem to matter. We're all up to date on the latest version and don't use any external GPS receivers with QField.

### Reproduction steps
1) Turn on tracking as specified in https://docs.qfield.org/how-to/tracking/?h=track.
2) Screen turns off automatically **OR** another app is activated **OR** home button is pushed **OR** screen in locked manually
3) When re-entering QField, tracking has turned off. Sometimes, the track skips to the current location, and sometimes tracking is turned off entirely, forcing the user to restart the tracking and creating a new feature

### Expected behavior
1) Turn on tracking as specified in https://docs.qfield.org/how-to/tracking/?h=track.
2) Tracking ONLY turns off when the app is specifically closed OR tracking is turned off as specified in the above help document.

### Observed behavior
See reproduction steps

### Desktop (please complete the following information)
N/A

### Mobile (please complete the following information)
 - Device: Samsung Tab Active 3, iPhone SE (Gen1), iPad Mini, iPad Pro, Handheld Nautiz X9
 - OS: Android 10, 13; iOS 12.5.7, 15.7.3
 - QField version: 2.7.1, been going on for several versions previous also.

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes].
* The Location settings options for QField on all devices are Only while using the app, Ask every time, and Don't allow. This may be fixed by allowing for an option to let QField use location all the time.

QFieldCloud not used by our company.

I'm new to GitHub, so please let me know if this belongs in the Bugs section rather than the Issues section.

**Comment by nirvn** [comment] 2023-04-08 09:37
Duplicate of https://github.com/opengisch/QField/issues/1841 -- it's an enhancement that is not implemented yet. It involves quite a lot of work, unlikely to happen unless funding supports the effort.

**Closed by nirvn** 2023-04-08 09:37 UTC
