### ISSUE TITLE
Activating localisation services causes map to disappear

### ISSUE THREAD

**Issue by qnmai** [opengisch/QField#124] opened 2017-04-08 01:46 UTC
Map disappears when localisation button is activated.

### Reproduction Steps:

1. Activate localisation on device (Samsung Galaxy S7 Android 7.0)
2. Open QField (map successful appears)
3. Activate localisation in application via button
4. Map disappears

### Expected behavior:

1. Activate localisation on device (Samsung Galaxy S7 Android 7.0)
2. Open QField (map successful appears)
3. Activate localisation in application via button

### Observed behavior:

1. Activate localisation on device (Samsung Galaxy S7 Android 7.0)
2. Open QField (map successful appears)
3. Activate localisation in application via button
4. Point to indicate location appears on screen, but map disappears displaying blank screen

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

When opening project--map appears successfully:

![screenshot_20170407-145633](https://cloud.githubusercontent.com/assets/20867587/24824552/0ccd9f88-1ba9-11e7-86cb-378fb97f3fc9.png)

Activating localisation causes map to disappear--coordinates are correct:

![screenshot_20170407-153123](https://cloud.githubusercontent.com/assets/20867587/24824563/2ec8408e-1ba9-11e7-9def-7cc21fb265a3.png)

The log shows this error:

![screenshot_20170407-145801](https://cloud.githubusercontent.com/assets/20867587/24824561/1a555858-1ba9-11e7-8cbd-988313fdae13.png)

**QField version:** 0.8.8

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No (first time using)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: TBA

**Comment by m-kuhn** [comment] 2017-04-08 06:51
Can you test the latest release from here https://github.com/opengisch/QField/releases or switch to the beta on G play.

**Comment by donkey12345** [comment] 2017-04-10 01:30
Is it possible that the coordinates setting in qgis.db does not exist and that the crs.db file is missing.

**Comment by niunani** [comment] 2017-04-10 06:31
I do notice that this pathname does not exist on my device. How can I acquire this file and how can I modify the expected pathname to match my device?

I will update when I have tested the latest release.

**Comment by m-kuhn** [comment] 2017-04-10 09:36
It's very well possible, that the CRS warning and the observed behavior are related.

I could reproduce (the warning) on an S7 edge with Android 7 and QField 0.9.10. It *might* be related to the Android version.

**Comment by niunani** [comment] 2017-04-11 19:25
I have installed the latest release 0.9.10 and the problem persists.

Do you have any suggestions for resolving the CRS warning?

**Comment by giedrioks26** [comment] 2017-07-25 06:50
I uninstall QField (not update) and reinstalled 9.10. Now I'm working fine.
Before performing this step, you must safely transfer data from external SD. Because the Android system will delete the /Android/data/ch.opengis.qfield directory. This is important if you keep the data in the External sd card.

**Comment by signedav** [comment] 2018-03-26 06:40
Can you confirm this as solved as well @niunani ?
Thanks for your help.

**Closed** 2019-11-18 16:40 UTC
