### ISSUE TITLE
@snapping_results with several layers in QField for Windows

### ISSUE THREAD

**Issue by tproduit** [opengisch/QField#5661] opened 2024-09-17 10:45 UTC
### Describe the issue
The expression `z(geometry(get_feature_by_id('layer_id',  map_get(array_first(@snapping_results), 'feature_id'))))` doesn't work in QField for windows

### Reproduction steps
1. Open the linked project
2. Add a new feature in the layer "get_z_from_reference" by snapping it to the layer "reference"
3. The field "get_z" should be filled with the height of the snapped point

### Expected behavior
The field "get_z" should be filled with the height of the point within the layer "reference"

### Observed behavior
The field is filled in QGIS Desktop and QField for Android. The field is not filled in QField for Windows. 

If it can help, if the project contains only the layers "get_z_from_reference" and "reference", there is no problem. The problem occurs only once that a third layer is added ("reference 2").

### QGIS (please complete the following information)
 - OS: Windows
 - QGIS Version: 3.24
 - QFieldSync Version: not used

### QField (please complete the following information)
 - OS: Windows
 - QField version: 3.4.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[qfield_snapping.zip](https://github.com/user-attachments/files/17025305/qfield_snapping.zip)

**Comment by nirvn** [comment] 2024-11-12 05:05
@tproduit , thanks for the report and the test project. I _think_ this issue will be fixed by the PR we just opened. From what I could see here, it is not really that snapping wouldn't work on Windows, but rather than the mouse interface would often mean that the coordinate cursor would not end up snapping to anything upon project creation.

In roughly 30 minutes, you should have a windows test build to confirm the the problem is fixed for you here: https://github.com/opengisch/QField/actions/runs/11791043372/job/32842465780?pr=5808

**Closed** 2024-11-14 05:59 UTC
