### ISSUE TITLE
QGS or QGZ does not exist

### ISSUE THREAD

**Issue by nicolasmcfadden** [opengisch/QField#390] opened 2018-11-14 15:16 UTC
Can't open qgs or qgz projects since 0.11.10  update

### Reproduction Steps:

1. Open QField
2. Go to Open Project
3. Navigate to project file location and select

### Expected behavior:

Opens the projects

### Observed behavior:

Doesn't open qgs project and gives me an error message : "... project.qgs doesn't exist"
And with a qgz files gives two messages: 

1. "Error zip file does not exist"

2. "... project.qgz doesn't exist"

### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/27243743/48491289-46e49c00-e838-11e8-873f-c47561e37af8.png)

**QField version:** 0.11.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by marioba** [comment] 2018-11-15 13:54
Thank you @nicolasmcfadden for reporting this problem.
Qgz files are not yet supported by Qfield.

For the qgs file, unfortunately I can not reproduce the problem on my device, but it probably depends on the transformation of the files's URI in the path that Qfield needs.

Could you tell me what is the correct path of the qgs file you are trying to open? You can see it from "My Files" by selecting the file -> and then "details".

**Comment by nicolasmcfadden** [comment] 2018-11-15 14:05
Hello marioba,
it's my pleasure to help the project! Ok the .qgz is now obvious.

As for the .qgs, here's the path:

![image](https://user-images.githubusercontent.com/27243743/48557718-9094bb80-e8f8-11e8-9b03-603ed50c7692.png)

**Comment by nicolasmcfadden** [comment] 2018-11-20 06:47
Hello Marioba,
Thank you for looking into it so actively!
I now get the following message:

![image](https://user-images.githubusercontent.com/27243743/48756174-16be5280-eca9-11e8-88ca-008fc4814586.png)

Maybe I should point out that my projects are not on an SD card but on the main storage of the phone.

**Comment by Isaacson33** [comment] 2019-01-09 17:58
Getting the same problem with files on main storage and of Google Drive with latest version 1.0.0-rc1. Cannot open any files. Tries with qgz and qgs files, just get the same 'File does not exist' error.

**Comment by Koalha** [comment] 2019-01-14 18:58
Same here, I can't open .qgs projects from internal memory nor from SD. QField 1.0.0-rc1 gives a "File does not exist" -error. My device is a Nokia 7 plus, Android 9.

**Comment by mbernasocchi** [comment] 2019-01-31 10:44
@3nids should this be closed?

**Comment by nicolasmcfadden** [comment] 2019-01-31 11:07
@mbernasocchi Thanks for all the development work. I've downloaded the rc3 and it seems to be working! However the QField projects tab, doesn't find any project ("Can't load any content at the momenbt"), is this normal? And .qgz, don't work for now, right?

**Comment by mbernasocchi** [comment] 2019-02-01 12:14
hi @nicolasmcfadden a fix has been added to master, please test the apk available at:
https://github.com/opengisch/QField/commit/42aec179a8a1911b77e9f10dc23059d3097a57bc

**Comment by marioba** [comment] 2019-02-02 07:02
Hi @janneke-qgis,  
Thank you for the report and for the availability.

If you can, I ask you to try the apk [here](https://github.com/opengisch/QField/pull/471) and see if it changes something or if at least the error message says something more useful.

Thanks

**Comment by janneke-qgis** [comment] 2019-02-02 08:15
Thanks! I have downloaded the apk you mentioned and installed it. When opening Qfield it initially still referred to the project that I had managed to open earlier using the workaround. Not sure if that is to be expected. Going to Open Project>phone>open the .qgis file still gives me the error message "QField File does not exist" (in the log window). Is there another place where I might get more extensive log messages? The workaround by choosing "open project" the the option QField still works.

**Comment by marioba** [comment] 2019-02-02 14:07
Thanks for the test.
I have prepared a new test version. It should be loaded [here](https://github.com/opengisch/QField/pull/471) in a few minutes.

In order to be able to show the log messages, I know two possibilities:
- Connect the device to the computer and show the logs with the adb tool https://developer.android.com/studio/command-line/adb for example in this way `adb logcat | grep "QField Documents Provider"`.
- There are apps that allow you to see the logs directly on the device but require root access to the device. (e.g. Logcat Viewer) https://play.google.com/store/apps/details?id=net.sinoka.apps.logcatviewer

The logs concerning file upload start with `QField Documents Provider`.

Thank you.

**Comment by janneke-qgis** [comment] 2019-02-03 16:32
Thanks! Will try tomorrow morning, was without power the whole day. I have adb so I'll give that a go too.

**Comment by marioba** [comment] 2019-02-04 07:34
This works for me, great! Now I need to figure out how to work with the application :-)

_Originally posted by @janneke-qgis in https://github.com/opengisch/QField/pull/471#issuecomment-460146964_

**Comment by marioba** [comment] 2019-02-04 07:34
That's good. 
@janneke-qgis If you could, would you still send me the log please? It might help me to understand the differences in file management on different devices and improve the file selector.

**Comment by janneke-qgis** [comment] 2019-02-04 07:57
Could you give me slightly more dumbed down instructions for windows 10? I have adb in the cmd window, the phone is in debug mode but grep is not recognised as a command - because it's linux? Or because I first need to do something else?

**Comment by mbernasocchi** [comment] 2019-02-04 13:33
grep is a linux tool that seaches strings.
you can type `adb logcat` and copy paste the log to a file and then search in it or do 

`adb logcat > mylog.txt`
or have a look at:
https://stackoverflow.com/questions/1416241/is-there-a-pattern-matching-utility-like-grep-in-windows

**Comment by janneke-qgis** [comment] 2019-02-04 17:32
Ok, I got something - 
[mylog1.txt](https://github.com/opengisch/QField/files/2829132/mylog1.txt)

**Comment by janneke-qgis** [comment] 2019-02-04 17:32
it looks messy to me - can you work with this?

**Comment by marioba** [comment] 2019-02-05 06:43
@janneke-qgis Thank you very much. That's exactly what I needed. 
I'm probably preparing a new test version today, and if that's okay for you, I'd ask you to do another test.

**Comment by janneke-qgis** [comment] 2019-02-05 06:46
Sure!

**Comment by Xulzer** [comment] 2019-02-11 15:07
Thanks Marioba. I was looking in many forums how to deal with the no file problem, tried with your apk and worked perfect now.

**Comment by marioba** [comment] 2019-02-12 07:39
I'm glad it works and it was very useful to understand some mechanisms of Android. However, the solution adopted in this testing branch is not usable in a production context because of some bad hacks that can potentially create problems in some situations, because the file selector always shows the icons of providers that can not currently work with QField, such as Google Drive, Downloads, etc..., and because it's really in opposition to some of the Android's best practices.
The File selector has been rewritten differently to try to eliminate the problems mentioned and you can find it here: #476. 
I close this issue. I thank everyone who helped implement/debug the various versions and I invite you to try the new file selector.

**Closed by marioba** 2019-02-12 07:39 UTC

**Comment by meyerlor** [comment] 2021-05-25 13:27
this exact errormessage appears in the Message Log when using the current Windows-dev release
