### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by tveinot** [opengisch/QField#161] opened 2017-08-30 10:51 UTC
Sometimes form fields disappear when collecting data.

### Reproduction Steps:

1. In QGIS create a project for QField
2. Setup forms with controlled visibility panels and tabs linked to a primary input field 
3. In edit mode begin adding features to open forms

### Expected behavior:

Expecting the forms to work as built in QGIS with certain tabs/group boxes only being visible as defined by the visibility expression

### Observed behavior:

Sometimes the form will open fine, other times it will have errors such as; Misnamed Fields, Duplicates, Missing Fields, Photo Field will switch to Text Input. 

### Screenshots and GIFs
View of my Visibility Expression in QGIS
![image](https://user-images.githubusercontent.com/26797978/29869105-f35a0638-8d57-11e7-96e4-cc0934e709a3.png)

My form layout
![image](https://user-images.githubusercontent.com/26797978/29869156-29a18d88-8d58-11e7-8ae9-51fa4e82ecfe.png)

You will notice 2 things a tab named "NA" and several fields duplicated across multiple tabs. I have found that using a blank tab as the default (i.e. "NA") the other tabs have a better chance of loading fully. My first attempt had all the common fields in the "Basic Info" tab and only feature specific fields in the other tabs. This setup caused the Photo Field to switch to a Default Text Input as oppose to a Camera Button.
I am finding this difficult to explain fully so I am attaching 2 files, My QGIS Project and the shapefile I am collecting to.

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

10.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [No] A little of both actually, it will always happen on the "Garbage Cans" Tab. If you in the form select asset type "Street Lights" Then switch it to "Garbage Cans" the "Garbage Cans" form will be missing fields. If you select "Garbage Cans" first it will be fine. My older versions had issues across all forms; but I was using group boxes and not tabs. Unfortunately I did not retain the older versions to show the progression of the initial issues and how I worked around them. 
* Problem happens with all files and projects, not only some files or projects: [Yes] On 2 I have done so far but those 2 were both developments of this data collection form.

[asset_collection.zip](https://github.com/opengisch/QField/files/1263330/asset_collection.zip)

**Comment by signedav** [comment] 2019-11-18 15:34
Hi @tveinot 
I cannot reproduce. Even when I remove the "NA" tab from the project the other tabs are loaded properly. Can you test with a later release? Thanks.

**Comment by signedav** [comment] 2019-12-04 11:32
Since I did not received a feedback I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:

**Closed by signedav** 2019-12-04 11:32 UTC
Labels: BUG, feedback
