### ISSUE TITLE
Geometry digitizing when adding a child with starting with geometry form

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#1679] opened 2021-02-10 16:13 UTC
When I start editing from a geometry form and from it I access an alphanumeric form, which in turn allows me to create a new geometry, the application is not able to create the latter geometry.

### **Reproduction Steps:**

1. Select **Terreno historico** in the interface.
2. Open the form related with **Identificador único de operación**.
3. Select **3- Terreno**.
4. Try to add a new **Terreno** in relation **Listado de terrenos del predio**.

### **Expected behavior:**

When I start editing from geometry form and go to alphanumeric form, I expect that I could create a new geometry from this form.

### **Observed behavior:**

When I start editing from geometry form and go to alphanumeric form, I can't create a new geometry from this form.

### **Screenshots and GIFs**

![support_child_geo_alpha_geo](https://user-images.githubusercontent.com/27906888/107537071-7fe35680-6b90-11eb-934f-79d6f7d7b19a.gif)

**QGIS Project**:  [Project.zip](https://github.com/opengisch/QField/files/5959563/Project.zip)

**QField version:** "master-dev" (bd1c2e)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment] 2021-02-10 16:44
That's fixed on most recent master builds. You can grap and test APKs in commits' comment.

Thanks for testing this new feature.

**Comment by jhonalex06** [comment] 2021-02-10 21:06
> That's fixed on most recent master builds. You can grap and test APKs in commits' comment.
> 
> Thanks for testing this new feature.

yes, I can see the implementation in the master (758428c), but when I tested with the project in the last comment, the application crashed.

Could I re-open this issue or shall I open a new one with the details?

Thanks

**Comment by nirvn** [comment] 2021-02-11 00:15
Can you type in steps to reproduce the crash here @jhonalex06 ?

**Comment by jhonalex06** [comment] 2021-02-11 00:23
Yes, But the steps are the same @nirvn, when I tried to create a **Terreno**, The application crashed.

**Comment by nirvn** [comment] 2021-02-11 00:51
@jhonalex06 , it crashes on first child feature addition or second one?

**Comment by nirvn** [comment] 2021-02-11 00:53
It works for me here, strangely enough.

**Comment by nirvn** [comment] 2021-02-11 01:56
@jhonalex06 , can you try APKs from this PR when they become available in ~10min or so: https://github.com/opengisch/QField/pull/1680 -- it doesn't crash for me here.

If it still crashes for you, can you make a screencast of it?

**Comment by jhonalex06** [comment] 2021-02-11 13:56
> @jhonalex06 , can you try APKs from this PR when they become available in ~10min or so: #1680 -- it doesn't crash for me here.
> 
> If it still crashes for you, can you make a screencast of it?

@nirvn , I tested with #1680 and It works in the first child feature but in the second it crashed.

The screencast of it:

![Error_crashed_geo_alpha_geo](https://user-images.githubusercontent.com/27906888/107645254-7b797500-6c46-11eb-91c6-ef5b2ab9c613.gif)

Thanks and sorry for not answering yesterday.

**Comment by nirvn** [comment] 2021-02-13 06:50
@jhonalex06 , can you give this PR a try and check if the crash is gone: https://github.com/opengisch/QField/pull/1688 ?

**Comment by jhonalex06** [comment] 2021-02-16 14:48
> @jhonalex06 , can you give this PR a try and check if the crash is gone: #1688 ?

Thanks for the implementation, This PR #1688 works excellent.

**Closed** 2021-02-17 00:08 UTC
