### ISSUE TITLE
Crash when photo added

### ISSUE THREAD

**Issue by Christophe55** [opengisch/QField#53] opened 2016-07-16 07:41 UTC
Qfield crash when I add a photo on android 4.4 (samsung galaxy tab 2) and android 6.0.1 (Nexus 5).
Qfield crash when I validate the photo.

**Comment by m-kuhn** [comment] 2016-07-16 07:55
Does your device offer to send a report after it happens?

**Comment by Christophe55** [comment] 2016-07-16 08:39
Yes, Android propose me to send a report, but i don't know if it'is an android report for google or a repport for qfield.

I already send a report.

**Comment by m-kuhn** [comment] 2016-07-16 13:36
Note to self:
```

Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: java_class == null'
    r0 00000000  r1 00005fdb  r2 00000006  r3 b6fc1b7c
    r4 b6fc1b84  r5 b6fc1b34  r6 0000000b  r7 0000010c
    r8 b4cff378  r9 b4d6a800  sl 00000001  fp 00000001
    ip 00000006  sp be82e838  lr b6d30b61  pc b6d32f50  cpsr 40070010

backtrace:
    #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
    #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
    #02 pc 0001c30f  /system/lib/libc.so (raise+10)
    #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 000174ac  /system/lib/libc.so (abort+4)
    #05 pc 00333971  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
    #06 pc 000f45fb  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
    #07 pc 0025aa4f  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1550)
    #08 pc 0025ae7b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+74)
    #09 pc 00283ea9  /system/lib/libart.so (_ZN3art3JNI11GetMethodIDEP7_JNIEnvP7_jclassPKcS6_+672)
    #10 pc 001b9391  /data/app/ch.opengis.qfield-2/lib/arm/libQt5Core.so
    #11 pc 001b98f9  /data/app/ch.opengis.qfield-2/lib/arm/libQt5Core.so (_ZNK17QJNIObjectPrivate11callMethodVIiEET_PKcS3_St9__va_list+40)
    #12 pc 00008ae3  /data/app/ch.opengis.qfield-2/lib/arm/libQt5AndroidExtras.so (_ZNK17QAndroidJniObject10callMethodIiEET_PKcS3_z+14)
    #13 pc 00025127  /data/app/ch.opengis.qfield-2/lib/arm/libqfield.so (_ZN20AndroidPictureSource20handleActivityResultEiiRK17QAndroidJniObject+362)
    #14 pc 0000a3df  /data/app/ch.opengis.qfield-2/lib/arm/libQt5AndroidExtras.so
    #15 pc 001b5903  /data/app/ch.opengis.qfield-2/lib/arm/libQt5Core.so (_ZN16QtAndroidPrivate20handleActivityResultEiiP8_jobject+82)
    #16 pc 0007427d  /data/app/ch.opengis.qfield-2/oat/arm/base.odex (offset 0x4f000)
```

**Comment by mikelayesta** [comment] 2016-10-20 15:28
Hello,

QField crashes when I add a photo on Android 5.1 (Archros 101c Copper) and Android 5.0 (LG-D855).

Thank you,

Mikel

**Comment by m-kuhn** [comment] 2016-10-20 15:30
This seems to happen on certain devices only. Unfortunately we cannot reproduce it with a device we have here. If anyone can help us to get our hands onto an affected device, that will help a lot already.

**Comment by raymondnijssen** [comment] 2016-11-08 14:10
Same here on HTC One S, cyanogenmod 12.1, android 5.1.1

**Comment by ludovico85** [comment] 2016-12-29 18:29
Hello! I get the same crash when when I validate the photo on Huawei p9 lite (Android 6.0) and Samsung Galaxy Tab 3 (GT-P5200 with Android 4.4.2)

**Comment by pedrogeo** [comment] 2017-01-31 08:12
Hello,

I have the same problem on Huawei p8 lite (Android 6). When I take a photo from the form, it works but when I save the photo I come back on the welcome screen of Android. And I can't save the point in Qfield.

**Comment by mbernasocchi** [comment] 2017-02-09 08:59
- Móvil Samsung Samsung Galaxy S6; Android 6.0.1: OK
- Móvil Samsung Galaxy S4; Android 4.4.2: Ok
- Móvil Motorola MotoE 4g; Android 6.0: Crashes
- Móvil LG D-805; Android 6.0.1: Ok
- Tablet ONDA V919 3G Air Dual OS; dual Windows y Android 4.4.4: crashes
- Tablet Lenovo Android 6.0.1: crashes

**Comment by niunani** [comment] 2017-04-27 05:46
Samsung Galaxy Active SM-T-365 Tablet with Android 5.1.1 : Crashes

**Comment by tethysgeco** [comment] 2017-06-29 08:44
I have the same problem.
SAMSUNG galaxy A5 crasches with version 0.9.10 (apk installation) but it works with 0.8.
Tablet ASUS ZenPad 3S crasches with both versions.
Does you know if exist a tablet that doesn’t have this problem? 
It’s a relevant limit if it couldn’t be fixed.

**Comment by m-kuhn** [comment] 2017-06-29 08:57
It works perfectly on the galaxy tab active and other devices.

It can be fixed it just needs some resources (someone to look into it or someone to sponsor us to look into it)

**Comment by mariano9898** [comment] 2017-07-22 16:51
I Mikel, I'm have the same problem when take a photo the application qfield reset and not save the photo.
My device is a Tablet Samsung Galaxy tab A6 with android 7. It's possible that i have to update my table to de android 6 and try? O how i resolve this problem thanks Mikel.

**Comment by mariano9898** [comment] 2017-07-22 22:01
Hi! I respond my own question, I downupdate the 7 Nougat to the 6 Mash... and the problem of the adding photos is fixed!

**Comment by m-kuhn** [comment] 2017-07-25 05:27
Thanks @mariano9898 that's valuable information

**Comment by lukaszurbuchen** [comment] 2017-09-20 09:03
Hi
I have the same error with Huawei Mediapad X2/GEM-701L Android 5.0.1 (and also with Mediapad X1, Android 4.2).
Would be nice if it will be fixed one day ;-)
Best regards
Lukas

**Comment by m-kuhn** [comment] 2017-09-20 09:37
It's an error somewhere deep down in some other library. We just invested some time to update all libraries but to no avail.
This is definitely on our radar high priority but so far with no luck.

**Comment by mrtwister3142** [comment] 2017-09-29 16:51
I have the same issue on Samsung Galaxy Tab A 2016 and Samsung Galaxy A3 2016 both running Android 7.0. Tested various versions from 0.9.0 to 0.10.1,

**Comment by jbostoen** [comment] 2017-10-10 11:30
As regular users, what could we do to help solve the camera crash issue?

Tried it on two smartphones; it crashes. (Huawei Ascend Y II, OnePlus 3). 
Would it be related to Android version? (I'm using Android 5.1 - Lollipop / my colleague is on 7.1.1 Nougat)

On my mother's Samsung Galaxy tablet, it works fine.

**Comment by StuartNorris** [comment] 2017-10-12 12:59
I've got the same issue on a Lenovo Tab3 10 (LenovoPad TB3-X70F) running Andriod 6.0

**Comment by ad-sige** [comment] 2017-10-18 06:42
Same problem on Android 7.0 Samsung S2 tab.
Works well on Galaxy Tab A6 (2016) with Android 5.1.1
Just bought brand new S2 Galaxy tabs to replace to slow A6 and start an ambitious data collection project on the Water network of Freetown after months of preparation and tests...Data colelction teams ready... Any help will be warmly welcome !

**Comment by VKolha** [comment] 2017-10-23 13:48
I have the same crashing problem on Huawei Honor  8 with Android 7.0 and Lenovo TAB3 10 Business with Android 6.0.

**Comment by jbostoen** [comment] 2017-10-23 19:17
Not sure if it may help, but I tried installing "Open Camera" and picked that as default camera app. QField still crashed.

**Comment by mrtwister3142** [comment] 2017-11-20 16:50
Could this be a permission-related problem? While reinstalling, I realized QFIELD never asks for granting camera permissions...

**Comment by zakigates** [comment] 2017-11-22 11:10
No it's not a permission issue. If you access to the permissions of the app you'll find just two (location, storage).

**Comment by salvioscogna** [comment] 2017-11-30 20:07
Hi, i've the same issue when saving picture. Tested on huawei M2-A01L running android 5.1.1.

**Comment by mikedufty** [comment] 2017-12-20 01:39
Same issue on Google Nexus 5x and Nexus 7 (2013)

**Comment by giedrioks26** [comment] 2017-12-25 01:53
Same issue on Blackview BV6000s (2017), Android 7.0

**Comment by vowasemp** [comment] 2018-01-23 11:02
same issue on Samsung Galaxy Tab Active2 (model SM-T395), Android 7.1.1

**Comment by ad-sige** [comment] 2018-01-24 08:46
Hello, 
Does someone from the development team read this topic and work on the issue ?
How can I help ?

**Comment by mbernasocchi** [comment] 2018-01-24 08:48
Yes, we do read, and are following this. we are looking into it. extra funding would definitely be beneficial to support the development

**Comment by saemiw** [comment] 2018-01-24 11:00
Can you approximate how much money you'd need to fix the issue? Maybe all the affected people can but something together (hail to the spirit of open source) and get the issue fixed.

**Comment by giedrioks26** [comment] 2018-01-24 11:14
> Can you approximate how much money you'd need to fix the issue? Maybe all the affected people can but something together (hail to the spirit of open source) and get the issue fixed.

I agree with this idea. We could put together a total budget if the amount is not high.

**Comment by ad-sige** [comment] 2018-01-24 14:53
Ok, My company, Sige is ok to participate to the effort if it allows a fast and reliable solution. How much would you need ?
Who else wants to be part of the effort ?

**Comment by saemiw** [comment] 2018-01-26 13:20
"my" company vogelwarte could only participate with a small financial support (about 200-300 Swiss Francs) as we are paying for the current bug fixing and functionality development (11'000 siwss francs). Our budget for this year is hence almost exhausted...

**Comment by mbernasocchi** [comment] 2018-01-26 13:31
@saemiw we know that and are extremely grateful :+1: 
@ad-sige, @giedrioks26 we are looking into getting a better idea of how much work is needed.

@ad-sige are you from the Sige in Vevey?

**Comment by ad-sige** [comment] 2018-01-26 13:36
Ok. No, I’m from Sige <http://www.sig-environnement.com/> in Morocco.
—
Alexandre Duclaux - Directeur
Sige | Solutions géographiques et immersives

www.sig-environnement.com <http://www.sig-environnement.com/>
Bureau + 212 5 37 65 91 09
Mobile Maroc: + 212 6 61 17 16 38
Mobile France: +33 7 69 10 88 89
32 Rue Ouled Ziane, Aviation, Rabat, Maroc Plan OSM <http://osm.org/go/b4oZYrEhv--?layers=N&m=>, Gmaps <https://www.google.fr/maps/place/Sige,+Soci%C3%A9t%C3%A9+d'ing%C3%A9nierie+g%C3%A9omatique+et+environnementale/@33.992439,-6.8260357,17z/data=!3m1!4b1!4m5!3m4!1s0xda76b6f50462d31:0xbf5c0d2cc4e237bc!8m2!3d33.992439!4d-6.823847>
Pour plus d'efficacité, nous consultons généralement nos e-mails à 11H et 16H. Pour les sujets urgents, merci de nous contacter par téléphone.

**Comment by Sete01** [comment] 2018-01-29 15:49
Hi, I've the same issue with a Galaxy Tab A6. Maybe I'll try the downgrade as suggested. Any news for the fix?

**Comment by pazadam** [comment] 2018-02-27 14:09
same issue with Lenovo TAB 2, Android 5.0.1 and Samsung Galaxy J5, Android 7.1.1
QField restarts, tested with shp and gpkg

**Comment by mrtwister3142** [comment] 2018-03-26 06:28
New camera implementation works perfectly on Samsung Galaxy A3 and Tab A. Great work guys, thanks!

**Closed** 2018-03-26 06:43 UTC

**Comment by yopyop25** [comment] 2018-04-12 12:28
New camera implementation works with oneplus one android 8.1 (lineageos 15.1 exactly), but with internal camera like camera Bacon it crash when i save...
