### ISSUE TITLE
Embedded layer doesn't display in QField

### ISSUE THREAD

**Issue by marcp1999** [opengisch/QField#279] opened 2018-04-24 16:23 UTC
I have a "master" map containing base layers that I use in many maps. I would like to be able to embed that map into other maps so that style changes and so on get carried forward into all maps, however I've found that embedded layers do not display in QField.

### Reproduction Steps:

1. Create a base map
2. Embed layers from base map into a second project
3. Copy second project and all dependent layers to QField
4. Open the project. The embedded layers are in the layer list but do not get displayed.

### Expected behavior:

I would like to be able to use embedded layers in maps destined for QField

**QField version:** [0.10.13]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Occurred at least in the last version... I just discovered embedded layers recently, so can't comment beyond that]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment] 2019-11-18 14:12
Hi @marcp1999
Do you have still this issue. Can you provide us a project we can reproduce?
Thanks

**Comment by signedav** [comment] 2019-12-04 11:36
Since I did not received a feedback I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:

**Closed by signedav** 2019-12-04 11:36 UTC
Labels: BUG, feedback
