### ISSUE TITLE
Qfield Crashes, when using the QR code scanner Feature for more than one Feature

### ISSUE THREAD

**Issue by Richterskala101** [opengisch/QField#4884] opened 2023-12-21 11:22 UTC
### Describe the issue
Qfield is crashing when the (QR) code scan tool (opened by the 3 dots beside the Field to fill in value) is opened.
Happens only when there was a Picture taken in advance and/or a Code scanned in advance

### Reproduction steps
1. Create and open a project, with one field for picture, one for text
2. Start digitizing/creating new features
3. Add a picture to the entry formula and scan a code, respective to fields
4. Save feature
5. Start adding a new feature and try to read a code

### Expected behavior
Qfield does read qr codes, when new feature is added

### Observed behavior
Qfield crashes when code reader is opened. Briefly, the shown camera preview window is freezing. Then immediate crash

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.30.2

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A52s 5G
 - OS: Android 13
 - QField version: 3.1.3 (14a255 v3.1.3) Qt 6.6.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unknown (Just started using the QR code Scan tool)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment] 2023-12-21 11:42
Known issue in upstream Qt library. A fix is being worked by the developers there and they are hopefully it'll be shipped in Qt 6.6.2, set to arrive in mid January 2024.

Until then, one workaround is to disable the native camera and rely on QField's own-grown camera. That will avoid crashes _as long as you do not lock your screen or put QField in the background_.

It's an unfortunate crasher that's out of our control, but we should see a fix real soon.

**Comment by nirvn** [comment] 2023-12-21 11:44
This is essentially a duplicate of https://github.com/opengisch/QField/issues/4860 but the description and steps are different enough to leave both open until upstream Qt ships a fixed version.

**Comment by nirvn** [comment] 2024-01-06 01:38
Fixed in QField 3.1.5

**Closed by nirvn** 2024-01-06 01:38 UTC
Labels: upstream
