### ISSUE TITLE
Adding children results in "database locked" after first feature

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1797] opened 2021-03-22 11:36 UTC
When adding children, this works fine on the first feature.
On the second feature, adding children doesn't work any more (add child attribute form is not shown) and an error is raised about database locked.

Workaround: click "reload layer" on parent layer. Once this is reloaded it works reliably.

![out](https://user-images.githubusercontent.com/588407/111984557-ce7afd80-8b0b-11eb-8706-43655e6461ef.gif)

QField 1.9.0

**Comment by nirvn** [comment] 2021-11-28 11:17
@m-kuhn , do you have this test project at hand? I'd like to have a look at this one.

**Comment by m-kuhn** [comment] 2021-11-28 11:35
sent by mail

**Comment by nirvn** [comment] 2021-11-28 12:40
Alright, closing this for two reasons:
1/ the problem - which isn't linked to child feature per say - is replicable on QGIS, so we're looking at an upstream issue (OGR or QGIS)
2/ the issue is linked to layers relying on some "SELECT *..." SQL statement as OGR vector layer subset string, which I'm not sure should work anyways ;-P

**Comment by nirvn** [comment] 2021-11-28 12:41
To add to this: I think virtual layers would probably be what is needed here.

**Closed by nirvn** 2021-11-28 12:41 UTC
