### ISSUE TITLE
Qfield crash while launching

### ISSUE THREAD

**Issue by ewaca** [opengisch/QField#2133] opened 2021-09-07 08:26 UTC
I need to start qfield twice or 3 times before it launch with success.
The device : crosscall trekker x3 with Android 6.0.1.
Qfield dev version does not launch at all.

No problem with both qfield version on other device with Android 11.

**Comment by m-kuhn** [comment] 2021-09-07 14:41
Thanks for reporting.
This has likely been fixed today, can you try to download and install https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-master-729b80bcec5149c0a633a4760e5909d1164ac4b1-arm64_v8a.apk ?

**Comment by ewaca** [comment] 2021-09-07 15:22
thanks for your answser.
now this Qfield dev version works after the 2nd launch. I have tried many time, and it work systematicly after 2 launch. It's much better than before, some time it didnt works after 5 or 6 launchs. Thank you !

**Comment by nirvn** [comment] 2021-09-07 15:47
@ewaca , thanks for the feedback. If you are able to provide a logcat for that remaining crasher, that'd be useful. The cause of the 6+ crashes is fixing, but there might be a different issue at play for that last crasher.

That said, I'm happily surprised to hear QField still runs on Android 6 ;)

**Comment by ewaca** [comment] 2021-09-08 08:31
@nirvn Android 6 is on the cell phone's compagny i can't flash new rom ^^
It's the first time i use the logcat, i don't know how to filter so there are thousands lines, hop you'll find something that help.
[qfield logcat.txt](https://github.com/opengisch/QField/files/7127249/qfield.logcat.txt)

**Comment by nirvn** [comment] 2021-09-08 08:36
@ewaca , thanks.

Relevant bits:
```
09-08 10:16:12.018   484   484 F DEBUG   : backtrace:
09-08 10:16:12.018   484   484 F DEBUG   :     #00 pc 0000000000005890  /system/bin/linker64 (__dl__Z19dlsym_linear_lookupPKcPP6soinfoS2_Pv+104)
09-08 10:16:12.018   484   484 F DEBUG   :     #01 pc 0000000000003100  /system/bin/linker64 (__dl_dlsym+84)
09-08 10:16:12.018   484   484 F DEBUG   :     #02 pc 00000000000f0e70  /data/app/ch.opengis.qfield_dev-1/lib/arm64/libplugins_platforms_qtforandroid_arm64-v8a.so
```

Looks like it'll be pretty hard to nail as it appears to be something happening on the Qt-side of things.

**Comment by ewaca** [comment] 2021-09-08 09:08
ok ... nevermind ... you know, today Qfield successfully launch at first launch, i had to launch Qfield many times to reproduce the crash.
it's stable enougth for my use, and i hope in a near futur, i'll get a new cellphone with higher android version ;)

**Comment by nirvn** [comment] 2021-10-02 06:56
We're going to close this issue here, @ewaca , thanks for reporting the original crash that stopped you from using QField altogether, and glad to hear things are now usable on Android 6.

**Closed by nirvn** 2021-10-02 06:56 UTC
